// Labor & Interaktive MINT/GeWi Simulationen Registry
// Vollstaendiges bilinguales Register fuer alle interaktiven 52 Labore & Simulationen
// Enthaelt systematische Fach- und Themenkategorien (DE/ZH) sowie Stufenzuordnung (EF/Q1/Q2).

export type LaborSimId =
  | "skate"
  | "pendulum"
  | "projectile"
  | "buoyancy"
  | "coulomb"
  | "spring"
  | "circuit"
  | "optics"
  | "optics-bench"
  | "gas"
  | "states-matter"
  | "under-pressure"
  | "diffusion"
  | "photoelectric"
  | "rutherford"
  | "hydrogen-atom"
  | "blackbody"
  | "molecule-shape"
  | "concentration"
  | "probability"
  | "membrane"
  | "neuron"
  | "vector"
  | "kinematik"
  | "schiefe-ebene"
  | "collision"
  | "lever"
  | "hooke"
  | "friction"
  | "titration"
  | "titration-lab"
  | "gleichgewicht"
  | "haber-bosch"
  | "osmose"
  | "tangent"
  | "box"
  | "markt"
  | "markt-welfare"
  | "orderbuch"
  | "gini"
  | "balance"
  | "wave"
  | "optics-lens"
  | "charges-fields"
  | "faraday"
  | "wave-string"
  | "orbit"
  | "ethik-waage"
  | "dilemma-theatre"
  | "magisches-viereck"
  | "trust-game"
  | "gewi-reading";

export type LaborFach = "Physik" | "Chemie" | "Bio" | "Mathe" | "SoWi" | "Philosophie" | "Deutsch";
export type LaborStufe = "EF" | "Q1" | "Q2";

export interface SimEntry {
  id: LaborSimId;
  fach: LaborFach;
  kategorieDE: string;
  kategorieZH: string;
  themenDE: string;
  themenZH: string;
  stufe: LaborStufe;
  titleDE: string;
  titleZH: string;
  descDE: string;
  descZH: string;
  formula: string;
  tags: string[];
}

export const SIMULATION_REGISTRY: SimEntry[] = [
  // ==========================================
  // PHYSIK (24 Labore)
  // ==========================================
  {
    id: "skate",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "力学与能量守恒",
    themenDE: "Energieerhaltung und Reibung",
    themenZH: "机械能转化与守恒定律",
    stufe: "EF",
    titleDE: "Energie-Skaterpark (Labor)",
    titleZH: "能量滑板场与机械能守恒 (Labor)",
    descDE: "U-Bahn/Rampe, potentielle/kinetische/thermische Energie, Reibungsdämpfung und dynamisches Kreisdiagramm.",
    descZH: "U型半管与斜坡滑道、动能/重力势能/内能实时转化饼图与柱状图、摩擦阻尼与机械能守恒定律。",
    formula: "E_{\\text{ges}} = E_{\\text{pot}} + E_{\\text{kin}} + E_{\\text{therm}} = \\text{konst.}",
    tags: ["Mechanik", "Energie", "Skater", "Reibung", "Labor"],
  },
  {
    id: "pendulum",
    fach: "Physik",
    kategorieDE: "Schwingungen & Wellen",
    kategorieZH: "机械振动与周期",
    themenDE: "Harmonische Schwingungen",
    themenZH: "单摆非线性摆动与重力加速度",
    stufe: "EF",
    titleDE: "Pendel-Labor & Schwingungsdauer (Labor)",
    titleZH: "单摆实验室与重力周期 (Labor)",
    descDE: "Exakte nichtlineare Pendelgleichung, Fadenlänge L, Photogate-Zeitmessung und Massenunabhängigkeit.",
    descZH: "精确非线性摆动微分方程、摆长 L 调控、光电门周期计时器与单摆周期与质量无关性验证。",
    formula: "T = 2\\pi\\sqrt{\\frac{L}{g}}",
    tags: ["Mechanik", "Pendel", "Gravitation", "Periode", "Labor"],
  },
  {
    id: "projectile",
    fach: "Physik",
    kategorieDE: "Kinematik & Ballistik",
    kategorieZH: "运动学与抛体运动",
    themenDE: "Zweidimensionale Bewegungen",
    themenZH: "平抛与斜抛弹道轨迹拟合",
    stufe: "EF",
    titleDE: "Wurfbewegung & Ballistik (Labor)",
    titleZH: "抛体运动与弹道射程 (Labor)",
    descDE: "Kanonenabschuss, Flugbahn-Trajektorie, Scheitelhöhe, Luftwiderstand und Zieltreffer-Simulation.",
    descZH: "大炮发射仰角调控、二次空气阻力模型、抛物线轨迹拟合、最大射高与地面靶标精准命中判定。",
    formula: "x(t) = v_0\\cos\\theta\\cdot t \\quad y(t) = h_0 + v_0\\sin\\theta\\cdot t - \\frac{1}{2}gt^2",
    tags: ["Mechanik", "Kinematik", "Ballistik", "Wurf", "Labor"],
  },
  {
    id: "buoyancy",
    fach: "Physik",
    kategorieDE: "Hydrostatik & Fluide",
    kategorieZH: "流体静力学与浮力",
    themenDE: "Fluiddynamik und Dichte",
    themenZH: "阿基米德浮力定律与沉浮条件",
    stufe: "EF",
    titleDE: "Dichte & Auftrieb / Archimedes (Labor)",
    titleZH: "密度与阿基米德浮力定律 (Labor)",
    descDE: "Eintauchtiefe, verdrängtes Flüssigkeitsvolumen, Auftriebskraft F_A vs. Gewichtskraft F_G und Waagenmessung.",
    descZH: "物体浸入深度、排开液体体积实时测量、浮力 F_A 与重力 F_G 矢量对比、浮沉条件与底部秤重。",
    formula: "F_A = \\rho_{\\text{Fluid}} \\cdot V_{\\text{sub}} \\cdot g",
    tags: ["Mechanik", "Hydrostatik", "Dichte", "Auftrieb", "Archimedes", "Labor"],
  },
  {
    id: "coulomb",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "静电学与场强分布",
    themenDE: "Elektrostatisches Feld",
    themenZH: "库仑定律与反平方力场",
    stufe: "Q1",
    titleDE: "Coulomb-Gesetz & Elektrostatik (Labor)",
    titleZH: "库仑定律与静电力反平方律 (Labor)",
    descDE: "Zwei Punktladungen auf Lineal, anziehende/abstoßende Kräfte, Vektoren und Abstandsgesetz F ~ 1/r².",
    descZH: "刻度尺双点电荷移动、库仑力大小科学计数法显示、同号相斥异号相吸力矢量与 1/r² 反平方律。",
    formula: "F = \\frac{1}{4\\pi\\varepsilon_0} \\frac{|q_1 q_2|}{r^2}",
    tags: ["Elektrizität", "Coulomb", "Kraft", "Ladung", "Labor"],
  },
  {
    id: "spring",
    fach: "Physik",
    kategorieDE: "Schwingungen & Wellen",
    kategorieZH: "机械振动与弹性势能",
    themenDE: "Federpendel & Oszillation",
    themenZH: "简谐振动与劲度系数",
    stufe: "EF",
    titleDE: "Masse-Feder-System & Schwingungslabor",
    titleZH: "弹簧振子与简谐振动实验室",
    descDE: "Harmonische Schwingung, Federkonstante D, Periodendauer T und Energieerhaltung (E_kin, E_spann).",
    descZH: "简谐振动、弹簧劲度系数 D、固有周期 T 与机械能守恒（动能与弹性势能转化）。",
    formula: "T = 2\\pi\\sqrt{\\frac{m}{D}}",
    tags: ["Mechanik", "Schwingung", "Energie", "Feder"],
  },
  {
    id: "circuit",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "直流电路与欧姆定律",
    themenDE: "Gleichstromkreise",
    themenZH: "欧姆定律与电功率测量",
    stufe: "EF",
    titleDE: "Virtueller Stromkreis & Ohmsches Gesetz",
    titleZH: "直流电路与欧姆定律实验室",
    descDE: "Elektronenfluss-Animation, Spannung U, Widerstand R, Stromstärke I und Glühlampenleistung.",
    descZH: "真实电子流定向移动动画、电压 U、电阻 R、电流强度 I 与白炽灯发光功率。",
    formula: "I = \\frac{U}{R} \\quad P = U \\cdot I",
    tags: ["Elektrizität", "Strom", "Spannung", "Widerstand"],
  },
  {
    id: "optics",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "几何光学与光的折射",
    themenDE: "Strahlenoptik und Reflexion",
    themenZH: "斯涅尔折射定律与全反射",
    stufe: "EF",
    titleDE: "Brechungsgesetz von Snellius & Totalreflexion",
    titleZH: "几何光学折射与全反射实验室",
    descDE: "Laserstrahl an Grenzflächen, Brechungsindizes n₁/n₂, Einfallslot und Grenzwinkel der Totalreflexion.",
    descZH: "激光束介质界面折射反射光路、折射率 n₁/n₂、法线与全反射临界角。",
    formula: "n_1 \\sin\\alpha = n_2 \\sin\\beta",
    tags: ["Optik", "Licht", "Brechung", "Laser"],
  },
  {
    id: "optics-bench",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "相干光波与光学工作台",
    themenDE: "Optische Medien & Fresnel",
    themenZH: "斯涅尔光学台与脉冲流动",
    stufe: "EF",
    titleDE: "OpticsBench: Snellius-Präzisionsbank (Labor)",
    titleZH: "斯涅尔高精度光学台与介质色散实验室",
    descDE: "Laser-Rotationsprüfstand mit Kohärenzpuls-Simulation, Fresnel-Intensitätsaufteilung und Brechungsindex-Presets.",
    descZH: "激光转角测试台、相干光脉冲流动、菲涅尔界面光强反射率分配与常见介质预设库。",
    formula: "n = \\frac{c_0}{c} \\quad R = \\left(\\frac{n_1 - n_2}{n_1 + n_2}\\right)^2",
    tags: ["Optik", "OpticsBench", "Brechung", "Fresnel", "Labor"],
  },
  {
    id: "kinematik",
    fach: "Physik",
    kategorieDE: "Kinematik & Ballistik",
    kategorieZH: "运动学与自由落体",
    themenDE: "Gleichförmig beschleunigte Bewegung",
    themenZH: "匀变速运动与加速度微积分",
    stufe: "EF",
    titleDE: "Kinematik-Labor & Bewegungsgesetze",
    titleZH: "匀变速运动与自由落体实验室",
    descDE: "Orts-, Geschwindigkeits- und Beschleunigungsdiagramme (s-t, v-t, a-t) für freies Fallen.",
    descZH: "位移-时间 s(t)、速度-时间 v(t) 与加速度-时间 a(t) 运动学规律与抛体曲线。",
    formula: "s(t) = \\frac{1}{2}at^2 + v_0 t",
    tags: ["Mechanik", "Kinematik", "Freier Fall", "Geschwindigkeit"],
  },
  {
    id: "schiefe-ebene",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "斜面受力分析与摩擦",
    themenDE: "Kräftezerlegung & Reibung",
    themenZH: "重力沿斜面分解与临界滑移",
    stufe: "EF",
    titleDE: "Schiefe Ebene & Kräftezerlegung",
    titleZH: "斜面力学分解与摩擦力实验室",
    descDE: "Kräftezerlegung am Hang: Hangabtriebskraft F_H, Normalkraft F_N und Haft-/Gleitreibungsgrenze.",
    descZH: "斜面受力分析：下滑分力 F_H、支持正压力 F_N 与静/动摩擦临界滑移条件。",
    formula: "F_{\\parallel} = mg\\sin\\alpha \\quad F_{\\perp} = mg\\cos\\alpha",
    tags: ["Mechanik", "Kräfte", "Reibung", "Hang", "Labor"],
  },
  {
    id: "collision",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "碰撞动力学与动量守恒",
    themenDE: "Impulserhaltung & Stöße",
    themenZH: "一维/二维弹性与非弹性碰撞",
    stufe: "EF",
    titleDE: "Stoß-Labor & Impulserhaltung (Labor)",
    titleZH: "二维弹性碰撞与动量守恒实验室",
    descDE: "Zwei Wagen auf Luftkissenbahn: Massen, Geschwindigkeiten, Impuls- und Energieerhaltung beim elastischen Stoß.",
    descZH: "气垫导轨双车碰撞：质量与初速调控、动量与动能守恒监视、质心系观察。",
    formula: "\\vec{p}_1 + \\vec{p}_2 = \\vec{p}'_1 + \\vec{p}'_2",
    tags: ["Mechanik", "Stoß", "Impuls", "Energie", "Labor"],
  },
  {
    id: "lever",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "静力学与力矩平衡",
    themenDE: "Starrkörper & Drehmoment",
    themenZH: "杠杆原理与力矩平衡方程",
    stufe: "EF",
    titleDE: "Drehmoment & Hebel-Gleichgewicht (Labor)",
    titleZH: "杠杆力矩平衡实验室",
    descDE: "Massen und Hebelarme beidseits der Drehachse: Drehmomentbilanz ΣM = 0 und Gleichgewichtsanzeige.",
    descZH: "支点两侧砝码质量与力臂调控：力矩平衡 ΣM = 0 与横梁平衡指示。",
    formula: "\\sum M = \\sum (F_i \\cdot l_i) = 0",
    tags: ["Mechanik", "Drehmoment", "Hebel", "Gleichgewicht", "Labor"],
  },
  {
    id: "hooke",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "弹性力学与胡克定律",
    themenDE: "Elastizität & Federkonstante",
    themenZH: "弹簧串并联等效刚度",
    stufe: "EF",
    titleDE: "Hookesches Gesetz & Feder-Kombination (Labor)",
    titleZH: "胡克定律与弹簧串并联实验室",
    descDE: "Federsteifigkeit k, Kraft-Verlängerungs-Diagramm, Reihen- und Parallelschaltung von Federn.",
    descZH: "劲度系数 k、力-伸长直线图、弹簧串并联等效刚度与弹性势能。",
    formula: "F = -k \\cdot \\Delta x",
    tags: ["Mechanik", "Feder", "Elastizität", "Energie", "Labor"],
  },
  {
    id: "friction",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "微观摩擦力与耗散",
    themenDE: "Reibungseffekte & Dissipation",
    themenZH: "最大静摩擦与滑动摩擦过渡",
    stufe: "EF",
    titleDE: "Haft- & Gleitreibung (Labor)",
    titleZH: "静摩擦与动摩擦过渡实验室",
    descDE: "Angreifende Kraft vs. Haftreibungsgrenze, Übergang zur Gleitreibung und Dissipationswärme.",
    descZH: "拉力与最大静摩临界、滑动过渡突降、摩擦耗散热累积与 F_R-F 图。",
    formula: "F_R \\le \\mu_s N \\quad F_{Gleit} = \\mu_k N",
    tags: ["Mechanik", "Reibung", "Dissipation", "Labor"],
  },
  {
    id: "under-pressure",
    fach: "Physik",
    kategorieDE: "Hydrostatik & Fluide",
    kategorieZH: "流体静压与连通器",
    themenDE: "Hydrostatischer Druck",
    themenZH: "液体压强公式与U型管差压",
    stufe: "EF",
    titleDE: "Hydrostatischer Druck & U-Rohr (Labor)",
    titleZH: "液体内部压强与连通器实验室",
    descDE: "Tiefensonde, Flüssigkeitsdichte, U-Rohr-Vergleich und Druck-Tiefe-Kennlinie p(h).",
    descZH: "深度探针拖拽、液体密度选择、U 型管对比与压强深度直线图。",
    formula: "p(h) = p_0 + \\rho g h",
    tags: ["Hydrostatik", "Druck", "Labor"],
  },
  {
    id: "wave",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "波动光学与干涉衍射",
    themenDE: "Welleninterferenz & Beugung",
    themenZH: "双缝干涉与波动光学图样",
    stufe: "Q1",
    titleDE: "Welleninterferenz & Doppelspalt (Labor)",
    titleZH: "波动干涉与杨氏双缝实验",
    descDE: "Zweiquellen-Interferenz, Wellenlänge λ, Spaltabstand d, Schirmabstand L und Intensitätsmuster.",
    descZH: "双点波源干涉场 60FPS 动态波前演化、波长 λ、双缝间距 d、干涉条纹间距与屏上光强分布曲线。",
    formula: "\\Delta y = \\frac{L \\cdot \\lambda}{d}",
    tags: ["Optik", "Wellen", "Interferenz", "Doppelspalt", "Labor"],
  },
  {
    id: "optics-lens",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "几何光学透镜成像",
    themenDE: "Linsengleichung & Abbildung",
    themenZH: "薄透镜成像方程与特殊光线",
    stufe: "EF",
    titleDE: "Dünne Linsen & Linsenabbildung (Labor)",
    titleZH: "凸透镜成像与三特殊光线实验室",
    descDE: "Brennweite f, Gegenstandsweite g, drei Hauptstrahlen, reelles/virtuelles Bild und Vergrößerung.",
    descZH: "焦距物距调控、三条特殊光线作图、实像虚像判定与放大率读数。",
    formula: "\\frac{1}{f} = \\frac{1}{g} + \\frac{1}{b}",
    tags: ["Optik", "Linse", "Abbildung", "Strahlen", "Labor"],
  },
  {
    id: "charges-fields",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "电场线与等势面分布",
    themenDE: "Elektrisches Potenzial",
    themenZH: "多点电荷电场与等势线绘制",
    stufe: "Q1",
    titleDE: "Ladungen & Feldlinien (Labor)",
    titleZH: "点电荷电场线与等势线实验室",
    descDE: "Punktladungen verschieben, Feldlinien-Tracing, Äquipotenziallinien und Sondenmessung von E und V.",
    descZH: "点电荷拖拽布场、电场线追踪、等势线与探针场强电势测量。",
    formula: "\\vec{E} = \\frac{\\vec{F}}{q}",
    tags: ["Elektrizität", "Feld", "Potenzial", "Labor"],
  },
  {
    id: "faraday",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "电磁感应与法拉第定律",
    themenDE: "Induktion & Magnetischer Fluss",
    themenZH: "磁通变化与楞次定律阻抗",
    stufe: "Q1",
    titleDE: "Elektromagnetische Induktion (Labor)",
    titleZH: "法拉第电磁感应实验室",
    descDE: "Magnet durch Spule, Flusskurve Φ(t), induzierte Spannung, Lampenhelligkeit und Lenz-Regel.",
    descZH: "磁铁穿线圈、磁通曲线、感应电动势极性大小、灯泡亮度与楞次定律。",
    formula: "\\mathcal{E} = -\\frac{d\\Phi}{dt}",
    tags: ["Elektromagnetismus", "Induktion", "Lenz", "Labor"],
  },
  {
    id: "wave-string",
    fach: "Physik",
    kategorieDE: "Schwingungen & Wellen",
    kategorieZH: "驻波振动与机械波谐振",
    themenDE: "Stehende Wellen & Resonanz",
    themenZH: "弦波反射、驻波节点与共振",
    stufe: "Q1",
    titleDE: "Seilwellen & Resonanz (Labor)",
    titleZH: "绳波传播与驻波谐振实验室",
    descDE: "Spannung T, Massenbelegung μ, Anregungsfrequenz f, festes/loses Ende und Resonanzbedingung.",
    descZH: "张力线密度频率调控、固定自由端反射、节点腹点标记与谐振判据。",
    formula: "v = \\sqrt{\\frac{T}{\\mu}} \\quad f_n = \\frac{nv}{2L}",
    tags: ["Wellen", "Resonanz", "Schwingung", "Labor"],
  },
  {
    id: "orbit",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "天体引力与天体轨道",
    themenDE: "Gravitation & Keplersche Gesetze",
    themenZH: "万有引力与开普勒三大定律",
    stufe: "EF",
    titleDE: "Gravitations- & Orbitallabor (Labor)",
    titleZH: "天体引力与开普勒轨道实验室 (Labor)",
    descDE: "Zentralgestirn, Umlaufbahnen, Keplersche Gesetze, Kreisbahn- und Fluchtgeschwindigkeit.",
    descZH: "开普勒三大行星运动定律、引力反平方场数值积分、初速度矢量调控、圆轨道与双曲线逃逸速度。",
    formula: "F = G\\frac{M \\cdot m}{r^2} \\quad v_k = \\sqrt{\\frac{GM}{r}}",
    tags: ["Astrophysik", "Gravitation", "Kepler", "Orbit", "Labor"],
  },
  {
    id: "photoelectric",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "量子理论与光电效应",
    themenDE: "Lichtquantenhypothese",
    themenZH: "爱因斯坦光电方程与普朗克常量",
    stufe: "Q2",
    titleDE: "Photoeffekt & Gegenfeldmethode (Labor)",
    titleZH: "光电效应与截止电压实验室",
    descDE: "Lichtfrequenz, Kathodenmaterial, Grenzfrequenz, Gegenspannung und Kennlinie des Photostroms.",
    descZH: "光频率强度、阴极材料、极限频率、截止电压与光电流特性曲线。",
    formula: "E_{\\text{kin,max}} = h\\nu - W_A",
    tags: ["Quanten", "Photon", "Labor"],
  },
  {
    id: "rutherford",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "原子物理与核式结构",
    themenDE: "Atommodelle & Streuung",
    themenZH: "卢瑟福散射与核电荷集中",
    stufe: "Q2",
    titleDE: "Rutherford-Streuung & Kernmodell (Labor)",
    titleZH: "卢瑟福散射与核式结构实验室",
    descDE: "Alpha-Teilchen, Stoßparameter, Coulomb-Abstoßung, Streuwinkel und Folgerung zum Kernmodell.",
    descZH: "α 粒子瞄准距离能量、库仑排斥轨道、散射角与核式结构结论。",
    formula: "\\theta = 2\\arctan\\frac{K}{2Eb}",
    tags: ["Atom", "Kern", "Streuung", "Labor"],
  },
  {
    id: "hydrogen-atom",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "原子物理与氢光谱",
    themenDE: "Bohrsches Atommodell",
    themenZH: "玻尔能级跃迁与巴尔末公式",
    stufe: "Q2",
    titleDE: "Bohr-Wasserstoffatom & Spektrallinien (Labor)",
    titleZH: "玻尔氢原子能级跃迁实验室",
    descDE: "Energieniveaus, Übergänge, Photonenenergie, Balmer-Serie und Absorptions-/Emissionsspektren.",
    descZH: "能级阶梯、跃迁选线、光子能量波长、巴尔末系与吸收发射光谱。",
    formula: "\\Delta E = h\\nu = E_n - E_m",
    tags: ["Atom", "Quanten", "Spektrum", "Labor"],
  },
  {
    id: "blackbody",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "黑体辐射与量子起源",
    themenDE: "Wärmestrahlung & Planck",
    themenZH: "普朗克黑体辐射与维恩位移",
    stufe: "Q2",
    titleDE: "Schwarzkörperstrahlung & Planck-Kurve (Labor)",
    titleZH: "黑体辐射谱与维恩位移实验室",
    descDE: "Temperatur, Planck-Kurve, Wiensches Verschiebungsgesetz und Stefan-Boltzmann-Leistung.",
    descZH: "温度调控、普朗克曲线、维恩位移峰值与辐射总功率。",
    formula: "\\lambda_{\\max}T = b",
    tags: ["Quanten", "Strahlung", "Thermodynamik", "Labor"],
  },

  // ==========================================
  // CHEMIE (9 Labore)
  // ==========================================
  {
    id: "titration",
    fach: "Chemie",
    kategorieDE: "Säure-Base & Analytik",
    kategorieZH: "酸碱理论与滴定分析",
    themenDE: "Säure-Base-Gleichgewichte",
    themenZH: "pH 滴定曲线与指示剂变色",
    stufe: "EF",
    titleDE: "pH-Skala & Säure-Base-Titration",
    titleZH: "酸碱溶液与 pH 滴定实验室",
    descDE: "Büretten-Titration, Indikatorfarben (Bromthymolblau, Phenolphthalein) und Äquivalenzpunkt.",
    descZH: "滴定管酸碱中和计量、指示剂变色梯级与化学计量等当点曲线。",
    formula: "\\text{pH} = -\\log_{10}[H_3O^+]",
    tags: ["Säure", "Base", "pH", "Titration", "Indikator"],
  },
  {
    id: "titration-lab",
    fach: "Chemie",
    kategorieDE: "Säure-Base & Analytik",
    kategorieZH: "电位滴定与突跃微观舱",
    themenDE: "Ionenkonzentration & pH-Sprung",
    themenZH: "强酸强碱突跃微观对数雪崩",
    stufe: "EF",
    titleDE: "TitrationLab: pH-Sprung & Ionen-Kaskade (Labor)",
    titleZH: "电位滴定与离子雪崩突跃微观实验室",
    descDE: "Sokratisches Schritt-Labor zum logarithmischen pH-Sprung von 4 auf 10 am Äquivalenzpunkt mit Mikroskop-Simulation.",
    descZH: "等当点（25mL）酸碱中和对数雪崩跳跃微观剖析、指示剂显色与苏格拉底递进式问答。",
    formula: "[H_3O^+] \\cdot [OH^-] = 10^{-14} \\; \\text{mol}^2/\\text{L}^2",
    tags: ["Chemie", "TitrationLab", "Säure", "Base", "pH-Sprung", "Labor"],
  },
  {
    id: "gleichgewicht",
    fach: "Chemie",
    kategorieDE: "Gleichgewicht & Kinetik",
    kategorieZH: "化学平衡与勒夏特列原理",
    themenDE: "Massenwirkungsgesetz & Gleichgewicht",
    themenZH: "平衡常数与外加条件扰动转移",
    stufe: "Q1",
    titleDE: "Chemisches Gleichgewicht & Le Chatelier",
    titleZH: "化学平衡与勒夏特列原理实验室",
    descDE: "Druck- und Temperaturverschiebung, Gaskompressor und Reaktionsquotient Q vs. K_c.",
    descZH: "压力活塞加压、吸放热温度干扰与勒夏特列分子碰撞动态平衡转移。",
    formula: "K_c = \\frac{[C]^c [D]^d}{[A]^a [B]^b}",
    tags: ["Gleichgewicht", "Thermodynamik", "Le Chatelier", "Kinetik"],
  },
  {
    id: "haber-bosch",
    fach: "Chemie",
    kategorieDE: "Gleichgewicht & Kinetik",
    kategorieZH: "工业化学与高压合成动力学",
    themenDE: "Ammoniaksynthese & Stoßtheorie",
    themenZH: "哈伯-博施法动态反应器",
    stufe: "Q1",
    titleDE: "Haber-Bosch-Lab: 60FPS Stoßreaktor (Labor)",
    titleZH: "哈伯法合成氨高压反应动力学实验室",
    descDE: "60FPS mikroskopischer Teilchenkollisionsreaktor, Kompressorkolben und Le-Chatelier-Ausweichreaktion.",
    descZH: "60FPS 分子微观碰撞动力学引擎、活塞加压体积压缩与温度-压力工业平衡产率寻优。",
    formula: "N_2 + 3H_2 \\rightleftharpoons 2NH_3 \\quad \\Delta H = -92{,}4 \\; \\text{kJ/mol}",
    tags: ["Gleichgewicht", "HaberBosch", "Kinetik", "Stöße", "Labor"],
  },
  {
    id: "gas",
    fach: "Chemie",
    kategorieDE: "Gase & Thermodynamik",
    kategorieZH: "气体定律与分子热运动",
    themenDE: "Gasgesetze & Kinetische Gastheorie",
    themenZH: "理想气体状态方程与玻尔兹曼分布",
    stufe: "EF",
    titleDE: "Ideales Gasgesetz & Teilchenbewegung (Labor)",
    titleZH: "理想气体状态方程与分子热运动实验室",
    descDE: "Movable Piston, manometrischer Druck p, absolute Temperatur T (Kelvin) und Boyle-Mariotte.",
    descZH: "活塞容积压缩、压力表测压、开尔文温度与波义耳-马略特气体定律。",
    formula: "p \\cdot V = n \\cdot R \\cdot T",
    tags: ["Thermodynamik", "Gase", "Druck", "Temperatur", "Labor"],
  },
  {
    id: "states-matter",
    fach: "Chemie",
    kategorieDE: "Gase & Thermodynamik",
    kategorieZH: "物质三态与相变潜热",
    themenDE: "Aggregatzustände & Phasen",
    themenZH: "三态微观粒子模型与相变平台",
    stufe: "EF",
    titleDE: "Aggregatzustände & Phasenübergang (Labor)",
    titleZH: "物质三态与熔沸相变实验室",
    descDE: "Teilchenmodell fest/flüssig/gasförmig, Schmelz- und Siedepunkt, latente Wärme und Heizkurve.",
    descZH: "三态粒子模型、熔沸点平台、潜热与加热冷却曲线。",
    formula: "Q = m \\cdot c \\cdot \\Delta T \\quad Q = m \\cdot L",
    tags: ["Thermodynamik", "Phasen", "Teilchen", "Labor"],
  },
  {
    id: "diffusion",
    fach: "Chemie",
    kategorieDE: "Lösungen & Diffusion",
    kategorieZH: "溶液扩散与热运动",
    themenDE: "Diffusion & Entropie",
    themenZH: "费克扩散定律与浓度均一化",
    stufe: "EF",
    titleDE: "Teilchendiffusion & Fick-Gesetz (Labor)",
    titleZH: "粒子扩散与浓度平衡实验室",
    descDE: "Konzentrationsgradient, Teilchenmasse, Temperatur und Konzentrations-Zeit-Kurve bis zum Gleichgewicht.",
    descZH: "浓度梯度、分子质量、温度影响与浓度时间平衡曲线。",
    formula: "J \\propto -\\Delta c",
    tags: ["Teilchen", "Diffusion", "Gleichgewicht", "Labor"],
  },
  {
    id: "molecule-shape",
    fach: "Chemie",
    kategorieDE: "Molekülstruktur & Bindung",
    kategorieZH: "分子构型与价层互斥",
    themenDE: "Chemische Bindung & VSEPR",
    themenZH: "VSEPR 理论与空间杂化构型",
    stufe: "EF",
    titleDE: "VSEPR Molekülgeometrie (Labor)",
    titleZH: "价层电子对互斥构型实验室",
    descDE: "AXE-Klassen, Bindungswinkel, freie Elektronenpaare und Drehansicht der Moleküle.",
    descZH: "AXE 构型切换、键角实测、孤对压缩与分子旋转视图。",
    formula: "\\text{AX}_m\\text{E}_n",
    tags: ["Moleküle", "VSEPR", "Geometrie", "Labor"],
  },
  {
    id: "concentration",
    fach: "Chemie",
    kategorieDE: "Lösungen & Diffusion",
    kategorieZH: "溶液浓度与比尔定律",
    themenDE: "Stoffmengenkonzentration & Photometrie",
    themenZH: "吸光度定量分析与标准工作曲线",
    stufe: "Q1",
    titleDE: "Molarität & Lambert-Beer-Gesetz (Labor)",
    titleZH: "溶液浓度与比尔定律实验室",
    descDE: "Konzentration, Schichtdicke, Extinktionskoeffizient und Kalibriergerade des Photometers.",
    descZH: "浓度光程系数调控、透射颜色、吸光度校准直线与检测器读数。",
    formula: "A = \\varepsilon \\cdot c \\cdot d",
    tags: ["Lösungen", "Spektroskopie", "Labor"],
  },

  // ==========================================
  // BIOLOGIE (3 Labore)
  // ==========================================
  {
    id: "membrane",
    fach: "Bio",
    kategorieDE: "Zellbiologie & Membrantransport",
    kategorieZH: "细胞生物学与跨膜运输",
    themenDE: "Biomembranen & Stofftransport",
    themenZH: "主动运输与被动扩散动力学",
    stufe: "EF",
    titleDE: "Membrantransport & ATP-Pumpe (Labor)",
    titleZH: "细胞膜转运与钠钾泵实验室",
    descDE: "Doppellipidschicht, Kanal vs. Pumpe, Sättigungskinetik und ATP-Verbrauch.",
    descZH: "磷脂双层、通道与泵切换、饱和动力学曲线与 ATP 消耗计数。",
    formula: "v = \\frac{V_{\\max} \\cdot S}{K_m + S}",
    tags: ["Zellbiologie", "Membran", "Transport", "Labor"],
  },
  {
    id: "neuron",
    fach: "Bio",
    kategorieDE: "Neurobiologie & Erregungsleitung",
    kategorieZH: "神经生物学与动作电位",
    themenDE: "Neuronale Informationsverarbeitung",
    themenZH: "动作电位形成与离子通道时序",
    stufe: "Q1",
    titleDE: "Aktionspotenzial & Ionenkanäle (Labor)",
    titleZH: "神经元动作电位实验室",
    descDE: "Reizstärke, Schwelle, Na+/K+-Kanaldynamik, vier Phasen und Refraktärzeit.",
    descZH: "刺激强度阈值、钠钾通道时序、四相标注与不应期阻断。",
    formula: "C_M\\frac{dV}{dt} = -\\sum I_{\\text{ion}} + I_{\\text{ext}}",
    tags: ["Neurobiologie", "Potenzial", "Labor"],
  },
  {
    id: "osmose",
    fach: "Bio",
    kategorieDE: "Zellbiologie & Membrantransport",
    kategorieZH: "渗透压与质壁分离",
    themenDE: "Wasserhaushalt der Pflanze",
    themenZH: "半透膜渗透平衡与水势方程",
    stufe: "EF",
    titleDE: "Osmose, Turgor & Plasmolyse-Labor",
    titleZH: "细胞渗透压与质壁分离微观实验室",
    descDE: "Semipermeable Biomembran, Konzentrationsgradient, Vakuolenvolumen und Hämolyse.",
    descZH: "选择透过性半透膜、细胞内外溶质浓度梯度、原生质体脱壁与红细胞溶血。",
    formula: "\\Psi = \\Psi_s + \\Psi_p",
    tags: ["Zellbiologie", "Membran", "Wasserpotenzial", "Plasmolyse"],
  },

  // ==========================================
  // MATHEMATIK (4 Labore)
  // ==========================================
  {
    id: "tangent",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "微积分与导数切线",
    themenDE: "Differentialrechnung & Ableitung",
    themenZH: "割线斜率极限逼近与瞬间导数",
    stufe: "EF",
    titleDE: "Differential- & Tangenten-Simulator",
    titleZH: "导数切线极限逼近沙盒",
    descDE: "Sekantensteigung Δy/Δx im Grenzübergang h → 0 zur Tangentensteigung f'(x).",
    descZH: "割线斜率在 Δx→0 极限逼近瞬间切线斜率 f'(x) 的几何微分直观。",
    formula: "f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}",
    tags: ["Analysis", "Ableitung", "Grenzwert", "Tangente"],
  },
  {
    id: "vector",
    fach: "Mathe",
    kategorieDE: "Vektorrechnung & Geometrie",
    kategorieZH: "空间向量与几何加法",
    themenDE: "Analytische Geometrie & Vektoren",
    themenZH: "二维/三维向量加法与点积正交",
    stufe: "EF",
    titleDE: "Vektor-Addition & Kräfte-Parallelogramm",
    titleZH: "二维向量加法与力学平行四边形",
    descDE: "Vektorkomponenten in 2D, Resultierende c = a + b, Betrag und Skalarprodukt.",
    descZH: "二维向量直角坐标分量、平行四边形定则合向量 c = a + b 与向量点积。",
    formula: "\\vec{c} = \\vec{a} + \\vec{b}",
    tags: ["Lineare Algebra", "Vektoren", "Kräfte", "Geometrie"],
  },
  {
    id: "box",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "极值问题与约束条件优化",
    themenDE: "Extremwertprobleme mit Nebenbedingungen",
    themenZH: "纸盒容积优化与驻点二阶导数判别",
    stufe: "EF",
    titleDE: "Box-Optimizer (Extremwert-Probleme)",
    titleZH: "长方体容积极值优化沙盒",
    descDE: "Eckenausschnitt x optimieren für maximales Volumen V(x) mit erster und zweiter Ableitung.",
    descZH: "角部切块 x 动态优化最大容积 V(x)，一阶导数为零与二阶导数判别极值。",
    formula: "V'(x) = 0 \\quad V''(x) < 0",
    tags: ["Analysis", "Extremwert", "Optimierung", "Volumen"],
  },
  {
    id: "probability",
    fach: "Mathe",
    kategorieDE: "Stochastik & Wahrscheinlichkeit",
    kategorieZH: "概率论与大数定律",
    themenDE: "Binomial- & Normalverteilung",
    themenZH: "高尔顿板下落二项分布拟合",
    stufe: "EF",
    titleDE: "Galton-Brett & Normalverteilung (Labor)",
    titleZH: "高尔顿板与正态分布实验室",
    descDE: "Nagelschichten, Kugelzahl, Binomial-Histogramm, Normal-Anpassung und Gesetz der großen Zahlen.",
    descZH: "钉层球数调控、二项直方图、正态拟合曲线与大数定律收敛。",
    formula: "P(k) = \\binom{n}{k} p^k (1-p)^{n-k}",
    tags: ["Stochastik", "Verteilung", "Labor"],
  },

  // ==========================================
  // SOWI / WIRTSCHAFT (6 Labore)
  // ==========================================
  {
    id: "markt",
    fach: "SoWi",
    kategorieDE: "Marktmechanismus & Mikroökonomie",
    kategorieZH: "微观经济与市场均衡",
    themenDE: "Preisbildung & Marktkräfte",
    themenZH: "供求曲线相交与消费者剩余",
    stufe: "EF",
    titleDE: "Markt-Mechanismus & Wohlfahrts-Simulator",
    titleZH: "供求曲线与市场价格机制沙盘",
    descDE: "Angebot und Nachfrage, Marktpreisbildung, Mindest-/Höchstpreise und Konsumentenrente.",
    descZH: "供求曲线平移、市场出清均衡价 P*、价格干预与消费者/生产者剩余。",
    formula: "Q_S(P) = Q_D(P)",
    tags: ["Wirtschaft", "Markt", "Preis", "Wohlfahrt"],
  },
  {
    id: "markt-welfare",
    fach: "SoWi",
    kategorieDE: "Marktmechanismus & Mikroökonomie",
    kategorieZH: "市场干预与福利经济学",
    themenDE: "Staatliche Eingriffe & Wohlfahrtsverlust",
    themenZH: "最低限价与无谓损失几何剖析",
    stufe: "Q1",
    titleDE: "MarktWelfareLab: Wohlfahrtsverlust (Labor)",
    titleZH: "市场干预、福利几何与无谓损失沙盘",
    descDE: "Tufte-geometrischer Prüfstand für Mindestpreis P_min, Konsumentenrente, Produzentenrente und Deadweight Loss (DWL).",
    descZH: "最低限价干预管制沙盘、透光多边形展示消费者剩余 (CS)、生产者剩余 (PS) 与社会总福利无谓损失 (DWL)。",
    formula: "\\text{DWL} = \\frac{1}{2} (P - P_{\\text{Anbieter}}) \\cdot (Q^* - Q_{\\text{trans}})",
    tags: ["SoWi", "Wohlfahrt", "DWL", "Mindestpreis", "Labor"],
  },
  {
    id: "orderbuch",
    fach: "SoWi",
    kategorieDE: "Finanzmärkte & Handel",
    kategorieZH: "金融市场与订单簿撮合",
    themenDE: "Börsenhandel & Preisfindung",
    themenZH: "Xetra 连续双向拍卖与滑点",
    stufe: "Q1",
    titleDE: "OrderbuchSimulator: Xetra-Matching (Labor)",
    titleZH: "证券交易所限价订单簿与深度撮合实验室",
    descDE: "Xetra-Orderbuch-Matching, Geld/Brief-Spanne (Spread), Ausführungsrisiko, Slippage und Stop-Loss-Orders.",
    descZH: "实时多档买卖深度撮合、买卖价差 Spread、市价单执行滑点损失与止损委托触发仿真。",
    formula: "\\text{Spread} = P_{\\text{Brief}} - P_{\\text{Geld}}",
    tags: ["SoWi", "Börse", "Orderbuch", "Slippage", "Labor"],
  },
  {
    id: "gini",
    fach: "SoWi",
    kategorieDE: "Sozialstruktur & Ungleichheit",
    kategorieZH: "社会结构与财富分配",
    themenDE: "Einkommens- und Vermögensverteilung",
    themenZH: "洛伦茨曲线积分与基尼系数",
    stufe: "EF",
    titleDE: "Gini-Koeffizient & Lorenz-Kurve",
    titleZH: "基尼系数与洛伦茨收入分配沙盒",
    descDE: "Einkommens- und Vermögensverteilung, Lorenz-Kurve und Ungleichheitsmaße.",
    descZH: "5大阶层财富分配调节、洛伦茨曲线积分与社会不平等基尼系数判定。",
    formula: "G = \\frac{A}{A + B}",
    tags: ["Soziologie", "Verteilung", "Gini", "Ungleichheit"],
  },
  {
    id: "magisches-viereck",
    fach: "SoWi",
    kategorieDE: "Makroökonomie & Wirtschaftspolitik",
    kategorieZH: "宏观调控与经济稳定",
    themenDE: "Stabilitätsgesetz 1967 & Konjunktur",
    themenZH: "经济四大目标冲突与宏观博弈",
    stufe: "Q1",
    titleDE: "Magisches Viereck (§ 1 StabG 1967)",
    titleZH: "宏观经济魔术四角形博弈沙盘",
    descDE: "Stabilitätsgesetz 1967: Wirtschaftswachstum, Vollbeschäftigung, Preisstabilität und Außenbeitrag im Zielkonflikt.",
    descZH: "增长、充分就业、物价稳定与对外经济平衡四大目标冲突，菲利普斯曲线与货币财政调控沙盘。",
    formula: "Y = C + I + G + (X - M) \\quad \\text{Zielkonflikt: } \\text{ALQ} \\leftrightarrow \\text{Inflation}",
    tags: ["Wirtschaft", "SoWi", "Konjunktur", "Stabilitätsgesetz", "EZB", "Fiskalpolitik", "Labor"],
  },
  {
    id: "trust-game",
    fach: "SoWi",
    kategorieDE: "Spieltheorie & Verhaltensökonomie",
    kategorieZH: "博弈论与合作演化",
    themenDE: "Gefangenendilemma & Vertrauen",
    themenZH: "以牙还牙策略与制度信任演化",
    stufe: "EF",
    titleDE: "TrustGameSim: Vertrauensspiel & Evolution (Labor)",
    titleZH: "信任博弈演化与纳什均衡仿真沙盘",
    descDE: "Evolutionäre Spieltheorie: Tit-for-Tat, Trittbrettfahrer, Sanktionskosten und Vertrauensindex im Agenten-Netzwerk.",
    descZH: "演化博弈论：以牙还牙（Tit-for-Tat）、搭便车背叛者、法律制裁成本与多智能体社会信任指数动态推演。",
    formula: "\\text{Payoff: } T > R > P > S \\quad (2R > T + S)",
    tags: ["SoWi", "Spieltheorie", "Vertrauen", "Tit-for-Tat", "Labor"],
  },

  // ==========================================
  // PHILOSOPHIE (3 Labore)
  // ==========================================
  {
    id: "balance",
    fach: "Philosophie",
    kategorieDE: "Dialektische Urteilsbildung",
    kategorieZH: "辩证裁决与论证结构",
    themenDE: "Sachurteil vs. Werturteil",
    themenZH: "事实依据与价值准则双轨平衡",
    stufe: "EF",
    titleDE: "Dialektische Urteils-Waage",
    titleZH: "辩证事实裁决与伦理价值天平",
    descDE: "Sachurteil vs. Werturteil: Abwägen von Pro- und Contra-Argumenten nach Kant & Utilitarismus.",
    descZH: "事实裁决（有效性）与价值裁决（合法性/伦理尊严）多维论据配重与定论推导。",
    formula: "\\text{Urteil} = f(\\text{Sachkriterien}, \\text{Wertkriterien})",
    tags: ["Ethik", "Philosophie", "Urteilsbildung", "Klausur"],
  },
  {
    id: "ethik-waage",
    fach: "Philosophie",
    kategorieDE: "Normative Ethik & Dilemma",
    kategorieZH: "规范伦理与两难决策",
    themenDE: "Kantische Deontologie vs. Utilitarismus",
    themenZH: "定言命令四步检验法与快乐算盘",
    stufe: "EF",
    titleDE: "Ethik-Waage und Dilemma-Entscheidung",
    titleZH: "伦理道德天平与双轨决策工坊",
    descDE: "Utilitarismus vs. Kantische Deontologie: Hedonistisches Kalkuel, Maximenpruefung und Antinomien.",
    descZH: "边沁快乐量度法定量净效用 vs 康德定言命令四步检验法（普遍法则与目的自身公式）。",
    formula: "\\Delta U = \\sum (F - L) \\quad \\text{vs.} \\quad \\text{Maximenpruefung}",
    tags: ["Ethik", "Philosophie", "Kant", "Utilitarismus", "Dilemma", "Labor"],
  },
  {
    id: "dilemma-theatre",
    fach: "Philosophie",
    kategorieDE: "Normative Ethik & Dilemma",
    kategorieZH: "道德两难剧场与情境抉择",
    themenDE: "Trolley-Dilemma & Autonomie",
    themenZH: "电车难题、器官分配与善意谎言",
    stufe: "Q1",
    titleDE: "DilemmaTheatre: 4-Akt-Ethikbühne (Labor)",
    titleZH: "通用伦理两难剧场与四幕沉浸抉择台",
    descDE: "Interaktives 4-Akt-Dilemma-Theater: Trolley-Problem, Organtransplantation und Wahrhaftigkeitspflicht mit Klausur-Urteilskarte.",
    descZH: "四幕沉浸式伦理剧场：电车转向、ICU 稀缺器官分配与绝对说真话义务，附带高考满分评价模板与答题卡。",
    formula: "\\text{Kategorischer Imperativ: Handle nur nach derjenigen Maxime...}",
    tags: ["Philosophie", "DilemmaTheatre", "Trolley", "Ethik", "Labor"],
  },

  // ==========================================
  // DEUTSCH / GEWI (1 Labor)
  // ==========================================
  {
    id: "gewi-reading",
    fach: "Deutsch",
    kategorieDE: "Textanalyse & Hermeneutik",
    kategorieZH: "文学戏剧解剖与原典精读",
    themenDE: "Dramen- & Sachtextanalyse",
    themenZH: "歌德《浮士德》与学术原典解剖",
    stufe: "EF",
    titleDE: "GeWiReadingLab: Sechsdimensionale Textlupe (Labor)",
    titleZH: "文科学术原典精读与六维戏剧解剖工坊",
    descDE: "Tufte-inspirierte Textlupe für Goethes Faust, Kants Anthropologie und Borchert: Versanalyse, Metrik, Leitbegriffe und Klausur-Satzbau.",
    descZH: "北威州高中会考经典选段精读：浮士德之夜独白、康德启蒙宣言与博尔歇特废墟文学，逐行诗韵、修辞格与学术论证装配。",
    formula: "\\text{Textdeutung} = \\text{Hypothese} + \\text{Belegkette} + \\text{Funktion}",
    tags: ["Deutsch", "GeWiReadingLab", "Faust", "Textanalyse", "Hermeneutik", "Labor"],
  },
];
