// Labor & Interaktive MINT/GeWi Simulationen Registry
// Vollstaendiges bilinguales Register fuer alle interaktiven 94 Labore & Simulationen
// Enthaelt systematische Fach- und Themenkategorien (DE/ZH) sowie Stufenzuordnung (EF/Q1/Q2).

export type LaborSimId =
  | "skate"
  | "pendulum"
  | "projectile"
  | "buoyancy"
  | "coulomb"
  | "spring"
  | "circuit"
  | "optics"
  | "optics-bench"
  | "gas"
  | "states-matter"
  | "under-pressure"
  | "diffusion"
  | "photoelectric"
  | "rutherford"
  | "hydrogen-atom"
  | "blackbody"
  | "molecule-shape"
  | "concentration"
  | "probability"
  | "membrane"
  | "neuron"
  | "vector"
  | "kinematik"
  | "schiefe-ebene"
  | "collision"
  | "lever"
  | "hooke"
  | "friction"
  | "titration"
  | "titration-lab"
  | "gleichgewicht"
  | "haber-bosch"
  | "osmose"
  | "tangent"
  | "box"
  | "markt"
  | "markt-welfare"
  | "orderbuch"
  | "gini"
  | "balance"
  | "wave"
  | "optics-lens"
  | "charges-fields"
  | "faraday"
  | "wave-string"
  | "orbit"
  | "ethik-waage"
  | "dilemma-theatre"
  | "magisches-viereck"
  | "trust-game"
  | "gewi-reading"
  // Chemie (6 neue Labore)
  | "chemie-galvanische-zelle"
  | "chemie-elektrolyse"
  | "chemie-puffer-hasselbalch"
  | "chemie-sn1-sn2"
  | "chemie-polymerisation"
  | "chemie-komplexchemie"
  // Bio (9 neue Labore)
  | "bio-fotosynthese"
  | "bio-zellatmung"
  | "bio-enzymkinetik"
  | "bio-genetik-kreuzung"
  | "bio-synapse"
  | "bio-oekologie-raeuber-beute"
  | "bio-dna-pcr"
  | "bio-epigenetik"
  | "bio-oekologie-see"
  // Mathe (9 neue Labore)
  | "mathe-integral-flaeche"
  | "mathe-kurvendiskussion"
  | "mathe-funktionenscharen"
  | "mathe-rotationskoerper"
  | "mathe-ebene-abstand"
  | "mathe-vektor-skalar-kreuz"
  | "mathe-markov-ketten"
  | "mathe-hypothesentest"
  | "mathe-korrelation-regression"
  // SoWi (7 neue Labore)
  | "sowi-sinus-milieus"
  | "sowi-konjunktur-zyklus"
  | "sowi-ezb-geldpolitik"
  | "sowi-sozialstaat-transfer"
  | "sowi-trilemma-trilemma"
  | "sowi-globalisierung-trade"
  | "sowi-standort-deutschland"
  // Philosophie (7 neue Labore)
  | "philo-kant-kategorischer"
  | "philo-hoehlengleichnis"
  | "philo-staatsvertrag"
  | "philo-rawls-schleier"
  | "philo-willensfreiheit"
  | "philo-popper-falsifikation"
  | "philo-arendt-banalitaet"
  // Deutsch (6 neue Labore)
  | "deutsch-drama-freytag"
  | "deutsch-lyrik-metrum"
  | "deutsch-brecht-episch"
  | "deutsch-kafka-verwandlung"
  | "deutsch-borchert-draussen"
  | "deutsch-sachtext-argument";

export type LaborFach = "Physik" | "Chemie" | "Bio" | "Mathe" | "SoWi" | "Philosophie" | "Deutsch";
export type LaborStufe = "EF" | "Q1" | "Q2";

export interface SimEntry {
  id: LaborSimId;
  fach: LaborFach;
  kategorieDE: string;
  kategorieZH: string;
  themenDE: string;
  themenZH: string;
  stufe: LaborStufe;
  titleDE: string;
  titleZH: string;
  descDE: string;
  descZH: string;
  formula: string;
  tags: string[];
}

export const SIMULATION_REGISTRY: SimEntry[] = [
  // ==========================================
  // PHYSIK (24 Labore)
  // ==========================================
  {
    id: "skate",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "力学与能量守恒",
    themenDE: "Energieerhaltung und Reibung",
    themenZH: "机械能转化与守恒定律",
    stufe: "EF",
    titleDE: "Energie-Skaterpark (Labor)",
    titleZH: "能量滑板场与机械能守恒 (Labor)",
    descDE: "U-Bahn/Rampe, potentielle/kinetische/thermische Energie, Reibungsdämpfung und dynamisches Kreisdiagramm.",
    descZH: "U型半管与斜坡滑道、动能/重力势能/内能实时转化饼图与柱状图、摩擦阻尼与机械能守恒定律。",
    formula: "E_{\\text{ges}} = E_{\\text{pot}} + E_{\\text{kin}} + E_{\\text{therm}} = \\text{konst.}",
    tags: ["Mechanik", "Energie", "Skater", "Reibung", "Labor"],
  },
  {
    id: "pendulum",
    fach: "Physik",
    kategorieDE: "Schwingungen & Wellen",
    kategorieZH: "机械振动与周期",
    themenDE: "Harmonische Schwingungen",
    themenZH: "单摆非线性摆动与重力加速度",
    stufe: "EF",
    titleDE: "Pendel-Labor & Schwingungsdauer (Labor)",
    titleZH: "单摆实验室与重力周期 (Labor)",
    descDE: "Exakte nichtlineare Pendelgleichung, Fadenlänge L, Photogate-Zeitmessung und Massenunabhängigkeit.",
    descZH: "精确非线性摆动微分方程、摆长 L 调控、光电门周期计时器与单摆周期与质量无关性验证。",
    formula: "T = 2\\pi\\sqrt{\\frac{L}{g}}",
    tags: ["Mechanik", "Pendel", "Gravitation", "Periode", "Labor"],
  },
  {
    id: "projectile",
    fach: "Physik",
    kategorieDE: "Kinematik & Ballistik",
    kategorieZH: "运动学与抛体运动",
    themenDE: "Zweidimensionale Bewegungen",
    themenZH: "平抛与斜抛弹道轨迹拟合",
    stufe: "EF",
    titleDE: "Wurfbewegung & Ballistik (Labor)",
    titleZH: "抛体运动与弹道射程 (Labor)",
    descDE: "Kanonenabschuss, Flugbahn-Trajektorie, Scheitelhöhe, Luftwiderstand und Zieltreffer-Simulation.",
    descZH: "大炮发射仰角调控、二次空气阻力模型、抛物线轨迹拟合、最大射高与地面靶标精准命中判定。",
    formula: "x(t) = v_0\\cos\\theta\\cdot t \\quad y(t) = h_0 + v_0\\sin\\theta\\cdot t - \\frac{1}{2}gt^2",
    tags: ["Mechanik", "Kinematik", "Ballistik", "Wurf", "Labor"],
  },
  {
    id: "buoyancy",
    fach: "Physik",
    kategorieDE: "Hydrostatik & Fluide",
    kategorieZH: "流体静力学与浮力",
    themenDE: "Fluiddynamik und Dichte",
    themenZH: "阿基米德浮力定律与沉浮条件",
    stufe: "EF",
    titleDE: "Dichte & Auftrieb / Archimedes (Labor)",
    titleZH: "密度与阿基米德浮力定律 (Labor)",
    descDE: "Eintauchtiefe, verdrängtes Flüssigkeitsvolumen, Auftriebskraft F_A vs. Gewichtskraft F_G und Waagenmessung.",
    descZH: "物体浸入深度、排开液体体积实时测量、浮力 F_A 与重力 F_G 矢量对比、浮沉条件与底部秤重。",
    formula: "F_A = \\rho_{\\text{Fluid}} \\cdot V_{\\text{sub}} \\cdot g",
    tags: ["Mechanik", "Hydrostatik", "Dichte", "Auftrieb", "Archimedes", "Labor"],
  },
  {
    id: "coulomb",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "静电学与场强分布",
    themenDE: "Elektrostatisches Feld",
    themenZH: "库仑定律与反平方力场",
    stufe: "Q1",
    titleDE: "Coulomb-Gesetz & Elektrostatik (Labor)",
    titleZH: "库仑定律与静电力反平方律 (Labor)",
    descDE: "Zwei Punktladungen auf Lineal, anziehende/abstoßende Kräfte, Vektoren und Abstandsgesetz F ~ 1/r².",
    descZH: "刻度尺双点电荷移动、库仑力大小科学计数法显示、同号相斥异号相吸力矢量与 1/r² 反平方律。",
    formula: "F = \\frac{1}{4\\pi\\varepsilon_0} \\frac{|q_1 q_2|}{r^2}",
    tags: ["Elektrizität", "Coulomb", "Kraft", "Ladung", "Labor"],
  },
  {
    id: "spring",
    fach: "Physik",
    kategorieDE: "Schwingungen & Wellen",
    kategorieZH: "机械振动与弹性势能",
    themenDE: "Federpendel & Oszillation",
    themenZH: "简谐振动与劲度系数",
    stufe: "EF",
    titleDE: "Masse-Feder-System & Schwingungslabor",
    titleZH: "弹簧振子与简谐振动实验室",
    descDE: "Harmonische Schwingung, Federkonstante D, Periodendauer T und Energieerhaltung (E_kin, E_spann).",
    descZH: "简谐振动、弹簧劲度系数 D、固有周期 T 与机械能守恒（动能与弹性势能转化）。",
    formula: "T = 2\\pi\\sqrt{\\frac{m}{D}}",
    tags: ["Mechanik", "Schwingung", "Energie", "Feder"],
  },
  {
    id: "circuit",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "直流电路与欧姆定律",
    themenDE: "Gleichstromkreise",
    themenZH: "欧姆定律与电功率测量",
    stufe: "EF",
    titleDE: "Virtueller Stromkreis & Ohmsches Gesetz",
    titleZH: "直流电路与欧姆定律实验室",
    descDE: "Elektronenfluss-Animation, Spannung U, Widerstand R, Stromstärke I und Glühlampenleistung.",
    descZH: "真实电子流定向移动动画、电压 U、电阻 R、电流强度 I 与白炽灯发光功率。",
    formula: "I = \\frac{U}{R} \\quad P = U \\cdot I",
    tags: ["Elektrizität", "Strom", "Spannung", "Widerstand"],
  },
  {
    id: "optics",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "几何光学与光的折射",
    themenDE: "Strahlenoptik und Reflexion",
    themenZH: "斯涅尔折射定律与全反射",
    stufe: "EF",
    titleDE: "Brechungsgesetz von Snellius & Totalreflexion",
    titleZH: "几何光学折射与全反射实验室",
    descDE: "Laserstrahl an Grenzflächen, Brechungsindizes n₁/n₂, Einfallslot und Grenzwinkel der Totalreflexion.",
    descZH: "激光束介质界面折射反射光路、折射率 n₁/n₂、法线与全反射临界角。",
    formula: "n_1 \\sin\\alpha = n_2 \\sin\\beta",
    tags: ["Optik", "Licht", "Brechung", "Laser"],
  },
  {
    id: "optics-bench",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "相干光波与光学工作台",
    themenDE: "Optische Medien & Fresnel",
    themenZH: "斯涅尔光学台与脉冲流动",
    stufe: "EF",
    titleDE: "OpticsBench: Snellius-Präzisionsbank (Labor)",
    titleZH: "斯涅尔高精度光学台与介质色散实验室",
    descDE: "Laser-Rotationsprüfstand mit Kohärenzpuls-Simulation, Fresnel-Intensitätsaufteilung und Brechungsindex-Presets.",
    descZH: "激光转角测试台、相干光脉冲流动、菲涅尔界面光强反射率分配与常见介质预设库。",
    formula: "n = \\frac{c_0}{c} \\quad R = \\left(\\frac{n_1 - n_2}{n_1 + n_2}\\right)^2",
    tags: ["Optik", "OpticsBench", "Brechung", "Fresnel", "Labor"],
  },
  {
    id: "kinematik",
    fach: "Physik",
    kategorieDE: "Kinematik & Ballistik",
    kategorieZH: "运动学与自由落体",
    themenDE: "Gleichförmig beschleunigte Bewegung",
    themenZH: "匀变速运动与加速度微积分",
    stufe: "EF",
    titleDE: "Kinematik-Labor & Bewegungsgesetze",
    titleZH: "匀变速运动与自由落体实验室",
    descDE: "Orts-, Geschwindigkeits- und Beschleunigungsdiagramme (s-t, v-t, a-t) für freies Fallen.",
    descZH: "位移-时间 s(t)、速度-时间 v(t) 与加速度-时间 a(t) 运动学规律与抛体曲线。",
    formula: "s(t) = \\frac{1}{2}at^2 + v_0 t",
    tags: ["Mechanik", "Kinematik", "Freier Fall", "Geschwindigkeit"],
  },
  {
    id: "schiefe-ebene",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "斜面受力分析与摩擦",
    themenDE: "Kräftezerlegung & Reibung",
    themenZH: "重力沿斜面分解与临界滑移",
    stufe: "EF",
    titleDE: "Schiefe Ebene & Kräftezerlegung",
    titleZH: "斜面力学分解与摩擦力实验室",
    descDE: "Kräftezerlegung am Hang: Hangabtriebskraft F_H, Normalkraft F_N und Haft-/Gleitreibungsgrenze.",
    descZH: "斜面受力分析：下滑分力 F_H、支持正压力 F_N 与静/动摩擦临界滑移条件。",
    formula: "F_{\\parallel} = mg\\sin\\alpha \\quad F_{\\perp} = mg\\cos\\alpha",
    tags: ["Mechanik", "Kräfte", "Reibung", "Hang", "Labor"],
  },
  {
    id: "collision",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "碰撞动力学与动量守恒",
    themenDE: "Impulserhaltung & Stöße",
    themenZH: "一维/二维弹性与非弹性碰撞",
    stufe: "EF",
    titleDE: "Stoß-Labor & Impulserhaltung (Labor)",
    titleZH: "二维弹性碰撞与动量守恒实验室",
    descDE: "Zwei Wagen auf Luftkissenbahn: Massen, Geschwindigkeiten, Impuls- und Energieerhaltung beim elastischen Stoß.",
    descZH: "气垫导轨双车碰撞：质量与初速调控、动量与动能守恒监视、质心系观察。",
    formula: "\\vec{p}_1 + \\vec{p}_2 = \\vec{p}'_1 + \\vec{p}'_2",
    tags: ["Mechanik", "Stoß", "Impuls", "Energie", "Labor"],
  },
  {
    id: "lever",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "静力学与力矩平衡",
    themenDE: "Starrkörper & Drehmoment",
    themenZH: "杠杆原理与力矩平衡方程",
    stufe: "EF",
    titleDE: "Drehmoment & Hebel-Gleichgewicht (Labor)",
    titleZH: "杠杆力矩平衡实验室",
    descDE: "Massen und Hebelarme beidseits der Drehachse: Drehmomentbilanz ΣM = 0 und Gleichgewichtsanzeige.",
    descZH: "支点两侧砝码质量与力臂调控：力矩平衡 ΣM = 0 与横梁平衡指示。",
    formula: "\\sum M = \\sum (F_i \\cdot l_i) = 0",
    tags: ["Mechanik", "Drehmoment", "Hebel", "Gleichgewicht", "Labor"],
  },
  {
    id: "hooke",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "弹性力学与胡克定律",
    themenDE: "Elastizität & Federkonstante",
    themenZH: "弹簧串并联等效刚度",
    stufe: "EF",
    titleDE: "Hookesches Gesetz & Feder-Kombination (Labor)",
    titleZH: "胡克定律与弹簧串并联实验室",
    descDE: "Federsteifigkeit k, Kraft-Verlängerungs-Diagramm, Reihen- und Parallelschaltung von Federn.",
    descZH: "劲度系数 k、力-伸长直线图、弹簧串并联等效刚度与弹性势能。",
    formula: "F = -k \\cdot \\Delta x",
    tags: ["Mechanik", "Feder", "Elastizität", "Energie", "Labor"],
  },
  {
    id: "friction",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "微观摩擦力与耗散",
    themenDE: "Reibungseffekte & Dissipation",
    themenZH: "最大静摩擦与滑动摩擦过渡",
    stufe: "EF",
    titleDE: "Haft- & Gleitreibung (Labor)",
    titleZH: "静摩擦与动摩擦过渡实验室",
    descDE: "Angreifende Kraft vs. Haftreibungsgrenze, Übergang zur Gleitreibung und Dissipationswärme.",
    descZH: "拉力与最大静摩临界、滑动过渡突降、摩擦耗散热累积与 F_R-F 图。",
    formula: "F_R \\le \\mu_s N \\quad F_{Gleit} = \\mu_k N",
    tags: ["Mechanik", "Reibung", "Dissipation", "Labor"],
  },
  {
    id: "under-pressure",
    fach: "Physik",
    kategorieDE: "Hydrostatik & Fluide",
    kategorieZH: "流体静压与连通器",
    themenDE: "Hydrostatischer Druck",
    themenZH: "液体压强公式与U型管差压",
    stufe: "EF",
    titleDE: "Hydrostatischer Druck & U-Rohr (Labor)",
    titleZH: "液体内部压强与连通器实验室",
    descDE: "Tiefensonde, Flüssigkeitsdichte, U-Rohr-Vergleich und Druck-Tiefe-Kennlinie p(h).",
    descZH: "深度探针拖拽、液体密度选择、U 型管对比与压强深度直线图。",
    formula: "p(h) = p_0 + \\rho g h",
    tags: ["Hydrostatik", "Druck", "Labor"],
  },
  {
    id: "wave",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "波动光学与干涉衍射",
    themenDE: "Welleninterferenz & Beugung",
    themenZH: "双缝干涉与波动光学图样",
    stufe: "Q1",
    titleDE: "Welleninterferenz & Doppelspalt (Labor)",
    titleZH: "波动干涉与杨氏双缝实验",
    descDE: "Zweiquellen-Interferenz, Wellenlänge λ, Spaltabstand d, Schirmabstand L und Intensitätsmuster.",
    descZH: "双点波源干涉场 60FPS 动态波前演化、波长 λ、双缝间距 d、干涉条纹间距与屏上光强分布曲线。",
    formula: "\\Delta y = \\frac{L \\cdot \\lambda}{d}",
    tags: ["Optik", "Wellen", "Interferenz", "Doppelspalt", "Labor"],
  },
  {
    id: "optics-lens",
    fach: "Physik",
    kategorieDE: "Optik & Licht",
    kategorieZH: "几何光学透镜成像",
    themenDE: "Linsengleichung & Abbildung",
    themenZH: "薄透镜成像方程与特殊光线",
    stufe: "EF",
    titleDE: "Dünne Linsen & Linsenabbildung (Labor)",
    titleZH: "凸透镜成像与三特殊光线实验室",
    descDE: "Brennweite f, Gegenstandsweite g, drei Hauptstrahlen, reelles/virtuelles Bild und Vergrößerung.",
    descZH: "焦距物距调控、三条特殊光线作图、实像虚像判定与放大率读数。",
    formula: "\\frac{1}{f} = \\frac{1}{g} + \\frac{1}{b}",
    tags: ["Optik", "Linse", "Abbildung", "Strahlen", "Labor"],
  },
  {
    id: "charges-fields",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "电场线与等势面分布",
    themenDE: "Elektrisches Potenzial",
    themenZH: "多点电荷电场与等势线绘制",
    stufe: "Q1",
    titleDE: "Ladungen & Feldlinien (Labor)",
    titleZH: "点电荷电场线与等势线实验室",
    descDE: "Punktladungen verschieben, Feldlinien-Tracing, Äquipotenziallinien und Sondenmessung von E und V.",
    descZH: "点电荷拖拽布场、电场线追踪、等势线与探针场强电势测量。",
    formula: "\\vec{E} = \\frac{\\vec{F}}{q}",
    tags: ["Elektrizität", "Feld", "Potenzial", "Labor"],
  },
  {
    id: "faraday",
    fach: "Physik",
    kategorieDE: "Elektrizität & Magnetismus",
    kategorieZH: "电磁感应与法拉第定律",
    themenDE: "Induktion & Magnetischer Fluss",
    themenZH: "磁通变化与楞次定律阻抗",
    stufe: "Q1",
    titleDE: "Elektromagnetische Induktion (Labor)",
    titleZH: "法拉第电磁感应实验室",
    descDE: "Magnet durch Spule, Flusskurve Φ(t), induzierte Spannung, Lampenhelligkeit und Lenz-Regel.",
    descZH: "磁铁穿线圈、磁通曲线、感应电动势极性大小、灯泡亮度与楞次定律。",
    formula: "\\mathcal{E} = -\\frac{d\\Phi}{dt}",
    tags: ["Elektromagnetismus", "Induktion", "Lenz", "Labor"],
  },
  {
    id: "wave-string",
    fach: "Physik",
    kategorieDE: "Schwingungen & Wellen",
    kategorieZH: "驻波振动与机械波谐振",
    themenDE: "Stehende Wellen & Resonanz",
    themenZH: "弦波反射、驻波节点与共振",
    stufe: "Q1",
    titleDE: "Seilwellen & Resonanz (Labor)",
    titleZH: "绳波传播与驻波谐振实验室",
    descDE: "Spannung T, Massenbelegung μ, Anregungsfrequenz f, festes/loses Ende und Resonanzbedingung.",
    descZH: "张力线密度频率调控、固定自由端反射、节点腹点标记与谐振判据。",
    formula: "v = \\sqrt{\\frac{T}{\\mu}} \\quad f_n = \\frac{nv}{2L}",
    tags: ["Wellen", "Resonanz", "Schwingung", "Labor"],
  },
  {
    id: "orbit",
    fach: "Physik",
    kategorieDE: "Mechanik & Energie",
    kategorieZH: "天体引力与天体轨道",
    themenDE: "Gravitation & Keplersche Gesetze",
    themenZH: "万有引力与开普勒三大定律",
    stufe: "EF",
    titleDE: "Gravitations- & Orbitallabor (Labor)",
    titleZH: "天体引力与开普勒轨道实验室 (Labor)",
    descDE: "Zentralgestirn, Umlaufbahnen, Keplersche Gesetze, Kreisbahn- und Fluchtgeschwindigkeit.",
    descZH: "开普勒三大行星运动定律、引力反平方场数值积分、初速度矢量调控、圆轨道与双曲线逃逸速度。",
    formula: "F = G\\frac{M \\cdot m}{r^2} \\quad v_k = \\sqrt{\\frac{GM}{r}}",
    tags: ["Astrophysik", "Gravitation", "Kepler", "Orbit", "Labor"],
  },
  {
    id: "photoelectric",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "量子理论与光电效应",
    themenDE: "Lichtquantenhypothese",
    themenZH: "爱因斯坦光电方程与普朗克常量",
    stufe: "Q2",
    titleDE: "Photoeffekt & Gegenfeldmethode (Labor)",
    titleZH: "光电效应与截止电压实验室",
    descDE: "Lichtfrequenz, Kathodenmaterial, Grenzfrequenz, Gegenspannung und Kennlinie des Photostroms.",
    descZH: "光频率强度、阴极材料、极限频率、截止电压与光电流特性曲线。",
    formula: "E_{\\text{kin,max}} = h\\nu - W_A",
    tags: ["Quanten", "Photon", "Labor"],
  },
  {
    id: "rutherford",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "原子物理与核式结构",
    themenDE: "Atommodelle & Streuung",
    themenZH: "卢瑟福散射与核电荷集中",
    stufe: "Q2",
    titleDE: "Rutherford-Streuung & Kernmodell (Labor)",
    titleZH: "卢瑟福散射与核式结构实验室",
    descDE: "Alpha-Teilchen, Stoßparameter, Coulomb-Abstoßung, Streuwinkel und Folgerung zum Kernmodell.",
    descZH: "α 粒子瞄准距离能量、库仑排斥轨道、散射角与核式结构结论。",
    formula: "\\theta = 2\\arctan\\frac{K}{2Eb}",
    tags: ["Atom", "Kern", "Streuung", "Labor"],
  },
  {
    id: "hydrogen-atom",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "原子物理与氢光谱",
    themenDE: "Bohrsches Atommodell",
    themenZH: "玻尔能级跃迁与巴尔末公式",
    stufe: "Q2",
    titleDE: "Bohr-Wasserstoffatom & Spektrallinien (Labor)",
    titleZH: "玻尔氢原子能级跃迁实验室",
    descDE: "Energieniveaus, Übergänge, Photonenenergie, Balmer-Serie und Absorptions-/Emissionsspektren.",
    descZH: "能级阶梯、跃迁选线、光子能量波长、巴尔末系与吸收发射光谱。",
    formula: "\\Delta E = h\\nu = E_n - E_m",
    tags: ["Atom", "Quanten", "Spektrum", "Labor"],
  },
  {
    id: "blackbody",
    fach: "Physik",
    kategorieDE: "Atom- & Quantenphysik",
    kategorieZH: "黑体辐射与量子起源",
    themenDE: "Wärmestrahlung & Planck",
    themenZH: "普朗克黑体辐射与维恩位移",
    stufe: "Q2",
    titleDE: "Schwarzkörperstrahlung & Planck-Kurve (Labor)",
    titleZH: "黑体辐射谱与维恩位移实验室",
    descDE: "Temperatur, Planck-Kurve, Wiensches Verschiebungsgesetz und Stefan-Boltzmann-Leistung.",
    descZH: "温度调控、普朗克曲线、维恩位移峰值与辐射总功率。",
    formula: "\\lambda_{\\max}T = b",
    tags: ["Quanten", "Strahlung", "Thermodynamik", "Labor"],
  },

  // ==========================================
  // CHEMIE (9 Labore)
  // ==========================================
  {
    id: "titration",
    fach: "Chemie",
    kategorieDE: "Säure-Base & Analytik",
    kategorieZH: "酸碱理论与滴定分析",
    themenDE: "Säure-Base-Gleichgewichte",
    themenZH: "pH 滴定曲线与指示剂变色",
    stufe: "EF",
    titleDE: "pH-Skala & Säure-Base-Titration",
    titleZH: "酸碱溶液与 pH 滴定实验室",
    descDE: "Büretten-Titration, Indikatorfarben (Bromthymolblau, Phenolphthalein) und Äquivalenzpunkt.",
    descZH: "滴定管酸碱中和计量、指示剂变色梯级与化学计量等当点曲线。",
    formula: "\\text{pH} = -\\log_{10}[H_3O^+]",
    tags: ["Säure", "Base", "pH", "Titration", "Indikator"],
  },
  {
    id: "titration-lab",
    fach: "Chemie",
    kategorieDE: "Säure-Base & Analytik",
    kategorieZH: "电位滴定与突跃微观舱",
    themenDE: "Ionenkonzentration & pH-Sprung",
    themenZH: "强酸强碱突跃微观对数雪崩",
    stufe: "EF",
    titleDE: "TitrationLab: pH-Sprung & Ionen-Kaskade (Labor)",
    titleZH: "电位滴定与离子雪崩突跃微观实验室",
    descDE: "Sokratisches Schritt-Labor zum logarithmischen pH-Sprung von 4 auf 10 am Äquivalenzpunkt mit Mikroskop-Simulation.",
    descZH: "等当点（25mL）酸碱中和对数雪崩跳跃微观剖析、指示剂显色与苏格拉底递进式问答。",
    formula: "[H_3O^+] \\cdot [OH^-] = 10^{-14} \\; \\text{mol}^2/\\text{L}^2",
    tags: ["Chemie", "TitrationLab", "Säure", "Base", "pH-Sprung", "Labor"],
  },
  {
    id: "gleichgewicht",
    fach: "Chemie",
    kategorieDE: "Gleichgewicht & Kinetik",
    kategorieZH: "化学平衡与勒夏特列原理",
    themenDE: "Massenwirkungsgesetz & Gleichgewicht",
    themenZH: "平衡常数与外加条件扰动转移",
    stufe: "Q1",
    titleDE: "Chemisches Gleichgewicht & Le Chatelier",
    titleZH: "化学平衡与勒夏特列原理实验室",
    descDE: "Druck- und Temperaturverschiebung, Gaskompressor und Reaktionsquotient Q vs. K_c.",
    descZH: "压力活塞加压、吸放热温度干扰与勒夏特列分子碰撞动态平衡转移。",
    formula: "K_c = \\frac{[C]^c [D]^d}{[A]^a [B]^b}",
    tags: ["Gleichgewicht", "Thermodynamik", "Le Chatelier", "Kinetik"],
  },
  {
    id: "haber-bosch",
    fach: "Chemie",
    kategorieDE: "Gleichgewicht & Kinetik",
    kategorieZH: "工业化学与高压合成动力学",
    themenDE: "Ammoniaksynthese & Stoßtheorie",
    themenZH: "哈伯-博施法动态反应器",
    stufe: "Q1",
    titleDE: "Haber-Bosch-Lab: 60FPS Stoßreaktor (Labor)",
    titleZH: "哈伯法合成氨高压反应动力学实验室",
    descDE: "60FPS mikroskopischer Teilchenkollisionsreaktor, Kompressorkolben und Le-Chatelier-Ausweichreaktion.",
    descZH: "60FPS 分子微观碰撞动力学引擎、活塞加压体积压缩与温度-压力工业平衡产率寻优。",
    formula: "N_2 + 3H_2 \\rightleftharpoons 2NH_3 \\quad \\Delta H = -92{,}4 \\; \\text{kJ/mol}",
    tags: ["Gleichgewicht", "HaberBosch", "Kinetik", "Stöße", "Labor"],
  },
  {
    id: "gas",
    fach: "Chemie",
    kategorieDE: "Gase & Thermodynamik",
    kategorieZH: "气体定律与分子热运动",
    themenDE: "Gasgesetze & Kinetische Gastheorie",
    themenZH: "理想气体状态方程与玻尔兹曼分布",
    stufe: "EF",
    titleDE: "Ideales Gasgesetz & Teilchenbewegung (Labor)",
    titleZH: "理想气体状态方程与分子热运动实验室",
    descDE: "Movable Piston, manometrischer Druck p, absolute Temperatur T (Kelvin) und Boyle-Mariotte.",
    descZH: "活塞容积压缩、压力表测压、开尔文温度与波义耳-马略特气体定律。",
    formula: "p \\cdot V = n \\cdot R \\cdot T",
    tags: ["Thermodynamik", "Gase", "Druck", "Temperatur", "Labor"],
  },
  {
    id: "states-matter",
    fach: "Chemie",
    kategorieDE: "Gase & Thermodynamik",
    kategorieZH: "物质三态与相变潜热",
    themenDE: "Aggregatzustände & Phasen",
    themenZH: "三态微观粒子模型与相变平台",
    stufe: "EF",
    titleDE: "Aggregatzustände & Phasenübergang (Labor)",
    titleZH: "物质三态与熔沸相变实验室",
    descDE: "Teilchenmodell fest/flüssig/gasförmig, Schmelz- und Siedepunkt, latente Wärme und Heizkurve.",
    descZH: "三态粒子模型、熔沸点平台、潜热与加热冷却曲线。",
    formula: "Q = m \\cdot c \\cdot \\Delta T \\quad Q = m \\cdot L",
    tags: ["Thermodynamik", "Phasen", "Teilchen", "Labor"],
  },
  {
    id: "diffusion",
    fach: "Chemie",
    kategorieDE: "Lösungen & Diffusion",
    kategorieZH: "溶液扩散与热运动",
    themenDE: "Diffusion & Entropie",
    themenZH: "费克扩散定律与浓度均一化",
    stufe: "EF",
    titleDE: "Teilchendiffusion & Fick-Gesetz (Labor)",
    titleZH: "粒子扩散与浓度平衡实验室",
    descDE: "Konzentrationsgradient, Teilchenmasse, Temperatur und Konzentrations-Zeit-Kurve bis zum Gleichgewicht.",
    descZH: "浓度梯度、分子质量、温度影响与浓度时间平衡曲线。",
    formula: "J \\propto -\\Delta c",
    tags: ["Teilchen", "Diffusion", "Gleichgewicht", "Labor"],
  },
  {
    id: "molecule-shape",
    fach: "Chemie",
    kategorieDE: "Molekülstruktur & Bindung",
    kategorieZH: "分子构型与价层互斥",
    themenDE: "Chemische Bindung & VSEPR",
    themenZH: "VSEPR 理论与空间杂化构型",
    stufe: "EF",
    titleDE: "VSEPR Molekülgeometrie (Labor)",
    titleZH: "价层电子对互斥构型实验室",
    descDE: "AXE-Klassen, Bindungswinkel, freie Elektronenpaare und Drehansicht der Moleküle.",
    descZH: "AXE 构型切换、键角实测、孤对压缩与分子旋转视图。",
    formula: "\\text{AX}_m\\text{E}_n",
    tags: ["Moleküle", "VSEPR", "Geometrie", "Labor"],
  },
  {
    id: "concentration",
    fach: "Chemie",
    kategorieDE: "Lösungen & Diffusion",
    kategorieZH: "溶液浓度与比尔定律",
    themenDE: "Stoffmengenkonzentration & Photometrie",
    themenZH: "吸光度定量分析与标准工作曲线",
    stufe: "Q1",
    titleDE: "Molarität & Lambert-Beer-Gesetz (Labor)",
    titleZH: "溶液浓度与比尔定律实验室",
    descDE: "Konzentration, Schichtdicke, Extinktionskoeffizient und Kalibriergerade des Photometers.",
    descZH: "浓度光程系数调控、透射颜色、吸光度校准直线与检测器读数。",
    formula: "A = \\varepsilon \\cdot c \\cdot d",
    tags: ["Lösungen", "Spektroskopie", "Labor"],
  },

  // ==========================================
  // BIOLOGIE (3 Labore)
  // ==========================================
  {
    id: "membrane",
    fach: "Bio",
    kategorieDE: "Zellbiologie & Membrantransport",
    kategorieZH: "细胞生物学与跨膜运输",
    themenDE: "Biomembranen & Stofftransport",
    themenZH: "主动运输与被动扩散动力学",
    stufe: "EF",
    titleDE: "Membrantransport & ATP-Pumpe (Labor)",
    titleZH: "细胞膜转运与钠钾泵实验室",
    descDE: "Doppellipidschicht, Kanal vs. Pumpe, Sättigungskinetik und ATP-Verbrauch.",
    descZH: "磷脂双层、通道与泵切换、饱和动力学曲线与 ATP 消耗计数。",
    formula: "v = \\frac{V_{\\max} \\cdot S}{K_m + S}",
    tags: ["Zellbiologie", "Membran", "Transport", "Labor"],
  },
  {
    id: "neuron",
    fach: "Bio",
    kategorieDE: "Neurobiologie & Erregungsleitung",
    kategorieZH: "神经生物学与动作电位",
    themenDE: "Neuronale Informationsverarbeitung",
    themenZH: "动作电位形成与离子通道时序",
    stufe: "Q1",
    titleDE: "Aktionspotenzial & Ionenkanäle (Labor)",
    titleZH: "神经元动作电位实验室",
    descDE: "Reizstärke, Schwelle, Na+/K+-Kanaldynamik, vier Phasen und Refraktärzeit.",
    descZH: "刺激强度阈值、钠钾通道时序、四相标注与不应期阻断。",
    formula: "C_M\\frac{dV}{dt} = -\\sum I_{\\text{ion}} + I_{\\text{ext}}",
    tags: ["Neurobiologie", "Potenzial", "Labor"],
  },
  {
    id: "osmose",
    fach: "Bio",
    kategorieDE: "Zellbiologie & Membrantransport",
    kategorieZH: "渗透压与质壁分离",
    themenDE: "Wasserhaushalt der Pflanze",
    themenZH: "半透膜渗透平衡与水势方程",
    stufe: "EF",
    titleDE: "Osmose, Turgor & Plasmolyse-Labor",
    titleZH: "细胞渗透压与质壁分离微观实验室",
    descDE: "Semipermeable Biomembran, Konzentrationsgradient, Vakuolenvolumen und Hämolyse.",
    descZH: "选择透过性半透膜、细胞内外溶质浓度梯度、原生质体脱壁与红细胞溶血。",
    formula: "\\Psi = \\Psi_s + \\Psi_p",
    tags: ["Zellbiologie", "Membran", "Wasserpotenzial", "Plasmolyse"],
  },

  // ==========================================
  // MATHEMATIK (4 Labore)
  // ==========================================
  {
    id: "tangent",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "微积分与导数切线",
    themenDE: "Differentialrechnung & Ableitung",
    themenZH: "割线斜率极限逼近与瞬间导数",
    stufe: "EF",
    titleDE: "Differential- & Tangenten-Simulator",
    titleZH: "导数切线极限逼近沙盒",
    descDE: "Sekantensteigung Δy/Δx im Grenzübergang h → 0 zur Tangentensteigung f'(x).",
    descZH: "割线斜率在 Δx→0 极限逼近瞬间切线斜率 f'(x) 的几何微分直观。",
    formula: "f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}",
    tags: ["Analysis", "Ableitung", "Grenzwert", "Tangente"],
  },
  {
    id: "vector",
    fach: "Mathe",
    kategorieDE: "Vektorrechnung & Geometrie",
    kategorieZH: "空间向量与几何加法",
    themenDE: "Analytische Geometrie & Vektoren",
    themenZH: "二维/三维向量加法与点积正交",
    stufe: "EF",
    titleDE: "Vektor-Addition & Kräfte-Parallelogramm",
    titleZH: "二维向量加法与力学平行四边形",
    descDE: "Vektorkomponenten in 2D, Resultierende c = a + b, Betrag und Skalarprodukt.",
    descZH: "二维向量直角坐标分量、平行四边形定则合向量 c = a + b 与向量点积。",
    formula: "\\vec{c} = \\vec{a} + \\vec{b}",
    tags: ["Lineare Algebra", "Vektoren", "Kräfte", "Geometrie"],
  },
  {
    id: "box",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "极值问题与约束条件优化",
    themenDE: "Extremwertprobleme mit Nebenbedingungen",
    themenZH: "纸盒容积优化与驻点二阶导数判别",
    stufe: "EF",
    titleDE: "Box-Optimizer (Extremwert-Probleme)",
    titleZH: "长方体容积极值优化沙盒",
    descDE: "Eckenausschnitt x optimieren für maximales Volumen V(x) mit erster und zweiter Ableitung.",
    descZH: "角部切块 x 动态优化最大容积 V(x)，一阶导数为零与二阶导数判别极值。",
    formula: "V'(x) = 0 \\quad V''(x) < 0",
    tags: ["Analysis", "Extremwert", "Optimierung", "Volumen"],
  },
  {
    id: "probability",
    fach: "Mathe",
    kategorieDE: "Stochastik & Wahrscheinlichkeit",
    kategorieZH: "概率论与大数定律",
    themenDE: "Binomial- & Normalverteilung",
    themenZH: "高尔顿板下落二项分布拟合",
    stufe: "EF",
    titleDE: "Galton-Brett & Normalverteilung (Labor)",
    titleZH: "高尔顿板与正态分布实验室",
    descDE: "Nagelschichten, Kugelzahl, Binomial-Histogramm, Normal-Anpassung und Gesetz der großen Zahlen.",
    descZH: "钉层球数调控、二项直方图、正态拟合曲线与大数定律收敛。",
    formula: "P(k) = \\binom{n}{k} p^k (1-p)^{n-k}",
    tags: ["Stochastik", "Verteilung", "Labor"],
  },

  // ==========================================
  // SOWI / WIRTSCHAFT (5 Labore)
  // ==========================================
  {
    id: "markt",
    fach: "SoWi",
    kategorieDE: "Marktmechanismus & Wohlfahrtsökonomie",
    kategorieZH: "市场机制与福利经济学",
    themenDE: "Preisbildung, Intervention & Wohlfahrt",
    themenZH: "供求均衡、价格管制与福利几何",
    stufe: "EF",
    titleDE: "Markt-Mechanismus & Wohlfahrts-Simulator",
    titleZH: "供求曲线、价格机制与福利经济学沙盘",
    descDE: "Angebot und Nachfrage, Marktpreisbildung, Mindest-/Höchstpreise, Konsumenten-/Produzentenrente und Deadweight Loss (DWL).",
    descZH: "供求曲线平移、市场出清均衡价 P*、价格干预（最低/最高限价）与福利几何剖析（CS、PS 与无谓损失 DWL）。",
    formula: "Q_S(P) = Q_D(P) \\quad \\text{bzw.} \\quad \\text{DWL} = \\frac{1}{2} (P - P_{\\text{Anbieter}}) \\cdot (Q^* - Q_{\\text{trans}})",
    tags: ["SoWi", "Wirtschaft", "Markt", "Preis", "Wohlfahrt", "DWL", "Mindestpreis"],
  },
  {
    id: "orderbuch",
    fach: "SoWi",
    kategorieDE: "Finanzmärkte & Handel",
    kategorieZH: "金融市场与订单簿撮合",
    themenDE: "Börsenhandel & Preisfindung",
    themenZH: "Xetra 连续双向拍卖与滑点",
    stufe: "Q1",
    titleDE: "OrderbuchSimulator: Xetra-Matching (Labor)",
    titleZH: "证券交易所限价订单簿与深度撮合实验室",
    descDE: "Xetra-Orderbuch-Matching, Geld/Brief-Spanne (Spread), Ausführungsrisiko, Slippage und Stop-Loss-Orders.",
    descZH: "实时多档买卖深度撮合、买卖价差 Spread、市价单执行滑点损失与止损委托触发仿真。",
    formula: "\\text{Spread} = P_{\\text{Brief}} - P_{\\text{Geld}}",
    tags: ["SoWi", "Börse", "Orderbuch", "Slippage", "Labor"],
  },
  {
    id: "gini",
    fach: "SoWi",
    kategorieDE: "Sozialstruktur & Ungleichheit",
    kategorieZH: "社会结构与财富分配",
    themenDE: "Einkommens- und Vermögensverteilung",
    themenZH: "洛伦茨曲线积分与基尼系数",
    stufe: "EF",
    titleDE: "Gini-Koeffizient & Lorenz-Kurve",
    titleZH: "基尼系数与洛伦茨收入分配沙盒",
    descDE: "Einkommens- und Vermögensverteilung, Lorenz-Kurve und Ungleichheitsmaße.",
    descZH: "5大阶层财富分配调节、洛伦茨曲线积分与社会不平等基尼系数判定。",
    formula: "G = \\frac{A}{A + B}",
    tags: ["Soziologie", "Verteilung", "Gini", "Ungleichheit"],
  },
  {
    id: "magisches-viereck",
    fach: "SoWi",
    kategorieDE: "Makroökonomie & Wirtschaftspolitik",
    kategorieZH: "宏观调控与经济稳定",
    themenDE: "Stabilitätsgesetz 1967 & Konjunktur",
    themenZH: "经济四大目标冲突与宏观博弈",
    stufe: "Q1",
    titleDE: "Magisches Viereck (§ 1 StabG 1967)",
    titleZH: "宏观经济魔术四角形博弈沙盘",
    descDE: "Stabilitätsgesetz 1967: Wirtschaftswachstum, Vollbeschäftigung, Preisstabilität und Außenbeitrag im Zielkonflikt.",
    descZH: "增长、充分就业、物价稳定与对外经济平衡四大目标冲突，菲利普斯曲线与货币财政调控沙盘。",
    formula: "Y = C + I + G + (X - M) \\quad \\text{Zielkonflikt: } \\text{ALQ} \\leftrightarrow \\text{Inflation}",
    tags: ["Wirtschaft", "SoWi", "Konjunktur", "Stabilitätsgesetz", "EZB", "Fiskalpolitik", "Labor"],
  },
  {
    id: "trust-game",
    fach: "SoWi",
    kategorieDE: "Spieltheorie & Verhaltensökonomie",
    kategorieZH: "博弈论与合作演化",
    themenDE: "Gefangenendilemma & Vertrauen",
    themenZH: "以牙还牙策略与制度信任演化",
    stufe: "EF",
    titleDE: "TrustGameSim: Vertrauensspiel & Evolution (Labor)",
    titleZH: "信任博弈演化与纳什均衡仿真沙盘",
    descDE: "Evolutionäre Spieltheorie: Tit-for-Tat, Trittbrettfahrer, Sanktionskosten und Vertrauensindex im Agenten-Netzwerk.",
    descZH: "演化博弈论：以牙还牙（Tit-for-Tat）、搭便车背叛者、法律制裁成本与多智能体社会信任指数动态推演。",
    formula: "\\text{Payoff: } T > R > P > S \\quad (2R > T + S)",
    tags: ["SoWi", "Spieltheorie", "Vertrauen", "Tit-for-Tat", "Labor"],
  },

  // ==========================================
  // PHILOSOPHIE (3 Labore)
  // ==========================================
  {
    id: "balance",
    fach: "Philosophie",
    kategorieDE: "Dialektische Urteilsbildung",
    kategorieZH: "辩证裁决与论证结构",
    themenDE: "Sachurteil vs. Werturteil",
    themenZH: "事实依据与价值准则双轨平衡",
    stufe: "EF",
    titleDE: "Dialektische Urteils-Waage",
    titleZH: "辩证事实裁决与伦理价值天平",
    descDE: "Sachurteil vs. Werturteil: Abwägen von Pro- und Contra-Argumenten nach Kant & Utilitarismus.",
    descZH: "事实裁决（有效性）与价值裁决（合法性/伦理尊严）多维论据配重与定论推导。",
    formula: "\\text{Urteil} = f(\\text{Sachkriterien}, \\text{Wertkriterien})",
    tags: ["Ethik", "Philosophie", "Urteilsbildung", "Klausur"],
  },
  {
    id: "ethik-waage",
    fach: "Philosophie",
    kategorieDE: "Normative Ethik & Dilemma",
    kategorieZH: "规范伦理与两难决策",
    themenDE: "Kantische Deontologie vs. Utilitarismus",
    themenZH: "定言命令四步检验法与快乐算盘",
    stufe: "EF",
    titleDE: "Ethik-Waage und Dilemma-Entscheidung",
    titleZH: "伦理道德天平与双轨决策工坊",
    descDE: "Utilitarismus vs. Kantische Deontologie: Hedonistisches Kalkuel, Maximenpruefung und Antinomien.",
    descZH: "边沁快乐量度法定量净效用 vs 康德定言命令四步检验法（普遍法则与目的自身公式）。",
    formula: "\\Delta U = \\sum (F - L) \\quad \\text{vs.} \\quad \\text{Maximenpruefung}",
    tags: ["Ethik", "Philosophie", "Kant", "Utilitarismus", "Dilemma", "Labor"],
  },
  {
    id: "dilemma-theatre",
    fach: "Philosophie",
    kategorieDE: "Normative Ethik & Dilemma",
    kategorieZH: "道德两难剧场与情境抉择",
    themenDE: "Trolley-Dilemma & Autonomie",
    themenZH: "电车难题、器官分配与善意谎言",
    stufe: "Q1",
    titleDE: "DilemmaTheatre: 4-Akt-Ethikbühne (Labor)",
    titleZH: "通用伦理两难剧场与四幕沉浸抉择台",
    descDE: "Interaktives 4-Akt-Dilemma-Theater: Trolley-Problem, Organtransplantation und Wahrhaftigkeitspflicht mit Klausur-Urteilskarte.",
    descZH: "四幕沉浸式伦理剧场：电车转向、ICU 稀缺器官分配与绝对说真话义务，附带高考满分评价模板与答题卡。",
    formula: "\\text{Kategorischer Imperativ: Handle nur nach derjenigen Maxime...}",
    tags: ["Philosophie", "DilemmaTheatre", "Trolley", "Ethik", "Labor"],
  },

  // ==========================================
  // DEUTSCH / GEWI (1 Labor)
  // ==========================================
  {
    id: "gewi-reading",
    fach: "Deutsch",
    kategorieDE: "Textanalyse & Hermeneutik",
    kategorieZH: "文学戏剧解剖与原典精读",
    themenDE: "Dramen- & Sachtextanalyse",
    themenZH: "歌德《浮士德》与学术原典解剖",
    stufe: "EF",
    titleDE: "GeWiReadingLab: Sechsdimensionale Textlupe (Labor)",
    titleZH: "文科学术原典精读与六维戏剧解剖工坊",
    descDE: "Tufte-inspirierte Textlupe für Goethes Faust, Kants Anthropologie und Borchert: Versanalyse, Metrik, Leitbegriffe und Klausur-Satzbau.",
    descZH: "北威州高中会考经典选段精读：浮士德之夜独白、康德启蒙宣言与博尔歇特废墟文学，逐行诗韵、修辞格与学术论证装配。",
    formula: "\\text{Textdeutung} = \\text{Hypothese} + \\text{Belegkette} + \\text{Funktion}",
    tags: ["Deutsch", "GeWiReadingLab", "Faust", "Textanalyse", "Hermeneutik", "Labor"],
  },

  // ==========================================
  // CHEMIE EXPANSION (+6 Labore, Gesamt: 15)
  // ==========================================
  {
    id: "chemie-galvanische-zelle",
    fach: "Chemie",
    kategorieDE: "Elektrochemie & Energetik",
    kategorieZH: "电化学与化学能转化",
    themenDE: "Galvanische Elemente & Nernst-Gleichung",
    themenZH: "丹尼尔原电池与能斯特方程",
    stufe: "Q1",
    titleDE: "Galvanische Zelle & Nernst-Gleichung (Labor)",
    titleZH: "丹尼尔原电池电动势与能斯特方程实验室",
    descDE: "Daniell-Element (Zn/Cu), Konzentrationsabhängigkeit der Zellspannung, Salzbrücke und Nernst-Kurve.",
    descZH: "锌铜原电池双半反应微观电子流动、盐桥平衡、离子浓度调控对电动势的定量影响与能斯特方程对数关系。",
    formula: "E = E^\\circ + \\frac{0{,}059}{z} \\log\\frac{[\\text{Ox}]}{[\\text{Red}]}",
    tags: ["Elektrochemie", "Nernst", "Daniell", "Redox", "Labor"],
  },
  {
    id: "chemie-elektrolyse",
    fach: "Chemie",
    kategorieDE: "Elektrochemie & Energetik",
    kategorieZH: "电化学与化学能转化",
    themenDE: "Elektrolyse & Faradaysche Gesetze",
    themenZH: "电解池电解电压与法拉第定量电解",
    stufe: "Q1",
    titleDE: "Elektrolyse & Faradaysche Gesetze (Labor)",
    titleZH: "电解池与法拉第电沉积定量实验室",
    descDE: "Zersetzungsspannung, Überspannung, quantitative Stoffabscheidung an Anode und Kathode nach Faraday.",
    descZH: "分解电压门槛、阳极氧化阴极还原、电流大小与通电时间对金属沉积量的法拉第定量定律验证。",
    formula: "m = \\frac{M \\cdot I \\cdot t}{z \\cdot F}",
    tags: ["Elektrochemie", "Elektrolyse", "Faraday", "Redox", "Labor"],
  },
  {
    id: "chemie-puffer-hasselbalch",
    fach: "Chemie",
    kategorieDE: "Säure-Base & Analytik",
    kategorieZH: "酸碱理论与滴定分析",
    themenDE: "Puffersysteme & Pufferkapazität",
    themenZH: "缓冲溶液与亨德森-哈塞尔巴赫方程",
    stufe: "Q1",
    titleDE: "Puffersysteme & Henderson-Hasselbalch (Labor)",
    titleZH: "醋酸-醋酸盐缓冲溶液与抗酸碱平衡实验室",
    descDE: "Essigsäure/Acetat-Puffer, pH-Stabilisierung bei Zugabe starker Säuren/Basen und Pufferbereich um den pKs.",
    descZH: "共轭酸碱对共存体系、外加强酸强碱时的 pH 缓冲阻尼、最大缓冲容量窗口与亨德森-哈塞尔巴赫方程计算。",
    formula: "\\text{pH} = \\text{p}K_s + \\log\\frac{[A^-]}{[HA]}",
    tags: ["Säure", "Base", "Puffer", "Hasselbalch", "pH", "Labor"],
  },
  {
    id: "chemie-sn1-sn2",
    fach: "Chemie",
    kategorieDE: "Organische Reaktionsmechanismen",
    kategorieZH: "有机化学机理与立体化学",
    themenDE: "Nukleophile Substitution: SN1 vs. SN2",
    themenZH: "亲核取代机理：单分子与双分子机理",
    stufe: "Q1",
    titleDE: "Reaktionsmechanismen SN1 vs SN2 (Labor)",
    titleZH: "亲核取代反应 SN1 与 SN2 机理立体工坊",
    descDE: "Carbeniumionen-Stabilität vs. sterische Hinderung, Walden-Umkehr, Geschwindigkeitsgesetze 1. und 2. Ordnung.",
    descZH: "空间位阻与碳正离子稳定性抉择、瓦尔登转化立体翻转、动力学一级/二级速率方程与溶剂极性影响。",
    formula: "v_{\\text{SN2}} = k[\\text{RX}][\\text{Nu}^-] \\quad v_{\\text{SN1}} = k[\\text{RX}]",
    tags: ["Organik", "SN1", "SN2", "Mechanismus", "Substitution", "Labor"],
  },
  {
    id: "chemie-polymerisation",
    fach: "Chemie",
    kategorieDE: "Angewandte Chemie & Kunststoffe",
    kategorieZH: "应用化学与合成高分子材料",
    themenDE: "Radikalische Polymerisation & Polykondensation",
    themenZH: "自由基聚合、缩聚反应与塑料结构特性",
    stufe: "Q2",
    titleDE: "Makromoleküle: Polymerisation & Kunststoffe (Labor)",
    titleZH: "高分子合成机理与塑料交联三态沙盘",
    descDE: "Kettenwachstum (Start, Wachstum, Abbruch), Vernetzungsgrad: Thermoplaste, Duroplaste und Elastomere im Festigkeitstest.",
    descZH: "自由基链反应三部曲、单体聚合度控制、线型与网状交联度对热塑性/热固性/弹性体宏观力学性能的决定作用。",
    formula: "n \\, \\text{Monomer} \\rightarrow [-\\text{Monomer}-]_n",
    tags: ["Organik", "Polymere", "Kunststoffe", "Kinetik", "Labor"],
  },
  {
    id: "chemie-komplexchemie",
    fach: "Chemie",
    kategorieDE: "Gleichgewicht & Kinetik",
    kategorieZH: "化学平衡与络合物动力学",
    themenDE: "Komplexchemie & Ligandenaustausch",
    themenZH: "过渡金属配位反应与配体竞争平衡",
    stufe: "Q2",
    titleDE: "Komplexchemie & Ligandenaustausch (Labor)",
    titleZH: "铜氨配合物合成与配体置换平衡实验室",
    descDE: "Hexaaqua- vs. Tetraamminkupfer(II), Farbvertiefung, schrittweise Komplexbildung und Stabilitätskonstanten.",
    descZH: "水合铜离子与氨水配合配体置换反应、特征天蓝色到深蓝紫显色跃迁、配位平衡常数与晶体场吸收光谱。",
    formula: "K_B = \\frac{[\\text{Cu}(\\text{NH}_3)_4^{2+}]}{[\\text{Cu}^{2+}][\\text{NH}_3]^4}",
    tags: ["Komplexe", "Gleichgewicht", "Farbe", "Kupfer", "Labor"],
  },

  // ==========================================
  // BIOLOGIE EXPANSION (+9 Labore, Gesamt: 12)
  // ==========================================
  {
    id: "bio-fotosynthese",
    fach: "Bio",
    kategorieDE: "Stoffwechselphysiologie",
    kategorieZH: "物质代谢生理学",
    themenDE: "Licht- und Dunkelreaktion der Fotosynthese",
    themenZH: "光合作用光反应同化力与卡尔文循环",
    stufe: "EF",
    titleDE: "Fotosynthese: Licht- und Dunkelreaktion (Labor)",
    titleZH: "光合作用光反应与卡尔文暗反应实验室",
    descDE: "Thylakoid-Membran, Lichtintensität, CO2-Konzentration, Engelmann-Experiment und Netto-Fotosyntheserate.",
    descZH: "类囊体光反应生成 ATP/NADPH、暗反应固定 CO2、光饱和点与补偿点、环境限制因子定律（李比希法则）仿真。",
    formula: "6\\text{CO}_2 + 6\\text{H}_2\\text{O} \\xrightarrow{h\\nu} \\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2",
    tags: ["Fotosynthese", "Stoffwechsel", "Licht", "Calvin", "Labor"],
  },
  {
    id: "bio-zellatmung",
    fach: "Bio",
    kategorieDE: "Stoffwechselphysiologie",
    kategorieZH: "物质代谢生理学",
    themenDE: "Zellatmung & Chemiosmose",
    themenZH: "有氧呼吸三阶段与线粒体氧化磷酸化",
    stufe: "EF",
    titleDE: "Zellatmung & Chemiosmotische ATP-Synthese (Labor)",
    titleZH: "细胞呼吸动力学与线粒体 ATP 合成实验室",
    descDE: "Glykolyse, Citratzyklus und Atmungskette: Protonengradient über der inneren Mitochondrienmembran und ATP-Ausbeute.",
    descZH: "葡萄糖降解三阶段、电子传递链产生的跨膜质子电化学势梯度、ATP 合酶旋转催化与化学渗透假说仿真。",
    formula: "\\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2 \\rightarrow 6\\text{CO}_2 + 6\\text{H}_2\\text{O} + 32\\text{ATP}",
    tags: ["Zellatmung", "Mitochondrium", "ATP", "Stoffwechsel", "Labor"],
  },
  {
    id: "bio-enzymkinetik",
    fach: "Bio",
    kategorieDE: "Stoffwechselphysiologie",
    kategorieZH: "酶催化与代谢调控",
    themenDE: "Enzymkinetik & Hemmungsmechanismen",
    themenZH: "米氏动力学、温度pH敏感性与竞争性抑制",
    stufe: "EF",
    titleDE: "Enzymkinetik & Michaelis-Menten-Modell (Labor)",
    titleZH: "酶促反应动力学与米氏常数实验室",
    descDE: "Substratsättigung, Wechselzahl, Km-Wert sowie kompetitive vs. allosterische Hemmung im Lineweaver-Burk-Diagramm.",
    descZH: "底物浓度与反应速率饱和双曲线、米氏常数 Km 物理意义、竞争性与非竞争性抑制剂对 Vmax 和 Km 的双重影响。",
    formula: "v = \\frac{v_{\\max} [S]}{K_m + [S]}",
    tags: ["Enzyme", "Kinetik", "MichaelisMenten", "Hemmung", "Labor"],
  },
  {
    id: "bio-genetik-kreuzung",
    fach: "Bio",
    kategorieDE: "Klassische & Molekulare Genetik",
    kategorieZH: "经典遗传与孟德尔分离定律",
    themenDE: "Mendelsche Regeln & Dihybrider Erbgang",
    themenZH: "孟德尔自由组合定律与双对相对性状杂交",
    stufe: "EF",
    titleDE: "Mendelsche Genetik & Dihybrider Erbgang (Labor)",
    titleZH: "孟德尔双杂合遗传与重组分离定律实验室",
    descDE: "Punnett-Quadrat für 2 Merkmale (Samenform/Farbe), 9:3:3:1 Phänotypen-Spaltung und statistische Rekombination.",
    descZH: "豌豆粒色与粒形双杂合子测交与自交棋盘方格、9:3:3:1 表型分离比与基因连锁重组假说。",
    formula: "9 : 3 : 3 : 1 \\quad (F_2\\text{-Phänotypenspaltung})",
    tags: ["Genetik", "Mendel", "Kreuzung", "Phänotyp", "Labor"],
  },
  {
    id: "bio-synapse",
    fach: "Bio",
    kategorieDE: "Neurobiologie & Erregungsleitung",
    kategorieZH: "神经生物学与突触传导",
    themenDE: "Chemische Synapse & Neurotransmitter",
    themenZH: "化学突触传递机制与神经毒素阻断",
    stufe: "Q1",
    titleDE: "Chemische Synapse & Neurotoxine (Labor)",
    titleZH: "化学突触传递与神经毒素受体阻断实验室",
    descDE: "Ca²⁺-Einstrom, Vesikelverschmelzung, Acetylcholin-Freisetzung, EPSP/IPSP und Wirkung von Giften (Curare, Sarin).",
    descZH: "动作电位触发电压门控钙通道开放、乙酰胆碱囊泡释放与受体结合、乙酰胆碱酯酶水解及箭毒/沙林毒气阻断机制。",
    formula: "\\Delta U_{\\text{EPSP}} \\propto [\\text{ACh}] \\cdot [\\text{Rezeptor}]",
    tags: ["Neurobiologie", "Synapse", "Transmitter", "Toxine", "Labor"],
  },
  {
    id: "bio-oekologie-raeuber-beute",
    fach: "Bio",
    kategorieDE: "Ökologie & Populationsdynamik",
    kategorieZH: "生态学与种群动态演化",
    themenDE: "Lotka-Volterra-Regeln & Populationsdynamik",
    themenZH: "洛特卡-沃尔泰拉捕食者-猎物波动模型",
    stufe: "Q1",
    titleDE: "Lotka-Volterra Räuber-Beute-Dynamik (Labor)",
    titleZH: "洛特卡-沃尔泰拉捕食者-猎物生态动力学实验室",
    descDE: "Die 3 Lotka-Volterra-Regeln: Phasenverschobene Oszillation, Konstanz der Mittelwerte und Störung der Gleichgewichte.",
    descZH: "种群波动周期性相位延迟、长期平均个体数量常数定律、外力无差别干扰后猎物优先恢复规律与相空间轨迹。",
    formula: "\\frac{dN_1}{dt} = r_1 N_1 - a N_1 N_2 \\quad \\frac{dN_2}{dt} = -d_2 N_2 + b N_1 N_2",
    tags: ["Ökologie", "Populationsdynamik", "LotkaVolterra", "RäuberBeute", "Labor"],
  },
  {
    id: "bio-dna-pcr",
    fach: "Bio",
    kategorieDE: "Klassische & Molekulare Genetik",
    kategorieZH: "分子生物学与基因工程技术",
    themenDE: "PCR (Polymerase-Kettenreaktion) & Elektrophorese",
    themenZH: "体外 PCR 扩增循环与凝胶电泳分离分析",
    stufe: "Q1",
    titleDE: "PCR-Thermostufen & DNA-Gelelektrophorese (Labor)",
    titleZH: "PCR 基因体外扩增与琼脂糖凝胶电泳实验室",
    descDE: "Temperaturzyklen (Denaturierung 95°C, Annealing 55°C, Elongation 72°C), Taq-Polymerase und Bandenwanderung im Gel.",
    descZH: "三步温度循环微观退火与延伸、引物特异性结合、DNA 片段指数级扩增与电泳凝胶根据分子量大小分级染色辨析。",
    formula: "N(n) = N_0 \\cdot 2^n \\quad (n = \\text{PCR-Zyklen})",
    tags: ["Genetik", "PCR", "Elektrophorese", "Biotechnologie", "Labor"],
  },
  {
    id: "bio-epigenetik",
    fach: "Bio",
    kategorieDE: "Klassische & Molekulare Genetik",
    kategorieZH: "表观遗传与基因表达调控",
    themenDE: "DNA-Methylierung & Histonacetylierung",
    themenZH: "DNA 胞嘧啶甲基化与组蛋白乙酰化修饰",
    stufe: "Q2",
    titleDE: "Epigenetik: Methylierung & Genexpression (Labor)",
    titleZH: "表观遗传调控与染色质转录活性实验室",
    descDE: "CpG-Inseln, Methyltransferasen, Chromatin-Kondensation (Hetero- vs. Euchromatin) und umweltinduzierte Gen-Stummschaltung.",
    descZH: "启动子区 CpG 岛甲基化对转录因子的位阻封锁、组蛋白修饰松散染色质、环境因素诱发基因可逆沉默与跨代传递。",
    formula: "\\text{Transkriptionsrate} \\propto \\frac{[\\text{Acetylierung}]}{1 + [\\text{Methylierung}]}",
    tags: ["Genetik", "Epigenetik", "Methylierung", "Chromatin", "Labor"],
  },
  {
    id: "bio-oekologie-see",
    fach: "Bio",
    kategorieDE: "Ökologie & Populationsdynamik",
    kategorieZH: "生态学与水域生态危机",
    themenDE: "Ökosystem See & Eutrophierung",
    themenZH: "湖泊热分层循环与富营养化崩溃过程",
    stufe: "Q2",
    titleDE: "Ökosystem See: Schichtung & Eutrophierung (Labor)",
    titleZH: "湖泊生态系统热分层与富营养化演变沙盘",
    descDE: "Epilimnion, Metalimnion, Hypolimnion, Phosphatüberdüngung, Algenblüte und Sauerstoffzehrung im Tiefenwasser.",
    descZH: "四季水体热分层与氧气浓度垂直剖面、磷酸盐过量输入导致蓝藻爆发、沉底腐败菌耗氧与湖泊泛池缺氧崩溃机制。",
    formula: "[\\text{PO}_4^{3-}] \\uparrow \\; \\Rightarrow \\; \\text{Biomasse} \\uparrow \\; \\Rightarrow \\; [\\text{O}_2]_{\\text{Boden}} \\rightarrow 0",
    tags: ["Ökologie", "See", "Eutrophierung", "Phosphat", "Labor"],
  },

  // ==========================================
  // MATHEMATIK EXPANSION (+9 Labore, Gesamt: 13)
  // ==========================================
  {
    id: "mathe-integral-flaeche",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "微积分与导数积分",
    themenDE: "Integralrechnung & Flächeninhalte",
    themenZH: "微积分基本定理与定积分几何面积",
    stufe: "Q1",
    titleDE: "Integralrechnung: Flächenbilanz & Hauptsatz (Labor)",
    titleZH: "微积分基本定理与定积分面积计算实验室",
    descDE: "Riemannsche Ober- und Untersummen, orientierter Flächeninhalt, Nullstellenschnitt und Stammfunktionen F(x).",
    descZH: "黎曼分割矩形微元极限逼近、连续函数正负净面积与绝对几何面积积分、牛顿-莱布尼茨公式几何验证。",
    formula: "\\int_a^b f(x) \\, dx = F(b) - F(a)",
    tags: ["Analysis", "Integral", "Hauptsatz", "Riemann", "Labor"],
  },
  {
    id: "mathe-kurvendiskussion",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "微积分与导数积分",
    themenDE: "Kurvendiskussion & Ableitungsgraphen",
    themenZH: "高次多项式导数特征与拐点切线判别",
    stufe: "EF",
    titleDE: "Kurvendiskussion & Wendetangenten (Labor)",
    titleZH: "函数全貌剖析：极值点与拐点切线工坊",
    descDE: "Nullstellen, Hoch-/Tiefpunkte (f'=0, f''≠0), Wendepunkte (f''=0, f'''≠0) und graphische Zusammenhänge f, f', f''.",
    descZH: "原函数与一阶、二阶导数函数图像三线联动、极值点驻点切线斜率与拐点最大变曲率判定。",
    formula: "f'(x_E) = 0, \\, f''(x_E) \\neq 0 \\quad f''(x_W) = 0, \\, f'''(x_W) \\neq 0",
    tags: ["Analysis", "Kurvendiskussion", "Ableitung", "Extremum", "Labor"],
  },
  {
    id: "mathe-funktionenscharen",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "微积分与导数积分",
    themenDE: "Funktionenscharen & Ortskurven",
    themenZH: "含参函数族与极值点几何轨迹曲线",
    stufe: "Q1",
    titleDE: "Funktionenscharen & Ortskurven (Labor)",
    titleZH: "含参函数族与极值点轨迹曲线实验室",
    descDE: "Kurvenschar fa(x) mit Scharparameter a, gemeinsame Punkte aller Scharkurven und Elimination des Parameters für die Ortskurve.",
    descZH: "单参数函数族动态滑条展开、公共定点寻找、极大值点坐标参数消元法求极值点轨迹曲线方程。",
    formula: "x = x(a), \\, y = y(a) \\;\\Rightarrow\\; a = g(x) \\;\\Rightarrow\\; y = y(g(x))",
    tags: ["Analysis", "Funktionenscharen", "Ortskurve", "Parameter", "Labor"],
  },
  {
    id: "mathe-rotationskoerper",
    fach: "Mathe",
    kategorieDE: "Analysis & Extremwertoptimierung",
    kategorieZH: "微积分与空间体积几何",
    themenDE: "Rotationskörper & Volumenintegrale",
    themenZH: "平面曲线绕轴旋转体积积分",
    stufe: "Q2",
    titleDE: "Rotationskörper & Volumenintegrale (Labor)",
    titleZH: "旋转体体积积分与三维立体切片沙盘",
    descDE: "Rotation einer Kurve um die x-Achse, Zylinderscheiben-Methode, Mantelflächen und exakte Volumenberechnung.",
    descZH: "平面曲线绕 x 轴旋转生成三维几何体、微元圆盘切片累加求和与定积分体积封闭精确解析。",
    formula: "V = \\pi \\int_a^b [f(x)]^2 \\, dx",
    tags: ["Analysis", "Integral", "Rotation", "Volumen", "Labor"],
  },
  {
    id: "mathe-ebene-abstand",
    fach: "Mathe",
    kategorieDE: "Vektorrechnung & Geometrie",
    kategorieZH: "空间解析几何与向量代数",
    themenDE: "Ebenen im Raum & Hessesche Normalenform",
    themenZH: "空间平面方程转换与点面垂直距离",
    stufe: "Q1",
    titleDE: "Ebenen & Hessesche Normalenform (Labor)",
    titleZH: "空间平面方程与点面距离判定实验室",
    descDE: "Parameterform, Normalenform und Koordinatenform einer Ebene, Normaleneinheitsvektor n0 und Hesse-Abstandsberechnung.",
    descZH: "空间平面三点式到法向量式的叉乘转换、黑塞标准法线方程构建与空间任意一点到平面的最短垂线投影距离。",
    formula: "d = \\frac{|\\vec{n} \\cdot \\vec{p} - c|}{|\\vec{n}|}",
    tags: ["Geometrie", "Vektoren", "Ebene", "Hesse", "Abstand", "Labor"],
  },
  {
    id: "mathe-vektor-skalar-kreuz",
    fach: "Mathe",
    kategorieDE: "Vektorrechnung & Geometrie",
    kategorieZH: "空间解析几何与向量代数",
    themenDE: "Skalarprodukt & Kreuzprodukt",
    themenZH: "点积正交性、投影与叉积正交向量与面积",
    stufe: "EF",
    titleDE: "Skalarprodukt & Kreuzprodukt in 3D (Labor)",
    titleZH: "三维向量点积正交与叉积法向量实验室",
    descDE: "Winkelberechnung zweier Vektoren, Orthogonalitätskriterium (a·b = 0) und Flächeninhalt des Parallelogramms (|a × b|).",
    descZH: "空间两向量夹角余弦公式、正交判据、三维右手系外积向量正交性与构成的空间平行四边形几何面积。",
    formula: "\\cos\\alpha = \\frac{\\vec{a}\\cdot\\vec{b}}{|\\vec{a}||\\vec{b}|} \\quad A = |\\vec{a} \\times \\vec{b}|",
    tags: ["Geometrie", "Vektoren", "Skalarprodukt", "Kreuzprodukt", "Labor"],
  },
  {
    id: "mathe-markov-ketten",
    fach: "Mathe",
    kategorieDE: "Stochastik & Wahrscheinlichkeit",
    kategorieZH: "概率统计与随机过程",
    themenDE: "Markow-Ketten & Stochastische Matrizen",
    themenZH: "马尔可夫链状态转移与稳态收敛分布",
    stufe: "Q2",
    titleDE: "Stochastische Prozesse & Markow-Ketten (Labor)",
    titleZH: "马尔可夫链与稳态概率极限分布沙盒",
    descDE: "Zustandsübergangsgraph, Übergangsmatrix M, Potenzen M^k und Konvergenz gegen den stationären Fixvektor.",
    descZH: "状态转移图、行和或列和为 1 的随机矩阵高次幂迭代、大步数后对初始状态的遗忘性与平衡固定向量计算。",
    formula: "\\vec{v}_{k} = M^k \\cdot \\vec{v}_0 \\quad M \\vec{v}^* = \\vec{v}^*",
    tags: ["Stochastik", "Matrizen", "Markov", "Wahrscheinlichkeit", "Labor"],
  },
  {
    id: "mathe-hypothesentest",
    fach: "Mathe",
    kategorieDE: "Stochastik & Wahrscheinlichkeit",
    kategorieZH: "概率统计与随机过程",
    themenDE: "Statistische Tests: Fehler 1. und 2. Art",
    themenZH: "二项分布假设检验与显著性水平决策",
    stufe: "Q2",
    titleDE: "Signifikanztest: Ein- & zweiseitiger Hypothesentest (Labor)",
    titleZH: "假设检验：第一类错误与显著性水平决策工坊",
    descDE: "Nullhypothese H0, Signifikanzniveau α (5%, 1%), kritischer Bereich, α-Fehler und kumulierte Binomialverteilung.",
    descZH: "原假设设定、单侧与双侧拒绝域临界点计算、第一类错误（弃真）概率控制与第二类错误（取伪）权衡分析。",
    formula: "P(X \\in K \\mid H_0) \\le \\alpha",
    tags: ["Stochastik", "Hypothesentest", "Signifikanz", "AlphaFehler", "Labor"],
  },
  {
    id: "mathe-korrelation-regression",
    fach: "Mathe",
    kategorieDE: "Stochastik & Wahrscheinlichkeit",
    kategorieZH: "概率统计与随机过程",
    themenDE: "Lineare Regression & Korrelationskoeffizient",
    themenZH: "最小二乘法回归直线与皮尔逊相关系数",
    stufe: "EF",
    titleDE: "Lineare Regression & Bestimmtheitsmaß R² (Labor)",
    titleZH: "最小二乘法线性回归与皮尔逊相关系数实验室",
    descDE: "Streudiagramm zweier Merkmale, Residuen-Quadrate minimieren, Pearson-Korrelation r und Bestimmtheitsmaß R².",
    descZH: "散点图样本均值中心、残差平方和极小化求斜率与截距、皮尔逊相关系数 r 与解释方差占比 R² 评估。",
    formula: "y = mx + b \\quad r = \\frac{\\sum (x_i-\\bar{x})(y_i-\\bar{y})}{\\sqrt{\\sum (x_i-\\bar{x})^2 \\sum (y_i-\\bar{y})^2}}",
    tags: ["Stochastik", "Regression", "Korrelation", "Labor"],
  },

  // ==========================================
  // SOWI / WIRTSCHAFT EXPANSION (+7 Labore, Gesamt: 13)
  // ==========================================
  {
    id: "sowi-sinus-milieus",
    fach: "SoWi",
    kategorieDE: "Sozialstruktur & Ungleichheit",
    kategorieZH: "社会分层与价值观念",
    themenDE: "Sinus-Milieus & Soziale Ungleichheit",
    themenZH: "德国西纳斯社会阶层与价值坐标图谱",
    stufe: "EF",
    titleDE: "Sinus-Milieus: Soziale Lage & Grundorientierung (Labor)",
    titleZH: "德国社会西纳斯环境模型与阶层图谱沙盘",
    descDE: "Zweidimensionales Koordinatensystem: Soziale Lage (Unter-/Mittel-/Oberschicht) vs. Grundorientierung (Tradition, Modernisierung, Neuorientierung).",
    descZH: "德国当代社会学经典双维图谱：纵轴经济社会地位与横轴价值取向演变，分析10类典型社群的生活方式与政治倾向。",
    formula: "\\text{Milieu} = f(\\text{Soziale Lage (Y)}, \\text{Grundorientierung (X)})",
    tags: ["SoWi", "Soziologie", "SinusMilieus", "Schichtung", "Labor"],
  },
  {
    id: "sowi-konjunktur-zyklus",
    fach: "SoWi",
    kategorieDE: "Makroökonomie & Wirtschaftspolitik",
    kategorieZH: "宏观经济调控与景气周期",
    themenDE: "Konjunkturphasen & Wirtschaftsindikatoren",
    themenZH: "宏观景气周期波动与经济先行/滞后指标",
    stufe: "Q1",
    titleDE: "Konjunkturphasen & Früh-/Spätindikatoren (Labor)",
    titleZH: "宏观经济景气周期与先行/滞后指标沙盘",
    descDE: "Aufschwung, Boom, Abschwung, Rezession/Depression sowie ifo-Geschäftsklima, Auftragseingang und Arbeitslosenquote.",
    descZH: "实际 GDP 波动偏离潜在产出缺口、各阶段先行/同步/滞后经济指标演变规律与反周期宏观调控时滞效应。",
    formula: "\\text{Produktionslücke} = \\frac{Y_{\\text{real}} - Y_{\\text{pot}}}{Y_{\\text{pot}}} \\times 100\\%",
    tags: ["SoWi", "Wirtschaft", "Konjunktur", "Indikatoren", "Labor"],
  },
  {
    id: "sowi-ezb-geldpolitik",
    fach: "SoWi",
    kategorieDE: "Makroökonomie & Wirtschaftspolitik",
    kategorieZH: "货币金融与中央银行调控",
    themenDE: "EZB-Geldpolitik & Zinstransmission",
    themenZH: "欧洲央行货币政策工具与通胀传导链条",
    stufe: "Q1",
    titleDE: "EZB-Geldpolitik: Zinskanal & Inflationssteuerung (Labor)",
    titleZH: "欧洲央行货币政策与利率传导机制沙盒",
    descDE: "Hauptrefinanzierungssatz, Einlagefazilität, Transmissionskanal auf Geschäftsbankenzinsen, Kreditvolumen und Inflationsziel 2%.",
    descZH: "央行三大基准利率调整、银行间拆借利率与商业贷款利差传导、总需求调节对物价指数 (HICP) 的两阶段调控逻辑。",
    formula: "i_{\\text{Leitzins}} \\uparrow \\; \\Rightarrow \\; I, C \\downarrow \\; \\Rightarrow \\; \\pi_{\\text{Inflation}} \\downarrow",
    tags: ["SoWi", "Wirtschaft", "EZB", "Geldpolitik", "Inflation", "Labor"],
  },
  {
    id: "sowi-sozialstaat-transfer",
    fach: "SoWi",
    kategorieDE: "Sozialstruktur & Ungleichheit",
    kategorieZH: "社会福利与再分配政策",
    themenDE: "Sozialstaatsmodelle: Bismarck vs. Beveridge",
    themenZH: "欧洲福利国家模式与再分配转移支付机制",
    stufe: "EF",
    titleDE: "Sozialstaatliche Sicherungssysteme: Bismarck vs Beveridge (Labor)",
    titleZH: "俾斯麦 vs 贝弗里奇社会保障制度对比沙盘",
    descDE: "Beitragsfinanzierte Äquivalenz (Bismarck) vs. steuerfinanzierte Grundsicherung (Beveridge), Ersatzquote und Lohnnebenkosten.",
    descZH: "德国法定五大社会保险（缴费工资关联制）与英欧税收普惠保底制、劳动力附加成本与财政可持续性权衡计算。",
    formula: "\\text{Ersatzquote} = \\frac{\\text{Netto-Transferleistung}}{\\text{Letztes Nettoeinkommen}} \\times 100\\%",
    tags: ["SoWi", "Sozialstaat", "Bismarck", "Beveridge", "Transfer", "Labor"],
  },
  {
    id: "sowi-trilemma-trilemma",
    fach: "SoWi",
    kategorieDE: "Globalisierung & Internationale Beziehungen",
    kategorieZH: "全球化与国际金融体系",
    themenDE: "Mundell-Fleming-Trilemma der Währungspolitik",
    themenZH: "蒙代尔-弗莱明不可能三角与汇率制度抉择",
    stufe: "Q2",
    titleDE: "Mundell-Fleming-Trilemma der Währungspolitik (Labor)",
    titleZH: "国际金融三元悖论：独立货币/汇率/资本流动",
    descDE: "Das makroökonomische Unmöglichkeits-Dreieck: Fester Wechselkurs, freier Kapitalverkehr und autonome Geldpolitik.",
    descZH: "央行在固定汇率、资本完全自由流动与独立货币政策三者中不可兼得的数学几何博弈模型，欧元区与美元体系实证。",
    formula: "\\text{Trilemma: Wähle genau 2 von 3 Zielen aus}",
    tags: ["SoWi", "Währung", "Trilemma", "MundellFleming", "EZB", "Labor"],
  },
  {
    id: "sowi-globalisierung-trade",
    fach: "SoWi",
    kategorieDE: "Globalisierung & Internationale Beziehungen",
    kategorieZH: "国际贸易与全球化分工",
    themenDE: "Freihandel vs. Protektionismus & Ricardo-Modell",
    themenZH: "李嘉图比较优势理论与跨国贸易自由化",
    stufe: "Q2",
    titleDE: "Komparative Kostenvorteile nach David Ricardo (Labor)",
    titleZH: "李嘉图比较优势与跨国贸易自由化沙盘",
    descDE: "Opportunitätskosten zweier Länder bei 2 Gütern, Spezialisierungsgewinn durch Freihandel und Wohlfahrtseffekte von Importzöllen.",
    descZH: "两国生产两种商品的机会成本矩阵、即便在绝对优势落后下基于比较优势分工带来的全球总产出净增益与关税无谓损失。",
    formula: "\\frac{a_{11}}{a_{21}} < \\frac{a_{12}}{a_{22}} \\; \\Rightarrow \\; \\text{Spezialisierungsvorteil Land 1}",
    tags: ["SoWi", "Globalisierung", "Freihandel", "Ricardo", "Zoll", "Labor"],
  },
  {
    id: "sowi-standort-deutschland",
    fach: "SoWi",
    kategorieDE: "Makroökonomie & Wirtschaftspolitik",
    kategorieZH: "经济区位与全球竞争力",
    themenDE: "Standortfaktoren im internationalen Wettbewerb",
    themenZH: "德国工业区位因素与跨国企业选址博弈",
    stufe: "EF",
    titleDE: "Standortfaktoren & Internationaler Wettbewerb (Labor)",
    titleZH: "国家投资区位因素与国际竞争力沙盒",
    descDE: "Harte vs. weiche Standortfaktoren: Lohnstückkosten, Energiekosten, Steuerbelastung, Infrastruktur, duale Ausbildung.",
    descZH: "硬性与软性区位因素加权记分模型：单位劳动成本、工业电价、企业实际所得税率与高技能人才供给对资本流向的决定。",
    formula: "\\text{Standortgüte} = \\sum_{i=1}^n w_i \\cdot K_i",
    tags: ["SoWi", "Wirtschaft", "Standort", "Wettbewerb", "Industrie", "Labor"],
  },

  // ==========================================
  // PHILOSOPHIE EXPANSION (+7 Labore, Gesamt: 10)
  // ==========================================
  {
    id: "philo-kant-kategorischer",
    fach: "Philosophie",
    kategorieDE: "Normative Ethik & Dilemma",
    kategorieZH: "规范伦理学与康德义务论",
    themenDE: "Kategorischer Imperativ & Maximenprüfung",
    themenZH: "康德绝对命令与普遍性四步检验工坊",
    stufe: "EF",
    titleDE: "Kant: Kategorischer Imperativ & Universalisierung (Labor)",
    titleZH: "康德绝对命令与普遍性四步检验工坊",
    descDE: "Die 4 Schritte der Maximenprüfung: Formulierung, Verallgemeinerung, Widerspruch im Denken und Widerspruch im Wollen.",
    descZH: "行为准则提炼、构想为普遍自然法则、概念逻辑思维自相矛盾检验、理性意志矛盾检验与完全/不完全道德义务划分。",
    formula: "\\text{Handle nur nach der Maxime, durch die du zugleich wollen kannst...}",
    tags: ["Philosophie", "Kant", "Deontologie", "Imperativ", "Ethik", "Labor"],
  },
  {
    id: "philo-hoehlengleichnis",
    fach: "Philosophie",
    kategorieDE: "Erkenntnistheorie & Metaphysik",
    kategorieZH: "认识论与形而上学",
    themenDE: "Platons Höhlengleichnis & Ideenlehre",
    themenZH: "柏拉图洞穴之喻与理念论四级认识阶梯",
    stufe: "EF",
    titleDE: "Platons Höhlengleichnis & Erkenntnisstufen (Labor)",
    titleZH: "柏拉图洞穴之喻与认识论四重阶梯",
    descDE: "Die 4 Erkenntnisstufen: Eikasia (Schattenbilder), Pistis (Gegenstände), Dianoia (Mathematik) und Noesis (Idee des Guten).",
    descZH: "从囚徒阴影虚妄（想象）、火光实物（信念）、走出洞穴仰望星空（理智推导）到直视太阳（善的最高理念直觉）的哲学跃迁仿真。",
    formula: "\\text{Doxa (Sinnenschein)} \\xrightarrow{\\text{Aufstieg}} \\text{Episteme (Wahre Erkenntnis)}",
    tags: ["Philosophie", "Platon", "Erkenntnistheorie", "Höhle", "Ideen", "Labor"],
  },
  {
    id: "philo-staatsvertrag",
    fach: "Philosophie",
    kategorieDE: "Rechts- & Staatsphilosophie",
    kategorieZH: "国家哲学与合法性基础",
    themenDE: "Vertragstheorien: Hobbes, Locke, Rousseau",
    themenZH: "经典契约论思想家自然状态与权力让渡对比",
    stufe: "Q1",
    titleDE: "Vertragstheorien: Hobbes vs Locke vs Rousseau (Labor)",
    titleZH: "社会契约论大辩论：霍布斯/洛克/卢梭",
    descDE: "Naturzustand (Krieg aller gegen alle vs. Naturrechte vs. edler Wilder), Vertragsabschluss und Staatsgewalt (Leviathan vs. Gewaltenteilung vs. Gemeinwille).",
    descZH: "霍布斯利维坦专制保障生命、洛克保护私有财产与权力分立、卢梭直接民主公共意志（volonté générale）的系统对照剖析。",
    formula: "\\text{Naturzustand} \\xrightarrow{\\text{Gesellschaftsvertrag}} \\text{Legitimer Staat}",
    tags: ["Philosophie", "Staat", "Hobbes", "Locke", "Rousseau", "Vertrag", "Labor"],
  },
  {
    id: "philo-rawls-schleier",
    fach: "Philosophie",
    kategorieDE: "Rechts- & Staatsphilosophie",
    kategorieZH: "正义理论与制度伦理",
    themenDE: "John Rawls: Schleier des Nichtwissens & Maximin",
    themenZH: "罗尔斯正义论：无知之幕与最大最小值准则",
    stufe: "Q1",
    titleDE: "John Rawls: Schleier des Nichtwissens & Maximin (Labor)",
    titleZH: "罗尔斯无知之幕与正义两原则沙盘",
    descDE: "Urzustand (Original Position), Schleier des Nichtwissens (Veil of Ignorance), Maximin-Regel und das Differenzprinzip.",
    descZH: "在不知晓自己出生阶级、天赋才能或健康状态的前提下设计社会分配规则，最大化处于社会最不利地位者的福利份额。",
    formula: "\\max(\\min(U_i)) \\quad [\\text{Differenzprinzip zum Vorteil der Schwächsten}]",
    tags: ["Philosophie", "Rawls", "Gerechtigkeit", "Maximin", "Ethik", "Labor"],
  },
  {
    id: "philo-willensfreiheit",
    fach: "Philosophie",
    kategorieDE: "Anthropologie & Willensfreiheit",
    kategorieZH: "人论与自由意志判定",
    themenDE: "Willensfreiheit: Libet-Experiment & Determinismus",
    themenZH: "自由意志是否存在：李贝特脑电神经实验",
    stufe: "Q2",
    titleDE: "Willensfreiheit: Libet-Experiment & Kompatibilismus (Labor)",
    titleZH: "自由意志之争与李贝特实验脑电沙盒",
    descDE: "Bereitschaftspotenzial im Gehirn (-550 ms), bewusster Willensdrang (-200 ms), Veto-Recht des Bewusstseins und harter vs. weicher Determinismus.",
    descZH: "神经活动准备电位早于主观意图意识出现引发的因果律悖论、意识否决权（Veto）存在性与兼容论/强决定论哲学分歧。",
    formula: "t_{\\text{BP}} (-550\\text{ms}) < t_{\\text{Wille}} (-200\\text{ms}) < t_{\\text{Aktion}} (0\\text{ms})",
    tags: ["Philosophie", "Anthropologie", "Willensfreiheit", "Libet", "Determinismus", "Labor"],
  },
  {
    id: "philo-popper-falsifikation",
    fach: "Philosophie",
    kategorieDE: "Wissenschaftstheorie",
    kategorieZH: "科学哲学与逻辑方法论",
    themenDE: "Karl Popper: Falsifikationismus & Demarkation",
    themenZH: "波普尔证伪主义原则与科学划界标准",
    stufe: "Q2",
    titleDE: "Karl Popper: Falsifikationismus & Demarkation (Labor)",
    titleZH: "波普尔证伪主义与科学划界标准",
    descDE: "Das Induktionsproblem (weiße Schwäne), Asymmetrie zwischen Verifikation und Falsifikation, empirischer Gehalt einer Theorie.",
    descZH: "归纳法逻辑漏洞、全称命题不可能被穷尽经验证实但仅需一个反例即可完全证伪的逻辑不对称性（否定后件律 Modus Tollens）。",
    formula: "\\forall x (P(x) \\rightarrow Q(x)) \\;\\Leftarrow\\; \\exists x (P(x) \\land \\neg Q(x)) \\text{ (Falsifikation)}",
    tags: ["Philosophie", "Wissenschaftstheorie", "Popper", "Falsifikation", "Labor"],
  },
  {
    id: "philo-arendt-banalitaet",
    fach: "Philosophie",
    kategorieDE: "Anthropologie & Ethik der Verantwortung",
    kategorieZH: "政治伦理与责任哲学",
    themenDE: "Hannah Arendt: Banalität des Bösen & Urteilskraft",
    themenZH: "汉娜·阿伦特恶的平庸性与个体判断力",
    stufe: "Q2",
    titleDE: "Hannah Arendt: Banalität des Bösen & Urteilskraft (Labor)",
    titleZH: "汉娜·阿伦特恶的平庸与批判性判断力",
    descDE: "Eichmann-Prozess in Jerusalem: Gedankenlosigkeit, bürokratisches Rädchensystem, Zusammenbruch der Moral und die autonome Urteilskraft.",
    descZH: "非极度邪恶狂热而是放弃反思与批判思考（Gedankenlosigkeit）导致的毁灭性平庸之恶、体制化服从与独立道德判断力觉醒。",
    formula: "\\text{Urteilskraft} = \\text{Fähigkeit zu denken an der Stelle jedes anderen}",
    tags: ["Philosophie", "Arendt", "Ethik", "Urteilskraft", "Verantwortung", "Labor"],
  },

  // ==========================================
  // DEUTSCH / GEWI EXPANSION (+6 Labore, Gesamt: 7)
  // ==========================================
  {
    id: "deutsch-drama-freytag",
    fach: "Deutsch",
    kategorieDE: "Dramen- & Theateranalyse",
    kategorieZH: "戏剧结构与悲剧冲突",
    themenDE: "Gustav Freytags Dramenpyramide",
    themenZH: "古典封闭式戏剧五幕金字塔结构",
    stufe: "EF",
    titleDE: "Freytagsche Dramenpyramide & Spannungskurve (Labor)",
    titleZH: "弗赖塔格古典戏剧五幕金字塔沙盘",
    descDE: "Die 5 Akte: Exposition, erregendes Moment, Höhepunkt/Peripetie, retardierendes Moment, Katastrophe/Lösung in Lessing, Schiller, Goethe.",
    descZH: "引入动机、激化冲突、突转与最高潮、阻滞延缓迟滞点到悲剧大结局五幕张力曲线，经典剧目关键场次定位仿真。",
    formula: "\\text{Akt I (Exposition)} \\rightarrow \\text{Akt III (Peripetie)} \\rightarrow \\text{Akt V (Katastrophe)}",
    tags: ["Deutsch", "Drama", "Freytag", "Pyramide", "Spannung", "Labor"],
  },
  {
    id: "deutsch-lyrik-metrum",
    fach: "Deutsch",
    kategorieDE: "Lyrikanalyse & Poetik",
    kategorieZH: "诗歌格律与文本细读",
    themenDE: "Verslehre: Metrum, Kadenz und Reimschema",
    themenZH: "德语诗歌四大基本音步与韵律节奏",
    stufe: "EF",
    titleDE: "Metrik & Verslehre: Jambus, Trochäus, Zäsur (Labor)",
    titleZH: "诗歌格律与韵律节奏解剖工坊",
    descDE: "Jambus (v -), Trochäus (- v), Daktylus (- v v), Anapäst (v v -), männliche (stumpfe) vs. weibliche (klingende) Kadenzen und Enjambement.",
    descZH: "抑扬格、扬抑格、扬抑抑格音步特征、行尾抑止与流转韵律、跨行连续（Enjambement）与破折停顿（Zäsur）对抒情意境的塑造。",
    formula: "\\text{Jambus: } \\cup - \\quad \\text{Trochäus: } - \\cup \\quad \\text{Daktylus: } - \\cup \\cup",
    tags: ["Deutsch", "Lyrik", "Metrum", "Verslehre", "Kadenz", "Labor"],
  },
  {
    id: "deutsch-brecht-episch",
    fach: "Deutsch",
    kategorieDE: "Dramen- & Theateranalyse",
    kategorieZH: "叙事剧与反亚里士多德剧场",
    themenDE: "Bertolt Brecht: Episches Theater & V-Effekt",
    themenZH: "布莱希特叙事剧与间离效果（V-Effekt）",
    stufe: "Q1",
    titleDE: "Brechts Episches Theater: Verfremdungseffekt (Labor)",
    titleZH: "布莱希特叙事剧与间离效果实验台",
    descDE: "Gegenüberstellung: Aristotelische Katharsis & Einfühlung vs. Brechtsche Distanz, Songs, Spruchbänder und kritische Aktivierung des Zuschauers.",
    descZH: "亚里士多德式移情共鸣与净化 vs 布莱希特式打破舞台幻觉、中插歌曲、投影字幕阻断沉浸并迫使观众进行理性社会批判。",
    formula: "\\text{V-Effekt} = \\text{Ent-Selbstverständlicherung} \\;\\Rightarrow\\; \\text{Handlungsfähigkeit}",
    tags: ["Deutsch", "Drama", "Brecht", "EpischesTheater", "VEffekt", "Labor"],
  },
  {
    id: "deutsch-kafka-verwandlung",
    fach: "Deutsch",
    kategorieDE: "Epik & Moderne Literatur",
    kategorieZH: "现代主义文学与异化主题",
    themenDE: "Franz Kafka: Die Verwandlung & Entfremdung",
    themenZH: "卡夫卡《变形记》异化隐喻与空间动力学",
    stufe: "Q1",
    titleDE: "Kafka-Labor: Die Verwandlung & Entfremdung (Labor)",
    titleZH: "卡夫卡《变形记》异化隐喻与家庭空间沙盘",
    descDE: "Gregor Samsas Zimmer als psychologischer Raum, 3-türiges Grenzsystem, ökonomische Nützlichkeit und die Entmenschlichung der bürgerlichen Familie.",
    descZH: "格里高尔卧室三扇门的空间隔离象征、资本主义雇佣劳动工具化对人性的挤压与被家庭当成赘瘤抛弃的悲剧进程。",
    formula: "\\text{Entfremdung} = \\text{Wertverlust als Arbeitskraft} \\;\\Rightarrow\\; \\text{Reale Auslöschung}",
    tags: ["Deutsch", "Kafka", "Verwandlung", "Entfremdung", "Epik", "Labor"],
  },
  {
    id: "deutsch-borchert-draussen",
    fach: "Deutsch",
    kategorieDE: "Epik & Nachkriegsliteratur",
    kategorieZH: "战后废墟文学与心理创伤",
    themenDE: "Wolfgang Borchert: Trümmerliteratur & Kahlschlag",
    themenZH: "博尔歇特废墟文学与战后归乡者绝境",
    stufe: "EF",
    titleDE: "Trümmerliteratur: Wolfgang Borchert & Kahlschlag (Labor)",
    titleZH: "博尔歇特废墟文学与零度语言实验室",
    descDE: "Draußen vor der Tür, Das Brot: Stakkato-Stil, Repetition, Verdinglichung, existenzielle Schuld und das Trauma der Generation nach 1945.",
    descZH: "《门外》与《面包》短促断奏句式、反复修辞、对面包碎屑的微观凝视、归乡退伍士兵无法被市民社会接纳的心灵创伤。",
    formula: "\\text{Kahlschlag} = \\text{Verweigerung falscher Pathos-Sprache} + \\text{Nackte Wirklichkeit}",
    tags: ["Deutsch", "Trümmerliteratur", "Borchert", "Nachkrieg", "Kahlschlag", "Labor"],
  },
  {
    id: "deutsch-sachtext-argument",
    fach: "Deutsch",
    kategorieDE: "Sachtextanalyse & Pragmatik",
    kategorieZH: "论述文分析与批判性修辞",
    themenDE: "Sachtextanalyse: Stephen Toulmins Argumentationsmodell",
    themenZH: "图尔敏论证模型：事实、准则与反驳条件",
    stufe: "EF",
    titleDE: "Sachtextanalyse: Toulmin-Argumentationsmodell (Labor)",
    titleZH: "非虚构论述文：图尔敏论证结构解剖沙盒",
    descDE: "Claim (These), Data (Tatsache), Warrant (Schlussregel), Backing (Stützung), Rebuttal (Ausnahmebedingung) und Gültigkeitsoperator.",
    descZH: "主张（Claim）、根据（Datum）、保证（Warrant）、支援（Backing）、保留条件（Rebuttal）与限定词六要素实战图解。",
    formula: "\\text{Datum} \\xrightarrow{\\text{Warrant (gestützt durch Backing)}} \\text{Claim (vorbehaltlich Rebuttal)}",
    tags: ["Deutsch", "Sachtext", "Toulmin", "Argumentation", "Rhetorik", "Labor"],
  },
];
