#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
export-vault-data.py
Exports vault CSV flashcards and Markdown notes into TypeScript modules for App-EF-Lernvault.
Pure ASCII file safe for Windows PowerShell 5.1.
"""
import os
import csv
import re
import json

VAULT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_SRC = os.path.join(VAULT_ROOT, "App-EF-Lernvault", "src")

EXEMPT_FILES = {
    "README.md", "Lehrplan.md", "Ressourcen.md", "Satzbausteine.md",
    "Fehlerlog.md", "AGENTS.md", "HANDOVER.md", "HANDOVER-Archiv.md",
    "00-Designprinzipien.md", "00-Notenproduktion-Plan.md", "00-Abi-Baum-Design.md"
}

EMOJI_PATTERN = re.compile(r'[\U0001F000-\U0001FAFF\u2600-\u27BF]')

def sanitize_text(text: str) -> str:
    if not text:
        return ""
    return EMOJI_PATTERN.sub("", text).strip()

def export_flashcards():
    csv_paths = [
        os.path.join(VAULT_ROOT, "01_Deutsch", "Vokabeln-Anki", "Deutsch-EF-Phrasen.csv"),
        os.path.join(VAULT_ROOT, "02_Englisch", "Vokabeln-Anki", "Englisch-EF-Phrasen.csv"),
        os.path.join(VAULT_ROOT, "03_Mathe", "Vokabeln-Anki", "Mathe-EF-Basis.csv"),
        os.path.join(VAULT_ROOT, "04_Physik", "Vokabeln-Anki", "Physik-EF-Basis.csv"),
        os.path.join(VAULT_ROOT, "05_Chemie", "Vokabeln-Anki", "Chemie-EF-Basis.csv"),
        os.path.join(VAULT_ROOT, "06_Bio", "Vokabeln-Anki", "Bio-EF-Basis.csv"),
        os.path.join(VAULT_ROOT, "07_Philosophie", "Vokabeln-Anki", "Philo-EF-Basis.csv"),
        os.path.join(VAULT_ROOT, "08_SoWi", "Vokabeln-Anki", "SoWi-EF-Basis.csv"),
        os.path.join(VAULT_ROOT, "09_Musik-m\u00fcndl", "Vokabeln-Anki", "Musik-EF-Basis.csv"),
        os.path.join(VAULT_ROOT, "10_Sport-m\u00fcndl", "Vokabeln-Anki", "Sport-EF-Basis.csv"),
    ]

    cards = []
    card_idx = 1
    for cp in csv_paths:
        if not os.path.exists(cp):
            continue
        with open(cp, "r", encoding="utf-8") as f:
            reader = csv.reader(f, delimiter=";")
            header = next(reader, None)
            for row in reader:
                if not row or len(row) < 4:
                    continue
                front = sanitize_text(row[0])
                back = sanitize_text(row[1])
                example = sanitize_text(row[2]) if len(row) > 2 else ""
                fach = sanitize_text(row[3]) if len(row) > 3 else ""
                cards.append({
                    "id": f"card_{card_idx}",
                    "front": front,
                    "back": back,
                    "example": example,
                    "fach": fach,
                    "dueIn": "heute"
                })
                card_idx += 1

    out_file = os.path.join(APP_SRC, "generatedCards.ts")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/export-vault-data.py - DO NOT EDIT MANUALLY\n")
        f.write("export interface GeneratedCard {\n")
        f.write("  id: string;\n")
        f.write("  front: string;\n")
        f.write("  back: string;\n")
        f.write("  example: string;\n")
        f.write("  fach: string;\n")
        f.write("  dueIn: string;\n")
        f.write("}\n\n")
        f.write("export const allVaultCards: GeneratedCard[] = ")
        f.write(json.dumps(cards, ensure_ascii=False, indent=2))
        f.write(";\n")

    print(f"[export-vault-data] Exported {len(cards)} cards to {out_file}")
    return len(cards)

def export_notes():
    notes = []
    note_idx = 1
    seen_ids = set()

    for root, dirs, files in os.walk(VAULT_ROOT):
        dirs[:] = [d for d in dirs if not d.startswith(".") and d not in (
            "App-EF-Lernvault", "_Downloads", "node_modules", "dist",
            "src-tauri", "brain", "Templates", "00_META", "Lernreise", "Skills"
        )]
        for fname in sorted(files):
            if not fname.endswith(".md") or fname in EXEMPT_FILES:
                continue
            full_path = os.path.join(root, fname)
            rel_path = os.path.relpath(full_path, VAULT_ROOT).replace("\\", "/")

            with open(full_path, "r", encoding="utf-8") as f:
                content = f.read()

            if not content.startswith("---"):
                continue
            parts = content.split("---", 2)
            if len(parts) < 3:
                continue
            fm_text = parts[1]
            body_text = parts[2]

            fach_m = re.search(r"^fach:\s*([^\r\n]+)", fm_text, re.M)
            fach = sanitize_text(fach_m.group(1)) if fach_m else "Sonstiges"

            thema_m = re.search(r"^thema:\s*\"?([^\r\n\"]+)\"?", fm_text, re.M)
            thema = sanitize_text(thema_m.group(1)) if thema_m else fname[:-3]

            ops_m = re.search(r"^operatoren:\s*\[(.*?)\]", fm_text, re.M)
            operatoren = []
            if ops_m and ops_m.group(1).strip():
                operatoren = [sanitize_text(op.strip().strip("'\"")) for op in ops_m.group(1).split(",") if op.strip()]

            klausurrelevant = "klausurrelevant: true" in fm_text

            # Parse H1 title for German and Chinese
            h1_m = re.search(r"^#\s+([^\r\n]+)", body_text, re.M)
            h1 = h1_m.group(1).strip() if h1_m else thema

            zh_title = thema
            zh_m = re.search(r"\(([^)]+)\)", h1)
            if zh_m:
                candidate = sanitize_text(zh_m.group(1))
                if any("\u4e00" <= ch <= "\u9fff" for ch in candidate):
                    zh_title = candidate

            # Extract body summary sentences
            body_de = []
            body_zh = []

            ks_matches = re.findall(r">\s*\*?Klausur-Satz\*?:\s*([^\r\n]+)", body_text)
            for ks in ks_matches[:3]:
                clean_ks = sanitize_text(ks.strip().strip("*`"))
                if clean_ks:
                    body_de.append(clean_ks)

            # Look for Chinese understanding
            zh_lead_m = re.search(r">\s*\*\*中文理解\*\*[:：]\s*([^\r\n]+(?:\r?\n>\s*[^\r\n]+)*)", body_text)
            if zh_lead_m:
                lead_lines = [line.lstrip("> ").strip() for line in zh_lead_m.group(1).splitlines() if line.strip()]
                combined_lead = " ".join(lead_lines)
                sentences = [sanitize_text(s) for s in re.split(r"[。；]", combined_lead) if len(s.strip()) > 8]
                for s in sentences[:3]:
                    body_zh.append(s + "。")

            if not body_de:
                body_de = [f"Thema: {thema} ({fach}). Exam-relevante Wissensnotiz."]
            if not body_zh:
                body_zh = [f"{fach} 核心考纲笔记：{zh_title}。"]

            slug = fname[:-3].lower().replace(" ", "-")
            fach_prefix = re.sub(r'[^a-z0-9]', '', fach.lower())
            note_id = f"{fach_prefix}-{slug}"
            if note_id in seen_ids:
                note_id = f"{note_id}-{note_idx}"
            seen_ids.add(note_id)

            notes.append({
                "id": note_id,
                "fach": fach,
                "thema": thema,
                "zh": zh_title,
                "operatoren": operatoren,
                "klausurrelevant": klausurrelevant,
                "bodyDE": body_de,
                "bodyZH": body_zh,
                "path": rel_path
            })
            note_idx += 1

    out_file = os.path.join(APP_SRC, "generatedNotes.ts")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/export-vault-data.py - DO NOT EDIT MANUALLY\n")
        f.write("export interface GeneratedNote {\n")
        f.write("  id: string;\n")
        f.write("  fach: string;\n")
        f.write("  thema: string;\n")
        f.write("  zh: string;\n")
        f.write("  operatoren: string[];\n")
        f.write("  klausurrelevant: boolean;\n")
        f.write("  bodyDE: string[];\n")
        f.write("  bodyZH: string[];\n")
        f.write("  path: string;\n")
        f.write("}\n\n")
        f.write("export const allVaultNotes: GeneratedNote[] = ")
        f.write(json.dumps(notes, ensure_ascii=False, indent=2))
        f.write(";\n")

    print(f"[export-vault-data] Exported {len(notes)} notes to {out_file}")
    return len(notes)

if __name__ == "__main__":
    n_cards = export_flashcards()
    n_notes = export_notes()
    print(f"[export-vault-data] Done! Cards={n_cards}, Notes={n_notes}")
