#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
export-vault-data.py
Exports vault CSV flashcards and Markdown notes into TypeScript modules for App-EF-Lernvault.
Pure ASCII file safe for Windows PowerShell 5.1.
"""
import os
import csv
import re
import json

VAULT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_SRC = os.path.join(VAULT_ROOT, "App-EF-Lernvault", "src")

EXEMPT_FILES = {
    "README.md", "Lehrplan.md", "Ressourcen.md", "Satzbausteine.md",
    "Fehlerlog.md", "AGENTS.md", "HANDOVER.md", "HANDOVER-Archiv.md",
    "00-Designprinzipien.md", "00-Notenproduktion-Plan.md", "00-Abi-Baum-Design.md"
}

EMOJI_PATTERN = re.compile(r'[\U0001F000-\U0001FAFF\u2600-\u27BF]')

def sanitize_text(text: str) -> str:
    if not text:
        return ""
    return EMOJI_PATTERN.sub("", text).strip()

def export_flashcards():
    import glob
    csv_paths = sorted(glob.glob(os.path.join(VAULT_ROOT, "*", "Vokabeln-Anki", "*.csv")))

    cards = []
    card_idx = 1
    for cp in csv_paths:
        if not os.path.exists(cp):
            continue
        with open(cp, "r", encoding="utf-8") as f:
            reader = csv.reader(f, delimiter=";")
            header = next(reader, None)
            for row in reader:
                if not row or len(row) < 4:
                    continue
                front = sanitize_text(row[0])
                back = sanitize_text(row[1])
                example = sanitize_text(row[2]) if len(row) > 2 else ""
                fach = sanitize_text(row[3]) if len(row) > 3 else ""
                cards.append({
                    "id": f"card_{card_idx}",
                    "front": front,
                    "back": back,
                    "example": example,
                    "fach": fach,
                    "dueIn": "heute"
                })
                card_idx += 1

    out_file = os.path.join(APP_SRC, "generatedCards.ts")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/export-vault-data.py - DO NOT EDIT MANUALLY\n")
        f.write("export interface GeneratedCard {\n")
        f.write("  id: string;\n")
        f.write("  front: string;\n")
        f.write("  back: string;\n")
        f.write("  example: string;\n")
        f.write("  fach: string;\n")
        f.write("  dueIn: string;\n")
        f.write("}\n\n")
        f.write("export const allVaultCards: GeneratedCard[] = ")
        f.write(json.dumps(cards, ensure_ascii=False, indent=2))
        f.write(";\n")

    print(f"[export-vault-data] Exported {len(cards)} cards to {out_file}")
    return len(cards)

def parse_markdown_blocks(body: str):
    blocks = []
    in_math = False
    in_diagram = False
    math_buf = []
    diagram_buf = []

    def has_cjk(s):
        return any("\u4e00" <= ch <= "\u9fff" for ch in s)

    def clean_inline(s):
        s = re.sub(r"^#+\s*", "", s)
        s = re.sub(r"^[-*]\s+", "", s)
        return sanitize_text(s)

    for raw_line in body.splitlines():
        line = raw_line.strip()
        if line.startswith("```"):
            fence = line[3:].strip().lower()
            if in_math or in_diagram:
                if in_math:
                    code = sanitize_text("\n".join(math_buf))
                    if code:
                        blocks.append({"kind": "math", "text": code, "lang": "de"})
                    math_buf = []
                    in_math = False
                else:
                    spec = sanitize_text("\n".join(diagram_buf))
                    if spec:
                        blocks.append({"kind": "diagram", "text": spec, "lang": "de"})
                    diagram_buf = []
                    in_diagram = False
            elif fence.startswith("diagram"):
                in_diagram = True
            else:
                in_math = True
            continue

        if in_math:
            math_buf.append(raw_line)
            continue
        if in_diagram:
            diagram_buf.append(raw_line)
            continue

        if not line:
            continue

        if line.startswith(">"):
            t = re.sub(r"^>+\s*", "", line).strip()
            if t:
                cleaned = clean_inline(t)
                if cleaned:
                    blocks.append({"kind": "quote", "text": cleaned, "lang": "zh" if has_cjk(cleaned) else "de"})
            continue

        if line.startswith("### "):
            cleaned = clean_inline(line)
            if cleaned:
                blocks.append({"kind": "h3", "text": cleaned, "lang": "zh" if has_cjk(cleaned) else "de"})
        elif line.startswith("## "):
            cleaned = clean_inline(line)
            if cleaned:
                blocks.append({"kind": "h2", "text": cleaned, "lang": "zh" if has_cjk(cleaned) else "de"})
        elif re.match(r"^[-*]\s+", line):
            cleaned = clean_inline(line)
            if cleaned:
                blocks.append({"kind": "li", "text": cleaned, "lang": "zh" if has_cjk(cleaned) else "de"})
        elif not line.startswith("#"):
            cleaned = clean_inline(line)
            if cleaned:
                blocks.append({"kind": "p", "text": cleaned, "lang": "zh" if has_cjk(cleaned) else "de"})

    return blocks

def export_notes():
    notes = []
    vault_notes = []
    note_idx = 1
    seen_ids = set()

    for root, dirs, files in os.walk(VAULT_ROOT):
        dirs[:] = [d for d in dirs if not d.startswith(".") and d not in (
            "App-EF-Lernvault", "_Downloads", "node_modules", "dist",
            "src-tauri", "brain", "Templates", "00_META", "Lernreise", "Skills"
        )]
        for fname in sorted(files):
            if not fname.endswith(".md") or fname in EXEMPT_FILES:
                continue
            full_path = os.path.join(root, fname)
            rel_path = os.path.relpath(full_path, VAULT_ROOT).replace("\\", "/")

            with open(full_path, "r", encoding="utf-8") as f:
                content = f.read()

            if not content.startswith("---"):
                continue
            parts = content.split("---", 2)
            if len(parts) < 3:
                continue
            fm_text = parts[1]
            body_text = parts[2]

            fach_m = re.search(r"^fach:\s*([^\r\n]+)", fm_text, re.M)
            fach = sanitize_text(fach_m.group(1)) if fach_m else "Sonstiges"

            thema_m = re.search(r"^thema:\s*\"?([^\r\n\"]+)\"?", fm_text, re.M)
            thema = sanitize_text(thema_m.group(1)) if thema_m else fname[:-3]

            ops_m = re.search(r"^operatoren:\s*\[(.*?)\]", fm_text, re.M)
            operatoren = []
            if ops_m and ops_m.group(1).strip():
                operatoren = [sanitize_text(op.strip().strip("'\"")) for op in ops_m.group(1).split(",") if op.strip()]

            klausurrelevant = "klausurrelevant: true" in fm_text

            datum_m = re.search(r"^datum:\s*([^\r\n]+)", fm_text, re.M)
            datum = sanitize_text(datum_m.group(1)) if datum_m else "2026-09-25"

            tags_m = re.search(r"^tags:\s*\[(.*?)\]", fm_text, re.M)
            tags = [sanitize_text(t.strip().strip("'\"")) for t in tags_m.group(1).split(",") if t.strip()] if tags_m else ["EF", fach]

            # Parse H1 title for German and Chinese
            h1_m = re.search(r"^#\s+([^\r\n]+)", body_text, re.M)
            h1 = h1_m.group(1).strip() if h1_m else thema

            zh_title = thema
            zh_m = re.search(r"\(([^)]+)\)", h1)
            if zh_m:
                candidate = sanitize_text(zh_m.group(1))
                if any("\u4e00" <= ch <= "\u9fff" for ch in candidate):
                    zh_title = candidate

            # Extract body summary sentences
            body_de = []
            body_zh = []

            ks_matches = re.findall(r">\s*\*?Klausur-Satz\*?:\s*([^\r\n]+)", body_text)
            for ks in ks_matches[:3]:
                clean_ks = sanitize_text(ks.strip().strip("*`"))
                if clean_ks:
                    body_de.append(clean_ks)

            # Look for Chinese understanding
            zh_lead_m = re.search(r">\s*\*\*中文理解\*\*[:：]\s*([^\r\n]+(?:\r?\n>\s*[^\r\n]+)*)", body_text)
            if zh_lead_m:
                lead_lines = [line.lstrip("> ").strip() for line in zh_lead_m.group(1).splitlines() if line.strip()]
                combined_lead = " ".join(lead_lines)
                sentences = [sanitize_text(s) for s in re.split(r"[。；]", combined_lead) if len(s.strip()) > 8]
                for s in sentences[:3]:
                    body_zh.append(s + "。")

            if not body_de:
                body_de = [f"Thema: {thema} ({fach}). Exam-relevante Wissensnotiz."]
            if not body_zh:
                body_zh = [f"{fach} 核心考纲笔记：{zh_title}。"]

            slug = fname[:-3].lower().replace(" ", "-")
            fach_prefix = re.sub(r'[^a-z0-9]', '', fach.lower())
            note_id = f"{fach_prefix}-{slug}"
            if note_id in seen_ids:
                note_id = f"{note_id}-{note_idx}"
            seen_ids.add(note_id)

            notes.append({
                "id": note_id,
                "fach": fach,
                "thema": thema,
                "zh": zh_title,
                "operatoren": operatoren,
                "klausurrelevant": klausurrelevant,
                "bodyDE": body_de,
                "bodyZH": body_zh,
                "path": rel_path
            })

            blocks = parse_markdown_blocks(body_text)
            vault_notes.append({
                "id": note_id,
                "path": rel_path,
                "fach": fach,
                "thema": thema,
                "operatoren": operatoren,
                "klausurrelevant": klausurrelevant,
                "datum": datum,
                "tags": tags,
                "blocks": blocks
            })

            note_idx += 1

    out_file = os.path.join(APP_SRC, "generatedNotes.ts")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/export-vault-data.py - DO NOT EDIT MANUALLY\n")
        f.write("export interface GeneratedNote {\n")
        f.write("  id: string;\n")
        f.write("  fach: string;\n")
        f.write("  thema: string;\n")
        f.write("  zh: string;\n")
        f.write("  operatoren: string[];\n")
        f.write("  klausurrelevant: boolean;\n")
        f.write("  bodyDE: string[];\n")
        f.write("  bodyZH: string[];\n")
        f.write("  path: string;\n")
        f.write("}\n\n")
        f.write("export const allVaultNotes: GeneratedNote[] = ")
        f.write(json.dumps(notes, ensure_ascii=False, indent=2))
        f.write(";\n")

    vault_out_file = os.path.join(APP_SRC, "generatedVaultNotes.ts")
    with open(vault_out_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/export-vault-data.py - DO NOT EDIT MANUALLY\n")
        f.write("export interface Block {\n")
        f.write("  kind: \"h2\" | \"h3\" | \"p\" | \"li\" | \"quote\" | \"math\" | \"diagram\";\n")
        f.write("  text: string;\n")
        f.write("  lang: \"zh\" | \"de\";\n")
        f.write("}\n\n")
        f.write("export interface GeneratedVaultNote {\n")
        f.write("  id: string;\n")
        f.write("  path: string;\n")
        f.write("  fach: string;\n")
        f.write("  thema: string;\n")
        f.write("  operatoren: string[];\n")
        f.write("  klausurrelevant: boolean;\n")
        f.write("  datum: string;\n")
        f.write("  tags: string[];\n")
        f.write("  blocks: Block[];\n")
        f.write("}\n\n")
        f.write("export const allVaultNotesWithBlocks: GeneratedVaultNote[] = ")
        f.write(json.dumps(vault_notes, ensure_ascii=False, indent=2))
        f.write(";\n")

    print(f"[export-vault-data] Exported {len(notes)} notes to {out_file}")
    print(f"[export-vault-data] Exported {len(vault_notes)} vault notes to {vault_out_file}")
    return len(notes)

if __name__ == "__main__":
    n_cards = export_flashcards()
    n_notes = export_notes()
    print(f"[export-vault-data] Done! Cards={n_cards}, Notes={n_notes}")
