import type { FachId } from "../fach";

export type MilestoneStage = 1 | 2 | 3;

export interface CurriculumMilestone {
  readonly stufe: MilestoneStage;
  readonly stufeLabelDE: string;
  readonly stufeLabelZH: string;
  readonly titleDE: string;
  readonly titleZH: string;
  readonly operatoren: readonly string[];
  readonly noteKeywords: readonly string[];
  readonly leitfrageDE: string;
  readonly leitfrageZH: string;
}

export interface CurriculumInhaltsfeld {
  readonly code: string;
  readonly titleDE: string;
  readonly titleZH: string;
  readonly leitgedankeDE: string;
  readonly leitgedankeZH: string;
  readonly milestones: readonly CurriculumMilestone[];
}

export interface SubjectCurriculumTree {
  readonly fach: FachId;
  readonly nameDE: string;
  readonly nameZH: string;
  readonly domain: "gewi" | "sprachen" | "mint" | "muendlich";
  readonly klpReferenz: string;
  readonly klausurFokusDE: string;
  readonly klausurFokusZH: string;
  readonly inhaltsfelder: readonly CurriculumInhaltsfeld[];
}

export const CURRICULUM_TREES: Record<FachId, SubjectCurriculumTree> = {
  Deutsch: {
    fach: "Deutsch",
    nameDE: "Deutsch",
    nameZH: "德语文学与语言",
    domain: "sprachen",
    klpReferenz: "NRW KLP Deutsch GOSt (ab 2023) & ZKE Vorgaben",
    klausurFokusDE: "Sachtextanalyse (Aufgabenart II A) & Lyrik-/Drameninterpretation (Aufgabenart I A)",
    klausurFokusZH: "实用文读者引导分析（任务类型 II A）与诗歌/戏剧文本细读（任务类型 I A）",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Texte: Sachtexte & Leserlenkung",
        titleZH: "文本领域：实用文与读者引导",
        leitgedankeDE: "Analyse informierender und argumentierender Texte nach Sinnabschnitten",
        leitgedankeZH: "按意义段落解构议论文论证结构与读者心理引导机制",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Erschließung",
            stufeLabelZH: "阶段 1 · 导语与论据分类",
            titleDE: "TATTE-Formel & Argumenttypen",
            titleZH: "TATTE 导语公式与六大论据分类",
            operatoren: ["darstellen", "beschreiben"],
            noteKeywords: ["sachtext", "leserlenkung", "argumentation", "rhetorik"],
            leitfrageDE: "Welche These vertritt der Autor und welche Argumente stützen sie?",
            leitfrageZH: "作者核心论点是什么，通过何种事实或规范论据进行支撑？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Analyse",
            stufeLabelZH: "阶段 2 · 修辞微观功能链",
            titleDE: "Rhetorischer Dreischritt & Leserlenkung",
            titleZH: "修辞分析三步法与读者心理操控",
            operatoren: ["analysieren", "untersuchen"],
            noteKeywords: ["leserlenkung", "rhetorik", "dreischritt", "scheinargument"],
            leitfrageDE: "Wie steuern rhetorische Stilmittel und Argumentationsgang die Rezipienten?",
            leitfrageZH: "修辞手法与论证展开如何具体引导并操控读者的态度认知？",
          },
          {
            stufe: 3,
            stufeLabelDE: "Stufe 3 · Urteil",
            stufeLabelZH: "阶段 3 · 价值评判与综合议论",
            titleDE: "Kritische Würdigung & Erörterung",
            titleZH: "批判性审视与综合议论文写作",
            operatoren: ["beurteilen", "erörtern", "stellung nehmen"],
            noteKeywords: ["eroerterung", "stellungnahme", "wuerdigung"],
            leitfrageDE: "Inwiefern ist die argumentative Beweisführung stichhaltig und überzeugend?",
            leitfrageZH: "作者的论证逻辑在多大程度上具备充分的说服力与现实有效性？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Texte: Lyrik & Epochenkontext",
        titleZH: "文本领域：诗歌鉴赏与时代流派",
        leitgedankeDE: "Historisch-gesellschaftliche Einbettung lyrischer Texte (Sturm und Drang / Klassik)",
        leitgedankeZH: "狂飙突进与古典时期抒情诗歌的意象解码与时代精神反思",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Formanalyse",
            stufeLabelZH: "阶段 1 · 形式与格律解构",
            titleDE: "Metrum, Reimschema & Kadenzen",
            titleZH: "诗歌格律、韵脚模式与抑扬顿挫",
            operatoren: ["beschreiben", "bestimmen"],
            noteKeywords: ["lyrik", "goethe", "metrum", "reim"],
            leitfrageDE: "Welche formale Struktur kennzeichnet das lyrische Gedicht?",
            leitfrageZH: "诗歌的节律、行数分布与韵脚规则呈现何种形式特征？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Interpretation",
            stufeLabelZH: "阶段 2 · 阐释假说与意象群",
            titleDE: "Deutungshypothese & Motivanalyse",
            titleZH: "阐释假说确立与自然情感意象分析",
            operatoren: ["analysieren", "interpretieren"],
            noteKeywords: ["deutungshypothese", "sturm-drang", "willkommen-abschied"],
            leitfrageDE: "Wie spiegeln Natur- und Liebesmotive das Lebensgefühl des Sturm und Drang wider?",
            leitfrageZH: "自然意象与爱情冲突如何映射狂飙突进时期的叛逆与生命张力？",
          },
          {
            stufe: 3,
            stufeLabelDE: "Stufe 3 · Synthese",
            stufeLabelZH: "阶段 3 · 时代共鸣与比较阐释",
            titleDE: "Epochenreflexion & Gedichtvergleich",
            titleZH: "时代精神总结与跨时期诗歌对比",
            operatoren: ["vergleichen", "erörtern"],
            noteKeywords: ["gedichtvergleich", "epochenreflexion"],
            leitfrageDE: "In welchem Verhältnis steht das lyrische Ich zu den Normen seiner Epoche?",
            leitfrageZH: "诗歌中的抒情主体与当时的主流社会规范构成何种互动与张力？",
          },
        ],
      },
      {
        code: "IF 3",
        titleDE: "Texte: Drama als Ganzschrift",
        titleZH: "文本领域：整本戏剧全书精读",
        leitgedankeDE: "Konfliktdynamik und Figurenkonstellation in klassischen/modernen Dramen",
        leitgedankeZH: "经典与现代戏剧中的人物关系图谱、矛盾冲突与悲喜转折",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Figuren",
            stufeLabelZH: "阶段 1 · 人物关系与舞台指示",
            titleDE: "Figurenkonstellation & Regieanweisungen",
            titleZH: "人物对立谱系与舞台指示潜台词",
            operatoren: ["beschreiben", "darstellen"],
            noteKeywords: ["drama", "figurenkonstellation", "duerrenmatt", "frisch"],
            leitfrageDE: "Welche Machtverhältnisse und Allianzen herrschen zwischen den Protagonisten?",
            leitfrageZH: "主要戏剧人物之间存在怎样的主从、敌友与权力制衡关系？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Szenenanalyse",
            stufeLabelZH: "阶段 2 · 戏剧场面与对白剖析",
            titleDE: "Dialogführung & Wendepunkte (Peripetie)",
            titleZH: "对白潜台词剖析与情节危机转折点",
            operatoren: ["analysieren", "untersuchen"],
            noteKeywords: ["dialog", "peripetie", "szenenanalyse"],
            leitfrageDE: "Wie treibt der dramatische Dialog den zentralen Konflikt zur Eskalation?",
            leitfrageZH: "戏剧对白中的争锋与试探如何推动核心冲突走向不可逆的爆发？",
          },
        ],
      },
    ],
  },
  Englisch: {
    fach: "Englisch",
    nameDE: "Englisch",
    nameZH: "英语语言与跨文化产出",
    domain: "sprachen",
    klpReferenz: "NRW KLP Englisch GOSt (ab 2023) · Zielniveau B1+/B2",
    klausurFokusDE: "Teil A (Text comprehension, Analysis, Comment) & Teil B (Mediation)",
    klausurFokusZH: "Teil A 文本读写一体（概括-分析-评论）与 Teil B 跨文化中继调解",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Individual & Society: Role Models & Identity",
        titleZH: "个人与社会：榜样范式与青年认同",
        leitgedankeDE: "Identity construction, diversity, ambitions and societal pressure in the English-speaking world",
        leitgedankeZH: "英语世界中的多元文化碰撞、青年身份认同建构与社会期许压力",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stage 1 · Comprehension",
            stufeLabelZH: "阶段 1 · 事实提取与客观概括",
            titleDE: "Summary Writing & Key Fact Selection",
            titleZH: "客观概要写作与非个人化语言规范",
            operatoren: ["outline", "summarize"],
            noteKeywords: ["summary", "role models", "pee", "characterization"],
            leitfrageDE: "What are the protagonist's core beliefs and how are they introduced?",
            leitfrageZH: "主角的核心价值观与人生动机是什么，作者如何将其引入文本？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stage 2 · Analysis",
            stufeLabelZH: "阶段 2 · P.E.E. 论据链人物刻画",
            titleDE: "P.E.E. Principle & Stylistic Devices",
            titleZH: "观点-引文-阐释三段论与文体风格分析",
            operatoren: ["analyze", "characterize"],
            noteKeywords: ["pee", "stylistic devices", "characterization", "register"],
            leitfrageDE: "How do register, tone, and figurative language reveal the character's motivation?",
            leitfrageZH: "语域、语气与修辞手法如何揭示人物深层的心理动因？",
          },
          {
            stufe: 3,
            stufeLabelDE: "Stage 3 · Evaluation",
            stufeLabelZH: "阶段 3 · 批判性评述与独立反思",
            titleDE: "Comment & Discussion of Modern Role Models",
            titleZH: "现代榜样现象价值评析与论述写作",
            operatoren: ["comment", "discuss", "evaluate"],
            noteKeywords: ["comment", "role-models-analysis", "discussion"],
            leitfrageDE: "To what extent do contemporary media role models foster authentic self-worth?",
            leitfrageZH: "当代社交媒体塑造的偶像榜样在何种程度上促进了青年的健康自我认同？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Mediation: Transcultural Information Transfer",
        titleZH: "调解领域：跨文化交际与语用中继",
        leitgedankeDE: "Selecting, restructuring, and contextualizing German source content for English addressees",
        leitgedankeZH: "针对特定英语受众进行德语源文本的信息遴选、重构与文化概念转译",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stage 1 · Context & Format",
            stufeLabelZH: "阶段 1 · 任务场景定位与体裁确立",
            titleDE: "Situational Embedding & Target Format",
            titleZH: "交际情境代入与目标文本格式规范",
            operatoren: ["identify", "select"],
            noteKeywords: ["mediation", "format", "target audience", "register"],
            leitfrageDE: "Who is the recipient and what exact communicative purpose must the text fulfill?",
            leitfrageZH: "目标受众是谁，文本必须达成怎样具体的交际任务与语调匹配？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stage 2 · Transformation",
            stufeLabelZH: "阶段 2 · 核心信息提取与文化释义",
            titleDE: "Paraphrasing & Cultural Contextualization",
            titleZH: "脱离字面改写与德国本土制度文化释义",
            operatoren: ["mediate", "explain"],
            noteKeywords: ["mediation", "paraphrasing", "contextualization", "strategies"],
            leitfrageDE: "How can German institutional terms (e.g. FSJ, Abitur) be explained clearly without borrowing German words?",
            leitfrageZH: "如何用纯正英语解释德国本土制度术语，彻底避免生硬死译？",
          },
        ],
      },
    ],
  },
  Philosophie: {
    fach: "Philosophie",
    nameDE: "Philosophie",
    nameZH: "哲学思考与伦理批判",
    domain: "gewi",
    klpReferenz: "NRW KLP Philosophie GOSt (EF) · Anthropologie & Ethik",
    klausurFokusDE: "Rekonstruktion philosophischer Argumente & Kriteriengeleitete Urteilsbildung",
    klausurFokusZH: "哲学命题三段论重构与基于道德准则的价值裁决写作",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Ethik: Grundmodelle moralischen Handelns",
        titleZH: "伦理学：道德行动的基础模型",
        leitgedankeDE: "Deontologische Pflichtethik (Kant) versus teleologischer Utilitarismus (Bentham/Mill)",
        leitgedankeZH: "康德先验义务论与功利主义目的论的根本对立与案例检验",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Begriffe",
            stufeLabelZH: "阶段 1 · 核心伦理概念建构",
            titleDE: "Kategorischer Imperativ vs. Utilitaristisches Kalkül",
            titleZH: "康德绝对命令公式与边沁功利核算模型",
            operatoren: ["darstellen", "beschreiben"],
            noteKeywords: ["utilitarismus", "kant", "imperativ", "kalkuel"],
            leitfrageDE: "Worin besteht der fundamentale Unterschied zwischen Pflicht und Folgenabwägung?",
            leitfrageZH: "出于纯粹义务的行动与权衡后果功利的行动在道德哲学上有何根本分野？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Rekonstruktion",
            stufeLabelZH: "阶段 2 · 准则普遍化四步推演",
            titleDE: "Vier-Schritte-Maximenprüfung & Selbstzweckformel",
            titleZH: "四步准则普遍化检验与人类自为目的公式",
            operatoren: ["rekonstruieren", "analysieren"],
            noteKeywords: ["maximenpruefung", "selbstzweckformel", "denkbarkeit", "wollbarkeit"],
            leitfrageDE: "Führt die Universalisierung der subjektiven Handlungsmaxime zu einem Denk- oder Wollenswiderspruch?",
            leitfrageZH: "行动准则若升格为普遍自然法则，会产生设想矛盾还是理性意愿矛盾？",
          },
          {
            stufe: 3,
            stufeLabelDE: "Stufe 3 · Dilemma-Urteil",
            stufeLabelZH: "阶段 3 · 极端道德困境裁决",
            titleDE: "Ethische Dilemmata: Trolley-Problem & Lügenverbot",
            titleZH: "经典道德两难：电车难题与不可撒谎戒律",
            operatoren: ["beurteilen", "vergleichen", "erörtern"],
            noteKeywords: ["dilemmata", "trolley", "luegenverbot", "menschenwuerde"],
            leitfrageDE: "Darf ein Menschenleben gegen das Wohl einer Mehrheit aufgerechnet werden?",
            leitfrageZH: "人命是否可以在任何情境下被当作换取更大社会功利的数学砝码？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Anthropologie: Das Menschenbild",
        titleZH: "人论领域：人的本质与自由界限",
        leitgedankeDE: "Freiheit, Determination, Vernunft und kulturelle Prägung des Menschen",
        leitgedankeZH: "人类意志自由、生理/社会决定论与理性主体的反思潜能",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Anthropologie",
            stufeLabelZH: "阶段 1 · 人类学核心学说",
            titleDE: "Der Mensch als Natur- und Kulturwesen",
            titleZH: "人作为自然存在物与文化存在物的双重属性",
            operatoren: ["darstellen", "beschreiben"],
            noteKeywords: ["menschenbild", "anthropologie", "plickat"],
            leitfrageDE: "Inwiefern ist der Mensch durch Triebe biologisch determiniert oder zur Freiheit verurteilt?",
            leitfrageZH: "人在多大程度上受本能生物学决定，又在何种意义上拥有不可剥夺的自由？",
          },
        ],
      },
    ],
  },
  SoWi: {
    fach: "SoWi",
    nameDE: "Sozialwissenschaften",
    nameZH: "社会科学综合（经济/政治/社会）",
    domain: "gewi",
    klpReferenz: "NRW KLP Sozialwissenschaften GOSt (EF) · Inhaltsfelder 1–3",
    klausurFokusDE: "Materialanalyse, Kriterienorientiertes Urteil (Effizienz & Legitimität), Karikaturdekonstruktion",
    klausurFokusZH: "社会政治材料解构、标准导向裁决（效率与合法性）与政治讽刺漫画评析",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Marktwirtschaft & Verbraucherentscheidungen",
        titleZH: "市场经济体制与消费者决策微观机制",
        leitgedankeDE: "Angebot und Nachfrage, Preisbildung, Marktformen und Marktversagen",
        leitgedankeZH: "供求关系、均衡价格形成、完全竞争与市场失灵（外部效应/公共品）",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Modelle",
            stufeLabelZH: "阶段 1 · 市场理论与经济人模型",
            titleDE: "Homo Oeconomicus & Preisbildung",
            titleZH: "理性经济人假设与完全竞争市场价格机制",
            operatoren: ["darstellen", "erläutern"],
            noteKeywords: ["soziale-marktwirtschaft", "konsum-wirtschaften", "marktversagen"],
            leitfrageDE: "Wie reguliert der Preismechanismus Angebot und Nachfrage bei vollkommener Konkurrenz?",
            leitfrageZH: "价格机制在理想市场条件下如何实现资源的最优配置？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Ordnungspolitik",
            stufeLabelZH: "阶段 2 · 社会市场经济体制支柱",
            titleDE: "Soziale Marktwirtschaft & Wohlfahrtsstaat",
            titleZH: "社会市场经济秩序支柱与社会保障网构建",
            operatoren: ["analysieren", "vergleichen"],
            noteKeywords: ["soziale-marktwirtschaft", "erhard", "ordnungspolitik"],
            leitfrageDE: "Welche ordnungspolitischen Leitplanken setzt der Staat zur Vermeidung von Monopolen?",
            leitfrageZH: "国家通过哪些竞争法与反垄断政策维持公平竞争并保障民生福祉？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Soziale Ungleichheit & Sozialstruktur",
        titleZH: "社会不平等与社会结构流动分层",
        leitgedankeDE: "Dimensionen sozialer Ungleichheit, Schichtmodelle und soziale Mobilität",
        leitgedankeZH: "收入财富分配、教育机会不平等、阶层结构与代际流动阻滞",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Dimensionen",
            stufeLabelZH: "阶段 1 · 四大不平等维度与指标",
            titleDE: "Einkommen, Vermögen, Bildung & Macht",
            titleZH: "财富收入分配不均与基尼系数量化分析",
            operatoren: ["darstellen", "beschreiben"],
            noteKeywords: ["soziale-ungleichheit", "mobilitaet", "gini"],
            leitfrageDE: "Anhand welcher Kriterien und Indikatoren wird soziale Ungleichheit in Deutschland gemessen?",
            leitfrageZH: "德国官方统计与学术界依据哪些核心指标测度财富与收入的不平等？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Mobilität",
            stufeLabelZH: "阶段 2 · 教育阶层固化与代际流动",
            titleDE: "Intergenerationale Mobilität & Chancengleichheit",
            titleZH: "代际社会流动壁垒与教育机会公平性危机",
            operatoren: ["analysieren", "erläutern"],
            noteKeywords: ["mobilitaet", "chancengerechtigkeit", "herkunft"],
            leitfrageDE: "Inwiefern bestimmt die soziale Herkunft den Bildungserfolg im deutschen Schulsystem?",
            leitfrageZH: "家庭社会阶层背景在多大程度上决定了德国学生的升学与学术成功？",
          },
          {
            stufe: 3,
            stufeLabelDE: "Stufe 3 · Urteilsbildung",
            stufeLabelZH: "阶段 3 · 再分配政策标准导向裁决",
            titleDE: "Kriterienurteil: Effizienz & Legitimität von Transferleistungen",
            titleZH: "转移支付与福利政策效率性与合法性价值裁决",
            operatoren: ["beurteilen", "erörtern", "stellung nehmen"],
            noteKeywords: ["kriterienurteil", "effizienz", "legitimitaet", "gestaltungsaufgabe"],
            leitfrageDE: "Ist eine Erhöhung der Erbschaftssteuer ökonomisch effizient und sozial legitim?",
            leitfrageZH: "提高遗产税率在经济效率（投资活力）与社会公正合法性上是否具有可行性？",
          },
        ],
      },
    ],
  },
  Mathe: {
    fach: "Mathe",
    nameDE: "Mathematik",
    nameZH: "数学分析与几何代数推演",
    domain: "mint",
    klpReferenz: "NRW KLP Mathematik GOSt (EF) · Funktionen & Analysis",
    klausurFokusDE: "Ganzrationale Funktionen, Differentialrechnung, Tangentensteigung, Modellierung (Steckbrief)",
    klausurFokusZH: "整式多项式函数性质、微积分导数几何直观、切线方程与待定系数逆推建模",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Funktionen & Analysis: Grundlagen",
        titleZH: "函数与分析：多项式函数全局性质",
        leitgedankeDE: "Ganzrationale Funktionen, Symmetrieverhalten, Nullstellen und Grenzwerte",
        leitgedankeZH: "多项式函数代数特征、主导项极限行为、轴对称/原点对称与因式分解求根",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Symmetrie & Nullstellen",
            stufeLabelZH: "阶段 1 · 对称性判据与方程求根",
            titleDE: "Globalverhalten & Symmetriekriterien",
            titleZH: "无穷远处渐近行为与奇偶指数对称判定",
            operatoren: ["bestimmen", "untersuchen"],
            noteKeywords: ["kurvendiskussion", "symmetrie", "nullstellen", "ableitung"],
            leitfrageDE: "Welchen Einfluss haben der höchste Exponent und der Leitkoeffizient auf das Grenzverhalten?",
            leitfrageZH: "多项式最高次项系数与奇偶性如何主导自变量趋向无穷时的极限走向？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Kurvendiskussion",
            stufeLabelZH: "阶段 2 · 导数判据与极值拐点特征",
            titleDE: "Extrema, Wendepunkte & Monotonie",
            titleZH: "一阶/二阶导数极值充分必要条件与单调性",
            operatoren: ["berechnen", "bestimmen"],
            noteKeywords: ["kurvendiskussion", "extrema", "wendepunkt", "monotonie"],
            leitfrageDE: "Unter welchen Bedingungen liegt an der Stelle x0 ein lokaler Hochpunkt bzw. Wendepunkt vor?",
            leitfrageZH: "在点 x0 处判定存在局部极大值点或曲率拐点的充分与必要条件是什么？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Differentialrechnung: Steigung & Tangenten",
        titleZH: "微积分基础：瞬时变化率与切线沙盘",
        leitgedankeDE: "Vom Differenzenquotienten zur Ableitung: Grenzwertprozess Δx → 0",
        leitgedankeZH: "从割线平均变化率到导数瞬时变化率的连续逼近微积分思想",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Ableitungsbegriff",
            stufeLabelZH: "阶段 1 · 割线逼近与导数定义",
            titleDE: "Sekanten- zu Tangentensteigung (Limes)",
            titleZH: "割线斜率向切线极限演进的几何直观",
            operatoren: ["herleiten", "erläutern"],
            noteKeywords: ["ableitung", "steigung", "tangente", "limes"],
            leitfrageDE: "Wie wird die lokale Änderungsrate mathematisch als Grenzwert des Differenzenquotienten definiert?",
            leitfrageZH: "瞬时变化率在数学上如何严格定义为差商步长趋近于零时的导数极限？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Tangentenformel",
            stufeLabelZH: "阶段 2 · 规范求导法则与切线方程",
            titleDE: "Ableitungsregeln & Tangentengleichung",
            titleZH: "幂函数法则、线性运算法则与点斜式切线方程",
            operatoren: ["berechnen", "aufstellen"],
            noteKeywords: ["tangentenformel", "potenzregel", "faktorregel"],
            leitfrageDE: "Wie lautet die Gleichung der Tangente im Kurvenpunkt P(x0 | f(x0))?",
            leitfrageZH: "在曲线定点 P(x0 | f(x0)) 处如何依据导数斜率标准求出切线解析式？",
          },
        ],
      },
      {
        code: "IF 3",
        titleDE: "Modellierung: Steckbriefaufgaben",
        titleZH: "实际建模应用：待定系数与几何条件逆推",
        leitgedankeDE: "Rekonstruktion von Funktionsgleichungen aus geometrischen und anwendungsbezogenen Bedingungen",
        leitgedankeZH: "依据定点坐标、切线斜率与拐点极值几何条件设立线性方程组逆推解析式",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Bedingungen",
            stufeLabelZH: "阶段 1 · 几何语言向代数方程翻译",
            titleDE: "Bedingungsgleichungen & Freiheitsgrade",
            titleZH: "特征条件翻译与多项式未知数阶数匹配",
            operatoren: ["aufstellen", "bestimmen"],
            noteKeywords: ["steckbrief", "funktionsrekonstruktion", "bedingung"],
            leitfrageDE: "Wie viele linear unabhängige Bedingungen benötigt ein Polynom 3. Grades für eine eindeutige Lösung?",
            leitfrageZH: "三次多项式需要多少个线性无关的几何特征条件才能实现确定解？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Gleichungssystem",
            stufeLabelZH: "阶段 2 · 高斯消元求解与合理性检验",
            titleDE: "LGS-Lösung & Randwertvalidierung",
            titleZH: "线性方程组高斯求解与定义域极值边界检验",
            operatoren: ["berechnen", "begründen"],
            noteKeywords: ["steckbrief", "gauss", "lgs", "funktionsanpassung"],
            leitfrageDE: "Erfüllt die rekonstruierte Kurve im Sachzusammenhang alle geforderten Randbedingungen?",
            leitfrageZH: "逆推求得的函数曲线在工程或经济物理情境中是否满足所有边界约束？",
          },
        ],
      },
    ],
  },
  Physik: {
    fach: "Physik",
    nameDE: "Physik",
    nameZH: "物理实验力学与运动能量定律",
    domain: "mint",
    klpReferenz: "NRW KLP Physik GOSt (EF) · Mechanik (Kinematik & Dynamik)",
    klausurFokusDE: "Gleichmäßig beschleunigte Bewegung, Freier Fall, Newtonsche Gesetze, Hangabtrieb, Energieerhaltung",
    klausurFokusZH: "匀加速运动运动学方程、自由落体实验、牛顿运动公理、斜面受力分析与机械能守恒",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Kinematik: Lineare Bewegungen & Freier Fall",
        titleZH: "运动学：直线运动方程与自由落体定律",
        leitgedankeDE: "Orts-, Geschwindigkeits- und Beschleunigungs-Zeit-Gesetze, grafische Differentiation/Integration",
        leitgedankeZH: "s-t、v-t、a-t 图象分析，斜率速度对应与积分位移面积计算",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Diagramme",
            stufeLabelZH: "阶段 1 · 运动图象的几何物理意义",
            titleDE: "s-t- und v-t-Diagrammanalyse",
            titleZH: "位移时间与速度时间图象的斜率与包围面积",
            operatoren: ["beschreiben", "skizzieren"],
            noteKeywords: ["kinematik", "gleichfoermige", "diagramm", "beschleunigt"],
            leitfrageDE: "Welche physikalische Größe entspricht der Steigung im s-t-Graph bzw. der Fläche unter dem v-t-Graph?",
            leitfrageZH: "s-t 图切线斜率与 v-t 图曲线下方包围的面积分别具有怎样的物理物理量意义？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Freier Fall",
            stufeLabelZH: "阶段 2 · 自由落体与重力加速度量纲",
            titleDE: "Freier Fall & Erdbeschleunigung g",
            titleZH: "真空自由落体方程与重力加速度量纲控制",
            operatoren: ["berechnen", "herleiten"],
            noteKeywords: ["freier fall", "beschleunigt", "superposition", "erdbeschleunigung"],
            leitfrageDE: "Warum fallen im Vakuum alle Körper unabhängig von ihrer Masse gleich schnell?",
            leitfrageZH: "为何在真空状态下所有物体下落的加速度均严格相同且与物体质量无关？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Dynamik: Newtonsche Axiome & Kräftezerlegung",
        titleZH: "动力学：牛顿运动定律与受力分析模型",
        leitgedankeDE: "Trägheit, Kraft und Gegenkraft, Kräftezerlegung an der geneigten Ebene, Reibungskräfte",
        leitgedankeZH: "惯性定律、动量定理 F=ma、作用反作用力与斜面正压力下滑力正交分解",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Newtonsche Axiome",
            stufeLabelZH: "阶段 1 · 牛顿三大运动定律体系",
            titleDE: "Trägheit, F = m · a & Actio gleich Reactio",
            titleZH: "惯性定律、牛顿第二定律与作用反作用定律",
            operatoren: ["erläutern", "beschreiben"],
            noteKeywords: ["newton", "kraft", "traegheit", "dynamik"],
            leitfrageDE: "Welche Resultierende Kraft bewirkt die Beschleunigung eines Körpers nach dem 2. Newtonschen Gesetz?",
            leitfrageZH: "物体获得恒定加速度的充要条件是什么，合外力与质量具备何种量纲对应关系？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Geneigte Ebene",
            stufeLabelZH: "阶段 2 · 斜面受力正交分解与摩擦",
            titleDE: "Hangabtriebskraft & Normalkraftzerlegung",
            titleZH: "下滑力与法向正压力分解计算及滑动摩擦",
            operatoren: ["berechnen", "analysieren"],
            noteKeywords: ["hangabtrieb", "normalkraft", "reibung", "ebene"],
            leitfrageDE: "Wie berechnen sich Hangabtriebskraft FH und Normalkraft FN in Abhängigkeit vom Neigungswinkel α?",
            leitfrageZH: "在倾角为 α 的斜面上，重力如何正交分解为下滑驱动力与垂直贴合正压力？",
          },
        ],
      },
    ],
  },
  Chemie: {
    fach: "Chemie",
    nameDE: "Chemie",
    nameZH: "化学微观平衡与酸碱分子动力学",
    domain: "mint",
    klpReferenz: "NRW KLP Chemie GOSt (EF) · Chemisches Gleichgewicht & Säure-Base",
    klausurFokusDE: "Massenwirkungsgesetz, Le Chatelier, Brønsted-Theorie, pH-Berechnung, Zwischenmolekulare Kräfte",
    klausurFokusZH: "质量作用定律、勒夏特列平衡移动、布朗斯特质子酸碱、pH对数计算与分子间作用力",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Chemisches Gleichgewicht & Kinetik",
        titleZH: "化学平衡常数与反应动态移动原理",
        leitgedankeDE: "Dynamisches Gleichgewicht, Massenwirkungsgesetz (Kc) und Prinzip von Le Chatelier",
        leitgedankeZH: "正逆反应速率相等平衡状态、质量作用定律表达式与外界应激对抗移动",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · MWG",
            stufeLabelZH: "阶段 1 · 质量作用定律数学表达式",
            titleDE: "Massenwirkungsgesetz & Gleichgewichtskonstante",
            titleZH: "质量作用定律（MWG）与浓度平衡常数 Kc 计算",
            operatoren: ["aufstellen", "berechnen"],
            noteKeywords: ["gleichgewicht", "le chatelier", "massenwirkungsgesetz"],
            leitfrageDE: "Wie wird die Gleichgewichtskonstante Kc aus den Gleichgewichtskonzentrationen berechnet?",
            leitfrageZH: "对于给定可逆化学反应方程式，如何书写并计算平衡常数 Kc 表达式？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Le Chatelier",
            stufeLabelZH: "阶段 2 · 勒夏特列外部应激平衡移动",
            titleDE: "Prinzip vom kleinsten Zwang (T, p, c)",
            titleZH: "温度、压力与浓度改变对平衡移动方向调控",
            operatoren: ["erläutern", "begründen"],
            noteKeywords: ["le chatelier", "stoerung", "endotherm", "exotherm"],
            leitfrageDE: "In welche Richtung verschiebt eine Temperaturerhöhung ein exothermes chemisches Gleichgewicht?",
            leitfrageZH: "对于放热反应可逆体系，升高反应温度时平衡将向何方移动并如何解释？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Säure-Base-Gleichgewichte & pH-Wert",
        titleZH: "酸碱质子理论与水溶液电离平衡",
        leitgedankeDE: "Brønsted-Konzept (Protonendonator/-akzeptor), Autoprotolyse, pH- und pOH-Berechnung",
        leitgedankeZH: "布朗斯特质子传递对、水自耦电离常数与对数 pH 标度中和滴定",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Brønsted-Theorie",
            stufeLabelZH: "阶段 1 · 共轭酸碱质子对判定",
            titleDE: "Protonendonator & korrespondierende Säure-Base-Paare",
            titleZH: "质子供体与受体识别及共轭酸碱对配对",
            operatoren: ["beschreiben", "aufstellen"],
            noteKeywords: ["saeure", "base", "broensted", "protolyse"],
            leitfrageDE: "Welche Teilchen fungieren in einer Protolysereaktion als Protonendonator bzw. -akzeptor?",
            leitfrageZH: "在水溶液质子转移反应中，哪个粒子作为质子供体，共轭对应产物是什么？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · pH-Skala",
            stufeLabelZH: "阶段 2 · 对数 pH 标度与水离子积常数",
            titleDE: "Autoprotolyse des Wassers & pH-Berechnung",
            titleZH: "水自耦电离常数 Kw=10^-14 与强弱酸 pH 定量计算",
            operatoren: ["berechnen", "begründen"],
            noteKeywords: ["ph-wert", "autoprotolyse", "ionenprodukt", "titration"],
            leitfrageDE: "Wie berechnet sich der pH-Wert aus der Oxoniumionenkonzentration c(H3O+)?",
            leitfrageZH: "水合氢离子浓度如何通过负对数公式换算为体系的 pH 标度值？",
          },
        ],
      },
      {
        code: "IF 3",
        titleDE: "Zwischenmolekulare Kräfte & Stoffeigenschaften",
        titleZH: "物质微观结构：分子间作用力与物理性质",
        leitgedankeDE: "Van-der-Waals-Kräfte, Dipol-Dipol-Kräfte, Wasserstoffbrücken und Makroeigenschaften",
        leitgedankeZH: "瞬时偶极范德华力、永久偶极相互作用、氢键网络与沸点溶解度规律",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Krafttypen",
            stufeLabelZH: "阶段 1 · 三大作用力强弱阶梯划分",
            titleDE: "Van-der-Waals, Dipole & Wasserstoffbrücken",
            titleZH: "范德华力、极性偶极作用与典型分子氢键",
            operatoren: ["beschreiben", "vergleichen"],
            noteKeywords: ["zwischenmolekulare", "van-der-waals", "wasserstoffbruecken", "dipol"],
            leitfrageDE: "Welche Voraussetzungen müssen für die Ausbildung stabiler Wasserstoffbrückenbindungen vorliegen?",
            leitfrageZH: "分子间形成稳定氢键相互作用必须具备怎样的电负性原子与极性共价键条件？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Eigenschaften",
            stufeLabelZH: "阶段 2 · 宏观沸点与相似相溶机理解释",
            titleDE: "Siedepunktsreihen & Löslichkeitsprinzip",
            titleZH: "同系物宏观相变沸点阶梯与极性溶剂溶解度规律",
            operatoren: ["erläutern", "begründen"],
            noteKeywords: ["siedepunkt", "loeslichkeit", "similia", "zmk"],
            leitfrageDE: "Warum besitzt Wasser (H2O) trotz geringer Molmasse einen anomal hohen Siedepunkt?",
            leitfrageZH: "为什么分子量仅为 18 的水具有远超同族氢化物的反常极高沸点？",
          },
        ],
      },
    ],
  },
  Bio: {
    fach: "Bio",
    nameDE: "Biologie",
    nameZH: "细胞生物学与跨膜生命动力系统",
    domain: "mint",
    klpReferenz: "NRW KLP Biologie GOSt (EF) · Zellbiologie & Biomembran",
    klausurFokusDE: "Flüssig-Mosaik-Modell, passiver/aktiver Transport, Osmose, Plasmolyse, Enzymkinetik (RGT)",
    klausurFokusZH: "流动镶嵌膜模型、主动被动跨膜转运、渗透压平衡、质壁分离实验与酶动力学催化",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Biomembran & Transportmechanismen",
        titleZH: "生物膜结构系统与选择透过性跨膜转运",
        leitgedankeDE: "Flüssig-Mosaik-Modell, Kanal- und Carrierproteine, Diffusion, Osmose und Plasmolyse",
        leitgedankeZH: "磷脂双分子层流动镶嵌结构、载体/通道蛋白促进扩散、主动运输与渗透质壁分离",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Membranmodell",
            stufeLabelZH: "阶段 1 · 磷脂双分子层流动镶嵌模型",
            titleDE: "Flüssig-Mosaik-Modell & Kompartimentierung",
            titleZH: "亲水亲脂两亲分子骨架与跨膜外周蛋白嵌入",
            operatoren: ["beschreiben", "skizzieren"],
            noteKeywords: ["biomembran", "fluessig-mosaik", "phospholipid", "osmose"],
            leitfrageDE: "Wie ist die Phospholipid-Doppelschicht amphiphil aufgebaut und warum ist sie selektiv permeabel?",
            leitfrageZH: "磷脂分子的两亲性结构如何自发形成双层水相阻隔并产生选择透过性？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Transport & Osmose",
            stufeLabelZH: "阶段 2 · 顺浓度被动转运与逆浓度主动运输",
            titleDE: "Passiver vs. aktiver Transport & Plasmolyse",
            titleZH: "通道/载体协助扩散、ATP主动消耗与植物细胞质壁分离",
            operatoren: ["vergleichen", "erklären"],
            noteKeywords: ["carrier", "kanalprotein", "plasmolyse", "deplasmolyse", "transport"],
            leitfrageDE: "Unter welchen osmotischen Bedingungen löst sich der Protoplast einer Pflanzenzelle von der Zellwand?",
            leitfrageZH: "在何种张力渗透环境下植物细胞会发生脱水质壁分离，其复原条件是什么？",
          },
        ],
      },
      {
        code: "IF 2",
        titleDE: "Enzymatik & Zellstoffwechsel",
        titleZH: "酶催化动力学与细胞生物化学反应",
        leitgedankeDE: "Schlüssel-Schloss-Prinzip, Aktivierungsenergie, RGT-Regel, Denaturierung und pH-Optimum",
        leitgedankeZH: "锁钥模型活性中心、活化能降低机制、范霍夫温度系数与极端条件变性",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Wirkungsweise",
            stufeLabelZH: "阶段 1 · 活化能降低与专一性催化",
            titleDE: "Aktivierungsenergie & Enzym-Substrat-Komplex",
            titleZH: "酶-底物复合物形成与化学反应活化能显著降低",
            operatoren: ["beschreiben", "erläutern"],
            noteKeywords: ["enzym", "aktivierungsenergie", "zellbiologie"],
            leitfrageDE: "Auf welche Weise beschleunigen Enzyme biochemische Stoffwechselreaktionen?",
            leitfrageZH: "生物酶通过何种构象变化机制极大降低反应所需的化学活化能？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Einflussfaktoren",
            stufeLabelZH: "阶段 2 · 温度曲线与 pH 最适范围调控",
            titleDE: "RGT-Regel, Temperaturoptimum & Denaturierung",
            titleZH: "温度 RGT 效应、最适温度峰值与空间构象不可逆变性",
            operatoren: ["analysieren", "begründen"],
            noteKeywords: ["rgt", "denaturierung", "optimum", "enzymkinetik"],
            leitfrageDE: "Warum bricht die Enzymaktivität oberhalb des Temperaturoptimums schlagartig ein?",
            leitfrageZH: "为何当反应温度超越最适临界值后，酶活性会出现断崖式归零崩溃？",
          },
        ],
      },
    ],
  },
  Musik: {
    fach: "Musik",
    nameDE: "Musik",
    nameZH: "音乐曲式分析与口试鉴赏呈现",
    domain: "muendlich",
    klpReferenz: "NRW KLP Musik GOSt (EF) · Sonatenhauptsatz & Motivverarbeitung",
    klausurFokusDE: "Mündliche Prüfung: Sonatenhauptsatzform, Motivverarbeitung (Krebs/Umkehrung), Höranalyse",
    klausurFokusZH: "口试重点：奏鸣曲式宏观结构、动机展开技法（逆行/倒影）与听觉分析答辩",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Musikalische Satzlehre & Form",
        titleZH: "曲式结构：奏鸣曲式与动机展开",
        leitgedankeDE: "Exposition, Durchführung, Reprise; Motivische Umkehrung, Krebs und Abspaltung",
        leitgedankeZH: "呈示部、展开部、再现部三段式曲式，音程倒影与时序逆行展开技法",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Formabschnitte",
            stufeLabelZH: "阶段 1 · 呈示部展开部调性布局",
            titleDE: "Sonatenhauptsatzform: Tonika & Dominante",
            titleZH: "主部主题（主调）与副部主题（属调）调性对立统一",
            operatoren: ["darstellen", "beschreiben"],
            noteKeywords: ["sonatenhauptsatzform", "exposition", "reprise", "beethoven"],
            leitfrageDE: "Wie unterscheiden sich Exposition und Reprise hinsichtlich der Tonarten ihrer Themen?",
            leitfrageZH: "呈示部副部主题处于属调或平行大调，在再现部中如何回归主部主调？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Verarbeitung",
            stufeLabelZH: "阶段 2 · 动机展开与变奏技法剖析",
            titleDE: "Motivverarbeitung: Umkehrung & Krebs",
            titleZH: "音程轴线镜像倒影与旋律逆行技法解剖",
            operatoren: ["analysieren", "untersuchen"],
            noteKeywords: ["motiv", "krebs", "umkehrung", "hoeren"],
            leitfrageDE: "An welchen Stellen der Durchführung wird das Kernmotiv abgespalten oder gespiegelt?",
            leitfrageZH: "展开部中作曲家如何通过节奏紧缩、音程倒影与剥离推动戏剧性张力？",
          },
        ],
      },
    ],
  },
  Sport: {
    fach: "Sport",
    nameDE: "Sport",
    nameZH: "运动生理机能与训练负荷适应",
    domain: "muendlich",
    klpReferenz: "NRW KLP Sport GOSt (EF) · Trainingslehre & Biomechanik",
    klausurFokusDE: "Mündliche Prüfung: Superkompensation, Belastungssteuerung, Energiebereitstellung (Laktat)",
    klausurFokusZH: "口试重点：超量恢复四阶段模型、运动负荷节奏调控与无氧/有氧供能代谢",
    inhaltsfelder: [
      {
        code: "IF 1",
        titleDE: "Trainingslehre & Sportphysiologie",
        titleZH: "训练学与运动生理代偿适应",
        leitgedankeDE: "Homöostasestörung, Erholungsphase, Superkompensation und Übertraining",
        leitgedankeZH: "训练负荷内环境破坏、机体超量恢复储备与过度训练衰竭预防",
        milestones: [
          {
            stufe: 1,
            stufeLabelDE: "Stufe 1 · Superkompensation",
            stufeLabelZH: "阶段 1 · 超量恢复四阶段曲线模型",
            titleDE: "Phasenmodell der Superkompensation",
            titleZH: "负荷刺激、疲劳衰竭、代偿恢复与波峰进阶",
            operatoren: ["beschreiben", "erläutern"],
            noteKeywords: ["superkompensation", "trainingslehre", "belastung", "erholung"],
            leitfrageDE: "Wann muss der Folge-Trainingsreiz gesetzt werden, um Leistungszuwächse zu erzielen?",
            leitfrageZH: "下一个递进训练刺激必须精准落在超量恢复曲线的哪个生理时间窗口？",
          },
          {
            stufe: 2,
            stufeLabelDE: "Stufe 2 · Energiebereitstellung",
            stufeLabelZH: "阶段 2 · 代谢供能通路与乳酸阈值",
            titleDE: "Anaerob-laktazid vs. aerobe Kapazität",
            titleZH: "磷酸原爆发、无氧糖酵解乳酸阈值与有氧氧化供能",
            operatoren: ["analysieren", "beurteilen"],
            noteKeywords: ["energiebereitstellung", "laktat", "anaerob", "aerob"],
            leitfrageDE: "Welches Energiesystem dominiert bei maximalen Kurzzeitbelastungen bis 30 Sekunden?",
            leitfrageZH: "在 30 秒至 2 分钟的高强度极限负荷中，何种代谢供能系统占据主导地位？",
          },
        ],
      },
    ],
  },
};

export function getCurriculumTreeForFach(fach: string): SubjectCurriculumTree | undefined {
  return CURRICULUM_TREES[fach as FachId];
}
