import type { FachBaum } from "./types";

export const bioBaum: FachBaum = {
  fach: "Bio",
  nameDE: "Biologie",
  nameZH: "生物",
  klpReferenz: "NRW KLP Biologie 2022",
  klausurFokusDE: "Material-/Mikroskopbild-Auswertung; Basiskonzepte Struktur-Funktion / Information / Steuerung",
  klausurFokusZH: "细胞生物学打地基；画图、术语、实验分析三件套，标注→描述→解释→评价四步答题",
  root: {
    id: "bio",
    level: 0,
    code: "",
    titleDE: "Biologie",
    titleZH: "生物",
    operatoren: [],
    klausurDE: "",
    klausurZH: "",
    leitfrageDE: "",
    leitfrageZH: "",
    noteKeywords: [],
    children: [
      {
        id: "bio/if1",
        level: 1,
        code: "IF 1",
        titleDE: "Zellbiologie",
        titleZH: "细胞生物学",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "bio/if1/zellaufbau-vergleich",
            level: 2,
            code: "",
            titleDE: "Zellaufbau und Vergleich",
            titleZH: "细胞结构与比较",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "bio/if1/zellaufbau-vergleich/tierische-zelle",
                level: 3,
                code: "",
                titleDE: "Tierische Zelle",
                titleZH: "动物细胞",
                operatoren: ["nennen", "beschriften", "beschreiben"],
                klausurDE: "Tierzelle beschriften und beschreiben (AFB I).",
                klausurZH: "标注图题",
                leitfrageDE: "Woran erkennt man eine Tierzelle?",
                leitfrageZH: "如何认出动物细胞？",
                noteKeywords: ["tierzelle", "zellbiologie", "beschriften"],
                children: [],
              },
              {
                id: "bio/if1/zellaufbau-vergleich/pflanzliche-zelle",
                level: 3,
                code: "",
                titleDE: "Pflanzliche Zelle",
                titleZH: "植物细胞",
                operatoren: ["beschriften", "beschreiben", "vergleichen"],
                klausurDE: "Pflanzen- vs. Tierzelle vergleichen.",
                klausurZH: "对比题",
                leitfrageDE: "Welche Strukturen hat nur die Pflanzenzelle?",
                leitfrageZH: "植物细胞独有什么结构？",
                noteKeywords: ["pflanzenzelle", "zellwand", "chloroplast", "vergleich"],
                children: [],
              },
              {
                id: "bio/if1/zellaufbau-vergleich/bakterienzelle",
                level: 3,
                code: "",
                titleDE: "Bakterienzelle",
                titleZH: "细菌细胞",
                operatoren: ["beschreiben", "vergleichen", "begründen"],
                klausurDE: "Prokaryot vs. Eukaryot begründen.",
                klausurZH: "比较解释题",
                leitfrageDE: "Was fehlt der Bakterienzelle?",
                leitfrageZH: "细菌细胞缺什么？",
                noteKeywords: ["bakterienzelle", "prokaryot", "eukaryot", "vergleich"],
                children: [],
              },
              {
                id: "bio/if1/zellaufbau-vergleich/groessenordnung",
                level: 3,
                code: "",
                titleDE: "Größenordnung",
                titleZH: "尺寸数量级",
                operatoren: ["angeben", "zuordnen", "berechnen"],
                klausurDE: "Größen abschätzen, Maßstab umrechnen.",
                klausurZH: "材料题小问",
                leitfrageDE: "Wie groß ist was in der Zelle?",
                leitfrageZH: "细胞里各结构有多大？",
                noteKeywords: ["groessenordnung", "mikrometer", "massstab"],
                children: [],
              },
            ],
          },
          {
            id: "bio/if1/organellen-funktion",
            level: 2,
            code: "",
            titleDE: "Organellen und Funktion",
            titleZH: "细胞器与功能",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "bio/if1/organellen-funktion/zellkern",
                level: 3,
                code: "",
                titleDE: "Zellkern",
                titleZH: "细胞核",
                operatoren: ["beschreiben", "erklären", "beschriften"],
                klausurDE: "Kernstruktur mit Informationsfunktion verknüpfen.",
                klausurZH: "结构→功能题",
                leitfrageDE: "Wie steuert der Kern die Zelle?",
                leitfrageZH: "细胞核如何控制细胞？",
                noteKeywords: ["zellkern", "information", "kernpore"],
                children: [],
              },
              {
                id: "bio/if1/organellen-funktion/mitochondrien-chloroplasten",
                level: 3,
                code: "",
                titleDE: "Mitochondrien und Chloroplasten",
                titleZH: "线粒体与叶绿体",
                operatoren: ["beschreiben", "erklären", "vergleichen"],
                klausurDE: "Beide als Energiestationen vergleichen (AFB II).",
                klausurZH: "对比解释题",
                leitfrageDE: "Was verbindet Mitochondrium und Chloroplast?",
                leitfrageZH: "线粒体和叶绿体有什么共同点？",
                noteKeywords: ["mitochondrium", "chloroplast", "energie", "vergleich"],
                children: [],
              },
              {
                id: "bio/if1/organellen-funktion/endomembransystem",
                level: 3,
                code: "",
                titleDE: "Endomembransystem",
                titleZH: "内膜系统（内质网、高尔基体、囊泡）",
                operatoren: ["beschreiben", "erklären", "darstellen"],
                klausurDE: "Proteinweg durch die Zelle als Fließschema darstellen.",
                klausurZH: "流程题",
                leitfrageDE: "Wie reist ein Protein durch die Zelle?",
                leitfrageZH: "蛋白质如何在细胞里旅行？",
                noteKeywords: ["endomembransystem", "golgi", "vesikel", "proteinweg"],
                children: [],
              },
              {
                id: "bio/if1/organellen-funktion/struktur-funktion",
                level: 3,
                code: "",
                titleDE: "Struktur-Funktion",
                titleZH: "结构与功能的关系",
                operatoren: ["erklären", "begründen", "bewerten"],
                klausurDE: "Struktur und Funktion erklären (Basiskonzept!).",
                klausurZH: "全卷红线",
                leitfrageDE: "Welche Funktion erklärt diese Struktur?",
                leitfrageZH: "这个结构对应什么功能？",
                noteKeywords: ["struktur-funktion", "basiskonzept", "begruendung"],
                children: [],
              },
            ],
          },
          {
            id: "bio/if1/membran-transport",
            level: 2,
            code: "",
            titleDE: "Membran und Transport",
            titleZH: "膜与物质运输",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "bio/if1/membran-transport/fluid-mosaik",
                level: 3,
                code: "",
                titleDE: "Fluid-Mosaik-Modell",
                titleZH: "流镶嵌模型",
                operatoren: ["beschreiben", "darstellen", "erklären"],
                klausurDE: "Modell skizzieren und selektive Permeabilität erklären.",
                klausurZH: "模型题",
                leitfrageDE: "Warum ist die Membran selektiv durchlässig?",
                leitfrageZH: "膜为什么选择透过？",
                noteKeywords: ["fluessig-mosaik", "biomembran", "phospholipid", "permeabilitaet"],
                children: [],
              },
              {
                id: "bio/if1/membran-transport/diffusion",
                level: 3,
                code: "",
                titleDE: "Diffusion",
                titleZH: "扩散",
                operatoren: ["beschreiben", "erklären", "auswerten"],
                klausurDE: "Diffusionsversuch beschreiben und deuten.",
                klausurZH: "实验解读",
                leitfrageDE: "Wohin wandern Teilchen von allein?",
                leitfrageZH: "粒子自发往哪里走？",
                noteKeywords: ["diffusion", "konzentration", "transport"],
                children: [],
              },
              {
                id: "bio/if1/membran-transport/osmose",
                level: 3,
                code: "",
                titleDE: "Osmose",
                titleZH: "渗透",
                operatoren: ["erklären", "auswerten", "begründen"],
                klausurDE: "Plasmolyse-Versuch auswerten (AFB II).",
                klausurZH: "经典实验题",
                leitfrageDE: "Was passiert mit Zellen in Salz- vs. Süßwasser?",
                leitfrageZH: "细胞在盐水和清水中分别怎样？",
                noteKeywords: ["osmose", "plasmolyse", "deplasmolyse", "transport"],
                children: [],
              },
              {
                id: "bio/if1/membran-transport/aktiver-transport",
                level: 3,
                code: "",
                titleDE: "Aktiver Transport",
                titleZH: "主动运输",
                operatoren: ["erklären", "vergleichen", "begründen"],
                klausurDE: "Aktiv vs. passiv unterscheiden und begründen.",
                klausurZH: "对比题",
                leitfrageDE: "Wann lohnt sich aktiver Transport?",
                leitfrageZH: "主动运输何时值得？",
                noteKeywords: ["aktiver-transport", "carrier", "kanalprotein", "atp"],
                children: [],
              },
            ],
          },
          {
            id: "bio/if1/enzyme",
            level: 2,
            code: "",
            titleDE: "Enzyme",
            titleZH: "酶",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "bio/if1/enzyme/spezifitaet",
                level: 3,
                code: "",
                titleDE: "Substrat- und Wirkungsspezifität",
                titleZH: "底物专一性与作用专一性",
                operatoren: ["beschreiben", "erklären", "begründen"],
                klausurDE: "Schlüssel-Schloss-Prinzip anwenden.",
                klausurZH: "模型解释题",
                leitfrageDE: "Warum passt nur ein Substrat?",
                leitfrageZH: "为什么只有一种底物匹配？",
                noteKeywords: ["spezifitaet", "schluessel-schloss", "substrat", "enzym"],
                children: [],
              },
              {
                id: "bio/if1/enzyme/rgt-regel",
                level: 3,
                code: "",
                titleDE: "RGT-Regel",
                titleZH: "温度系数规则",
                operatoren: ["auswerten", "erklären", "deuten"],
                klausurDE: "Temperaturoptimum aus Diagramm bestimmen.",
                klausurZH: "曲线分析题",
                leitfrageDE: "Warum hat jedes Enzym ein Optimum?",
                leitfrageZH: "为什么每种酶都有最适温度？",
                noteKeywords: ["rgt", "optimum", "enzymkinetik", "temperatur"],
                children: [],
              },
              {
                id: "bio/if1/enzyme/denaturierung",
                level: 3,
                code: "",
                titleDE: "Denaturierung",
                titleZH: "变性",
                operatoren: ["erklären", "begründen", "bewerten"],
                klausurDE: "Denaturierung als Struktur-Funktions-Beweis nutzen.",
                klausurZH: "解释评价题",
                leitfrageDE: "Warum ist Denaturierung meist irreversibel?",
                leitfrageZH: "变性为什么多半不可逆？",
                noteKeywords: ["denaturierung", "struktur-funktion", "enzym"],
                children: [],
              },
              {
                id: "bio/if1/enzyme/versuchsauswertung",
                level: 3,
                code: "",
                titleDE: "Versuchsauswertung",
                titleZH: "酶实验分析",
                operatoren: ["auswerten", "deuten", "bewerten"],
                klausurDE: "Enzymversuch mit Kontrolle auswerten.",
                klausurZH: "实验分析必考",
                leitfrageDE: "Was beweist der Kontrollansatz?",
                leitfrageZH: "对照组证明了什么？",
                noteKeywords: ["versuch", "kontrolle", "auswertung", "enzym"],
                children: [],
              },
            ],
          },
          {
            id: "bio/if1/energie-mikroskopie",
            level: 2,
            code: "",
            titleDE: "Energie und Mikroskopie",
            titleZH: "能量基础与显微镜",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "bio/if1/energie-mikroskopie/zellatmung",
                level: 3,
                code: "",
                titleDE: "Zellatmung im Überblick",
                titleZH: "细胞呼吸总览",
                operatoren: ["nennen", "beschreiben", "darstellen"],
                klausurDE: "Wort-/Summen-Gleichung angeben (Ausblick-Niveau).",
                klausurZH: "总反应式题",
                leitfrageDE: "Woher kommt die Energie der Zelle?",
                leitfrageZH: "细胞的能量从哪里来？",
                noteKeywords: ["zellatmung", "glucose", "energie", "sauerstoff"],
                children: [],
              },
              {
                id: "bio/if1/energie-mikroskopie/fotosynthese",
                level: 3,
                code: "",
                titleDE: "Fotosynthese im Überblick",
                titleZH: "光合作用总览",
                operatoren: ["nennen", "beschreiben", "vergleichen"],
                klausurDE: "Fotosynthese vs. Zellatmung gegenüberstellen.",
                klausurZH: "对比题",
                leitfrageDE: "Wie hängen Fotosynthese und Atmung zusammen?",
                leitfrageZH: "光合与呼吸有什么关系？",
                noteKeywords: ["fotosynthese", "chloroplast", "lichtenergie", "vergleich"],
                children: [],
              },
              {
                id: "bio/if1/energie-mikroskopie/mikroskopieren",
                level: 3,
                code: "",
                titleDE: "Mikroskopieren",
                titleZH: "显微观察",
                operatoren: ["beschreiben", "auswerten", "durchführen"],
                klausurDE: "Präparat beschreiben, Strukturen identifizieren (Mikroskopbild).",
                klausurZH: "显微图像分析",
                leitfrageDE: "Wie findet man Zellen im Mikroskop?",
                leitfrageZH: "如何在显微镜下找到细胞？",
                noteKeywords: ["mikroskop", "praeparat", "beobachtung", "material"],
                children: [],
              },
              {
                id: "bio/if1/energie-mikroskopie/wissenschaftliches-zeichnen",
                level: 3,
                code: "",
                titleDE: "Wissenschaftliches Zeichnen",
                titleZH: "科学绘图",
                operatoren: ["darstellen", "beschriften", "bewerten"],
                klausurDE: "Zellzeichnung mit Regeln anfertigen (Darstellungsleistung).",
                klausurZH: "绘图+标注题",
                leitfrageDE: "Was macht eine gute Zellzeichnung aus?",
                leitfrageZH: "好的细胞绘图标准是什么？",
                noteKeywords: ["zeichnung", "beschriften", "darstellung", "mikroskopbild"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "bio/if-oekologie",
        level: 1,
        code: "IF 4",
        titleDE: "Oekologie und Populationsdynamik",
        titleZH: "生态学与种群动力学",
        operatoren: ["analysieren", "modellieren", "interpretieren"],
        klausurDE: "Oekologische Nische, intra- und interspezifische Konkurrenz, Lotka-Volterra und Populationswachstum auswerten.",
        klausurZH: "生态位、种群增长模型与生物间相互关系分析",
        leitfrageDE: "Wie regulieren sich Populationen im Oekosystem?",
        leitfrageZH: "种群在生态系统中如何自我调节？",
        noteKeywords: ["oekologie", "nische", "beziehungen", "populationsdynamik", "wachstumsmodelle", "varianten-training", "kapazitaetsgrenze", "bio ef oekologie training", "oekologische nische und beziehungen", "populationsdynamik und wachstumsmodelle"],
        children: []
      },
      {
        id: "bio/if-genetik",
        level: 1,
        code: "IF 3",
        titleDE: "Genetik und Molekularbiologie",
        titleZH: "遗传学与分子生物学",
        operatoren: ["anwenden", "darstellen", "ermitteln"],
        klausurDE: "Stammbaumanalyse, Kreuzungsschemata, DNA-Replikation und Proteinbiosynthese.",
        klausurZH: "系谱图分析、单双杂合遗传计算三步程序与中心法则",
        leitfrageDE: "Wie werden Erbinformationen weitergegeben und ausgepraegt?",
        leitfrageZH: "遗传信息如何传递与表达？",
        noteKeywords: ["genetik", "rechenschema", "kreuzungsschema", "stammbaum", "proteinbiosynthese", "transkription", "translation", "genetik-rechenschema", "cn-methode: genetik-rechenschema"],
        children: []
      },
      {
        id: "bio/if-neuro-evolution",
        level: 1,
        code: "IF 5",
        titleDE: "Neurobiologie, Hormone und Evolution",
        titleZH: "神经生物学、激素调节与进化论",
        operatoren: ["erklaeren", "beurteilen", "vergleichen"],
        klausurDE: "Rezeptorpotenzial, Stressachse (HPA) und synthetische Evolutionstheorie.",
        klausurZH: "感受器电位、应激反应激素调节与综合进化论变异选择",
        leitfrageDE: "Wie reagiert der Organismus auf Umwelt und wie veraendert er sich ueber Generationen?",
        leitfrageZH: "机体如何感知应激并在世代间进化？",
        noteKeywords: ["hormone", "stressreaktion", "sinneszellen", "rezeptorpotenzial", "evolution", "synthetische evolutionstheorie", "hormone und stressreaktion", "sinneszellen und rezeptorpotenzial"],
        children: []
      },
      {
        id: "bio/klausur-training",
        level: 1,
        code: "Pruefung",
        titleDE: "Klausur- und Abitur-Training, CN-Methoden",
        titleZH: "应试模考、真题训练与CN解题速查",
        operatoren: ["anwenden", "ueberpruefen"],
        klausurDE: "Original Klausur- und Abituraufgaben mit Erwartungshorizont, CN-Tricks und Formel-Spickzettel.",
        klausurZH: "官方真题、标准采分点、CN解题技巧与公式全览",
        leitfrageDE: "Wie erreicht man 14+ Notenpunkte in Bio?",
        leitfrageZH: "如何在生物考试中拿到 14+ 高分？",
        noteKeywords: ["abitur-aufgabentraining", "operatoren check", "cn bio training", "abitur", "cn begriffshandbuch", "cn tricks verfahren", "formel-spickzettel", "abitur-aufgabentraining 2026", "bio operatoren check"],
        children: []
      }
    ],
  },
};
