import type { FachBaum } from "./types";

export const chemieBaum: FachBaum = {
  fach: "Chemie",
  nameDE: "Chemie",
  nameZH: "化学",
  klpReferenz: "NRW KLP Chemie 2022",
  klausurFokusDE: "Strukturformel → Gleichung → Beobachtung/Deutung trennen; Basiskonzepte Donator-Akzeptor / Struktur-Eigenschaft / Energie",
  klausurFokusZH: "有机化学入门与反应速率/平衡；画结构式、写方程式是基本功，观察与解释分开写",
  root: {
    id: "chemie",
    level: 0,
    code: "",
    titleDE: "Chemie",
    titleZH: "化学",
    operatoren: [],
    klausurDE: "",
    klausurZH: "",
    leitfrageDE: "",
    leitfrageZH: "",
    noteKeywords: [],
    children: [
      {
        id: "chemie/if1",
        level: 1,
        code: "IF 1",
        titleDE: "Organische Stoffklassen",
        titleZH: "有机物类别",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "chemie/if1/kohlenwasserstoffe-gruppen",
            level: 2,
            code: "",
            titleDE: "Kohlenwasserstoffe und Gruppen",
            titleZH: "烃与官能团",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if1/kohlenwasserstoffe-gruppen/alkane",
                level: 3,
                code: "",
                titleDE: "Alkane",
                titleZH: "烷烃",
                operatoren: ["nennen", "darstellen", "beschreiben"],
                klausurDE: "Homologe Reihe darstellen, Eigenschaften beschreiben.",
                klausurZH: "画结构式基础题",
                leitfrageDE: "Wie ändern sich Eigenschaften in der homologen Reihe?",
                leitfrageZH: "同系物中性质如何变化？",
                noteKeywords: ["alkane", "homologe-reihe", "strukturformel"],
                children: [],
              },
              {
                id: "chemie/if1/kohlenwasserstoffe-gruppen/alkene-alkine",
                level: 3,
                code: "",
                titleDE: "Alkene und Alkine",
                titleZH: "烯烃与炔烃",
                operatoren: ["darstellen", "beschreiben", "erklären"],
                klausurDE: "Doppel-/Dreifachbindung zeichnen, Reaktivität erklären.",
                klausurZH: "结构→性质题",
                leitfrageDE: "Warum sind Mehrfachbindungen reaktiver?",
                leitfrageZH: "为什么多重键更活泼？",
                noteKeywords: ["alkene", "alkine", "doppelbindung", "reaktivitaet"],
                children: [],
              },
              {
                id: "chemie/if1/kohlenwasserstoffe-gruppen/funktionelle-gruppen",
                level: 3,
                code: "",
                titleDE: "Funktionelle Gruppen: Hydroxy, Carbonyl, Carboxy",
                titleZH: "官能团：羟基、羰基、羧基",
                operatoren: ["nennen", "zuordnen", "beschreiben"],
                klausurDE: "Gruppe erkennen, Stoffklasse zuordnen (AFB I).",
                klausurZH: "识别归类题",
                leitfrageDE: "Welche Gruppe bestimmt welche Stoffklasse?",
                leitfrageZH: "哪个官能团决定哪类物质？",
                noteKeywords: ["funktionelle-gruppen", "hydroxy", "carbonyl", "carboxy"],
                children: [],
              },
              {
                id: "chemie/if1/kohlenwasserstoffe-gruppen/struktur-eigenschaft",
                level: 3,
                code: "",
                titleDE: "Struktur-Eigenschaft",
                titleZH: "结构与性质的关系",
                operatoren: ["erklären", "begründen", "bewerten"],
                klausurDE: "Eigenschaft aus Struktur begründen (Basiskonzept!).",
                klausurZH: "解释评价题",
                leitfrageDE: "Wie erklärt die Struktur die Eigenschaft?",
                leitfrageZH: "结构如何解释性质？",
                noteKeywords: ["struktur-eigenschaft", "siedepunkt", "loeslichkeit"],
                children: [],
              },
            ],
          },
          {
            id: "chemie/if1/nomenklatur-isomerie",
            level: 2,
            code: "",
            titleDE: "Nomenklatur und Isomerie",
            titleZH: "命名与同分异构",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if1/nomenklatur-isomerie/nomenklatur",
                level: 3,
                code: "",
                titleDE: "Nomenklatur",
                titleZH: "命名法",
                operatoren: ["benennen", "darstellen", "bestimmen"],
                klausurDE: "Name und Strukturformel wechselseitig übersetzen.",
                klausurZH: "必考基本功",
                leitfrageDE: "Wie benennt man verzweigte Kohlenwasserstoffe?",
                leitfrageZH: "支链烃如何命名？",
                noteKeywords: ["nomenklatur", "strukturformel", "benennung"],
                children: [],
              },
              {
                id: "chemie/if1/nomenklatur-isomerie/konstitutionsisomerie",
                level: 3,
                code: "",
                titleDE: "Konstitutionsisomerie",
                titleZH: "碳架异构",
                operatoren: ["darstellen", "bestimmen", "begründen"],
                klausurDE: "Isomere zeichnen, Isomerie begründen.",
                klausurZH: "作图题",
                leitfrageDE: "Wie findet man alle Isomere einer Formel?",
                leitfrageZH: "如何找全一个分子式的异构体？",
                noteKeywords: ["isomerie", "konstitution", "strukturformel"],
                children: [],
              },
              {
                id: "chemie/if1/nomenklatur-isomerie/strukturformeln",
                level: 3,
                code: "",
                titleDE: "Strukturformeln zeichnen",
                titleZH: "结构式画法",
                operatoren: ["darstellen", "angeben", "zuordnen"],
                klausurDE: "Korrekte Strukturformel zeichnen (Darstellungsleistung).",
                klausurZH: "全卷基本功",
                leitfrageDE: "Welche Darstellungsform passt zur Aufgabe?",
                leitfrageZH: "哪种结构式写法适合这道题？",
                noteKeywords: ["strukturformel", "skelettformel", "darstellung"],
                children: [],
              },
            ],
          },
          {
            id: "chemie/if1/reaktionstypen",
            level: 2,
            code: "",
            titleDE: "Reaktionstypen",
            titleZH: "反应类型",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if1/reaktionstypen/substitution",
                level: 3,
                code: "",
                titleDE: "Substitution",
                titleZH: "取代反应",
                operatoren: ["beschreiben", "darstellen", "erklären"],
                klausurDE: "Substitution als Reaktionsgleichung formulieren.",
                klausurZH: "方程式题",
                leitfrageDE: "Wie läuft eine Substitution ab?",
                leitfrageZH: "取代反应如何进行？",
                noteKeywords: ["substitution", "radikal", "halogen"],
                children: [],
              },
              {
                id: "chemie/if1/reaktionstypen/addition",
                level: 3,
                code: "",
                titleDE: "Addition",
                titleZH: "加成反应",
                operatoren: ["darstellen", "erklären", "begründen"],
                klausurDE: "Additionsprodukt vorhersagen und begründen.",
                klausurZH: "预测产物题",
                leitfrageDE: "Wohin addiert sich was bei asymmetrischen Alkenen?",
                leitfrageZH: "不对称烯烃加成时谁加到哪边？",
                noteKeywords: ["addition", "markownikow", "alken"],
                children: [],
              },
              {
                id: "chemie/if1/reaktionstypen/eliminierung",
                level: 3,
                code: "",
                titleDE: "Eliminierung",
                titleZH: "消去反应",
                operatoren: ["darstellen", "beschreiben", "vergleichen"],
                klausurDE: "Addition vs. Eliminierung gegenüberstellen.",
                klausurZH: "对比题",
                leitfrageDE: "Wann läuft Addition, wann Eliminierung?",
                leitfrageZH: "何时加成、何时消去？",
                noteKeywords: ["eliminierung", "addition", "alken"],
                children: [],
              },
            ],
          },
          {
            id: "chemie/if1/erdoel-nachhaltigkeit",
            level: 2,
            code: "",
            titleDE: "Kontext Erdöl und Nachhaltigkeit",
            titleZH: "石油背景与可持续",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if1/erdoel-nachhaltigkeit/erdoel-erdgas",
                level: 3,
                code: "",
                titleDE: "Erdöl und Erdgas",
                titleZH: "石油与天然气",
                operatoren: ["beschreiben", "nennen", "erklären"],
                klausurDE: "Fraktionierung/Cracken beschreiben.",
                klausurZH: "背景材料题",
                leitfrageDE: "Wie wird aus Erdöl ein Rohstoff?",
                leitfrageZH: "石油如何变成化工原料？",
                noteKeywords: ["erdoel", "erdgas", "fraktionierung", "cracken"],
                children: [],
              },
              {
                id: "chemie/if1/erdoel-nachhaltigkeit/verbrennung",
                level: 3,
                code: "",
                titleDE: "Verbrennung",
                titleZH: "燃烧",
                operatoren: ["darstellen", "berechnen", "bewerten"],
                klausurDE: "Verbrennungsgleichung aufstellen, CO2-Aspekt bewerten.",
                klausurZH: "方程式+评价",
                leitfrageDE: "Was entsteht bei vollständiger Verbrennung?",
                leitfrageZH: "完全燃烧生成什么？",
                noteKeywords: ["verbrennung", "brennstoff", "co2-bilanz"],
                children: [],
              },
              {
                id: "chemie/if1/erdoel-nachhaltigkeit/bewertung-nachhaltigkeit",
                level: 3,
                code: "",
                titleDE: "Bewertung und Nachhaltigkeit",
                titleZH: "可持续性评价",
                operatoren: ["bewerten", "beurteilen", "begründen"],
                klausurDE: "Nutzung fossiler Rohstoffe kriteriengeleitet bewerten.",
                klausurZH: "评价题 AFB III",
                leitfrageDE: "Wie bewertet man Rohstoffnutzung nachhaltig?",
                leitfrageZH: "如何可持续地评价原料使用？",
                noteKeywords: ["nachhaltigkeit", "bewertung", "rohstoff"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "chemie/if2",
        level: 1,
        code: "IF 2",
        titleDE: "Reaktionsgeschwindigkeit und chemisches Gleichgewicht",
        titleZH: "反应速率与化学平衡",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "chemie/if2/kollisionstheorie",
            level: 2,
            code: "",
            titleDE: "Kollisionstheorie",
            titleZH: "碰撞理论",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if2/kollisionstheorie/teilchenmodell",
                level: 3,
                code: "",
                titleDE: "Teilchenmodell",
                titleZH: "粒子模型",
                operatoren: ["beschreiben", "erklären", "darstellen"],
                klausurDE: "Geschwindigkeit mit Teilchenstößen erklären.",
                klausurZH: "解释题",
                leitfrageDE: "Wann ist ein Stoß wirksam?",
                leitfrageZH: "碰撞何时有效？",
                noteKeywords: ["teilchenmodell", "kollision", "stoss"],
                children: [],
              },
              {
                id: "chemie/if2/kollisionstheorie/aktivierung",
                level: 3,
                code: "",
                titleDE: "Aktivierung",
                titleZH: "活化",
                operatoren: ["beschreiben", "erklären", "darstellen"],
                klausurDE: "Aktivierungsenergie im Diagramm zeigen.",
                klausurZH: "能量图题",
                leitfrageDE: "Was bedeutet Aktivierungsenergie?",
                leitfrageZH: "活化能是什么意思？",
                noteKeywords: ["aktivierung", "aktivierungsenergie", "energieprofil"],
                children: [],
              },
              {
                id: "chemie/if2/kollisionstheorie/energieprofil",
                level: 3,
                code: "",
                titleDE: "Energieprofil",
                titleZH: "能量曲线",
                operatoren: ["darstellen", "deuten", "erklären"],
                klausurDE: "Energiediagramm zeichnen und deuten.",
                klausurZH: "图像解读",
                leitfrageDE: "Was liest man aus dem Energieprofil ab?",
                leitfrageZH: "能量曲线能读出什么？",
                noteKeywords: ["energieprofil", "aktivierungsenergie", "katalysator", "exotherm"],
                children: [],
              },
            ],
          },
          {
            id: "chemie/if2/einflussgroessen",
            level: 2,
            code: "",
            titleDE: "Einflussgrößen",
            titleZH: "影响因素",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if2/einflussgroessen/konzentration",
                level: 3,
                code: "",
                titleDE: "Konzentration",
                titleZH: "浓度",
                operatoren: ["beschreiben", "auswerten", "begründen"],
                klausurDE: "Konzentrationseinfluss aus Messdaten belegen.",
                klausurZH: "实验分析",
                leitfrageDE: "Warum beschleunigt höhere Konzentration?",
                leitfrageZH: "为什么浓度越高反应越快？",
                noteKeywords: ["konzentration", "geschwindigkeit", "messdaten"],
                children: [],
              },
              {
                id: "chemie/if2/einflussgroessen/temperatur",
                level: 3,
                code: "",
                titleDE: "Temperatur",
                titleZH: "温度",
                operatoren: ["erklären", "auswerten", "begründen"],
                klausurDE: "Temperaturversuch auswerten, RGT-Regel anwenden.",
                klausurZH: "对比实验题",
                leitfrageDE: "Warum wirkt Temperatur so stark?",
                leitfrageZH: "为什么温度影响这么大？",
                noteKeywords: ["temperatur", "rgt-regel", "geschwindigkeit"],
                children: [],
              },
              {
                id: "chemie/if2/einflussgroessen/oberflaeche-katalysator",
                level: 3,
                code: "",
                titleDE: "Oberfläche und Katalysator",
                titleZH: "接触面与催化剂",
                operatoren: ["beschreiben", "erklären", "bewerten"],
                klausurDE: "Katalysatorwirkung erklären, Einsatz bewerten.",
                klausurZH: "实验+评价",
                leitfrageDE: "Was ändert ein Katalysator — und was nicht?",
                leitfrageZH: "催化剂改变什么、不改变什么？",
                noteKeywords: ["oberflaeche", "katalysator", "aktivierungsenergie"],
                children: [],
              },
            ],
          },
          {
            id: "chemie/if2/gleichgewicht-mwg",
            level: 2,
            code: "",
            titleDE: "Gleichgewicht und MWG",
            titleZH: "平衡与质量作用定律",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if2/gleichgewicht-mwg/dynamisches-gleichgewicht",
                level: 3,
                code: "",
                titleDE: "Dynamisches Gleichgewicht",
                titleZH: "动态平衡",
                operatoren: ["beschreiben", "erklären", "darstellen"],
                klausurDE: "Dynamisch vs. statisch unterscheiden (AFB I–II).",
                klausurZH: "概念题",
                leitfrageDE: "Warum heißt es dynamisches Gleichgewicht?",
                leitfrageZH: "为什么叫动态平衡？",
                noteKeywords: ["gleichgewicht", "dynamisch", "hin-rueckreaktion"],
                children: [],
              },
              {
                id: "chemie/if2/gleichgewicht-mwg/massenwirkungsgesetz",
                level: 3,
                code: "",
                titleDE: "Massenwirkungsgesetz",
                titleZH: "质量作用定律",
                operatoren: ["angeben", "berechnen", "begründen"],
                klausurDE: "MWG aufstellen, K berechnen.",
                klausurZH: "计算题",
                leitfrageDE: "Wie stellt man das MWG auf?",
                leitfrageZH: "质量作用定律表达式怎么写？",
                noteKeywords: ["massenwirkungsgesetz", "gleichgewichtskonstante", "kc"],
                children: [],
              },
              {
                id: "chemie/if2/gleichgewicht-mwg/gleichgewichtskonstante",
                level: 3,
                code: "",
                titleDE: "Gleichgewichtskonstante",
                titleZH: "平衡常数",
                operatoren: ["deuten", "berechnen", "begründen"],
                klausurDE: "Aus K die Lage des Gleichgewichts deuten.",
                klausurZH: "判断题",
                leitfrageDE: "Was verrät K über die Lage?",
                leitfrageZH: "K 说明平衡位置的什么？",
                noteKeywords: ["gleichgewichtskonstante", "gleichgewicht", "konzentration"],
                children: [],
              },
            ],
          },
          {
            id: "chemie/if2/le-chatelier-diagramme",
            level: 2,
            code: "",
            titleDE: "Le Chatelier und Diagramme",
            titleZH: "勒夏特列与图像",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "chemie/if2/le-chatelier-diagramme/le-chatelier",
                level: 3,
                code: "",
                titleDE: "Le Chatelier",
                titleZH: "勒夏特列原理",
                operatoren: ["erklären", "vorhersagen", "begründen"],
                klausurDE: "Störung und Verschiebung vorhersagen und begründen.",
                klausurZH: "预判题",
                leitfrageDE: "Wohin weicht das Gleichgewicht aus?",
                leitfrageZH: "平衡往哪个方向移动？",
                noteKeywords: ["le-chatelier", "stoerung", "verschiebung"],
                children: [],
              },
              {
                id: "chemie/if2/le-chatelier-diagramme/diagramm-auswertung",
                level: 3,
                code: "",
                titleDE: "Diagramm-Auswertung",
                titleZH: "浓度—时间图像分析",
                operatoren: ["auswerten", "deuten", "darstellen"],
                klausurDE: "c-t-Diagramm deuten (Experiment-Auswertung).",
                klausurZH: "实验分析必考",
                leitfrageDE: "Was zeigt der Knick im Diagramm?",
                leitfrageZH: "图像中的折点说明什么？",
                noteKeywords: ["diagramm", "konzentration", "zeitverlauf", "gleichgewicht"],
                children: [],
              },
              {
                id: "chemie/if2/le-chatelier-diagramme/technische-anwendung",
                level: 3,
                code: "",
                titleDE: "Technische Anwendung",
                titleZH: "工业应用",
                operatoren: ["bewerten", "begründen", "erklären"],
                klausurDE: "Reaktionsbedingungen technisch-ökologisch bewerten.",
                klausurZH: "综合评价 AFB III",
                leitfrageDE: "Schnell oder vollständig — was zählt technisch?",
                leitfrageZH: "工业上要快还是要全？",
                noteKeywords: ["technik", "ausbeute", "geschwindigkeit", "oekologie"],
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
};
