import type { FachBaum } from "./types";
export const deutschBaum: FachBaum = { fach: "Deutsch", nameDE: "Deutsch", nameZH: "德语", klpReferenz: "NRW KLP Deutsch 2023, vier Inhaltsfelder EF", klausurFokusDE: "Drama-Ganzschrift und pragmatische Texte als Schwerpunkt, Aufgabenarten I-IV mit AFB-II-Fokus", klausurFokusZH: "戏剧整本加实用文分析为重点,考试锚定任务类型 I-IV 与 AFB II", root: { id: "deutsch", level: 0, code: "", titleDE: "Deutsch", titleZH: "德语", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if1", level: 1, code: "IF 1", titleDE: "Sprache", titleZH: "语言", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if1/sprachebenen", level: 2, code: "", titleDE: "Sprachebenen", titleZH: "语言层面", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if1/sprachebenen/phonologie", level: 3, code: "", titleDE: "Phonologie", titleZH: "语音", operatoren: ["untersuchen", "analysieren"], klausurDE: "Aufgabenart I-II, AFB I-II, Analyse-Baustein Sprache", klausurZH: "任务类型 I-II,AFB I-II,语言分析模块", leitfrageDE: "Welche Lautmittel praegen den Ton?", leitfrageZH: "哪些语音手段塑造了语气?", noteKeywords: ["phonologie", "lautmittel", "sprachebene"], children: [] },
{ id: "deutsch/if1/sprachebenen/morphologie-syntax", level: 3, code: "", titleDE: "Morphologie-Syntax", titleZH: "词法句法", operatoren: ["untersuchen", "analysieren"], klausurDE: "Aufgabenart I-II, AFB II Schwerpunkt, Analyse-Baustein Form", klausurZH: "任务类型 I-II,AFB II 重点,形式分析模块", leitfrageDE: "Was leistet der Satzbau fuer die Wirkung?", leitfrageZH: "句式为表达效果起什么作用?", noteKeywords: ["morphologie", "syntax", "satzbau"], children: [] },
{ id: "deutsch/if1/sprachebenen/semantik-pragmatik", level: 3, code: "", titleDE: "Semantik-Pragmatik", titleZH: "语义语用", operatoren: ["analysieren", "deuten"], klausurDE: "Aufgabenart II, AFB II-III, Uebergang Analyse zu Deutung", klausurZH: "任务类型 II,AFB II-III,由分析到阐释过渡", leitfrageDE: "Was bedeutet die Wortwahl im Kontext?", leitfrageZH: "词语选择在语境中意味着什么?", noteKeywords: ["semantik", "pragmatik", "wortwahl"], children: [] }
] },
{ id: "deutsch/if1/sprachvarietaeten", level: 2, code: "", titleDE: "Sprachvarietaeten", titleZH: "语言变体", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if1/sprachvarietaeten/distinktion", level: 3, code: "", titleDE: "Distinktion", titleZH: "区分功能", operatoren: ["darstellen", "untersuchen"], klausurDE: "Aufgabenart III, AFB I-II, Erklaerungs-Baustein", klausurZH: "任务类型 III,AFB I-II,解释模块", leitfrageDE: "Wovon grenzt sich die Varietaet ab?", leitfrageZH: "该变体与什么划清界限?", noteKeywords: ["varietaet", "distinktion", "abgrenzung"], children: [] },
{ id: "deutsch/if1/sprachvarietaeten/identitaet", level: 3, code: "", titleDE: "Identitaet", titleZH: "身份功能", operatoren: ["untersuchen", "erörtern"], klausurDE: "Aufgabenart III-IV, AFB II-III, Erörterungs-Anschluss", klausurZH: "任务类型 III-IV,AFB II-III,议论衔接", leitfrageDE: "Welche Zugehoerigkeit zeigt die Sprache?", leitfrageZH: "语言显示了何种归属?", noteKeywords: ["varietaet", "identitaet", "zugehoerigkeit"], children: [] },
{ id: "deutsch/if1/sprachvarietaeten/varietaetenvergleich", level: 3, code: "", titleDE: "Varietaetenvergleich", titleZH: "变体比较", operatoren: ["untersuchen", "vergleichen"], klausurDE: "Aufgabenart I-II, AFB II, Vergleichs-Baustein", klausurZH: "任务类型 I-II,AFB II,比较模块", leitfrageDE: "Wo unterscheiden sich die Varietaeten?", leitfrageZH: "变体之间区别在哪里?", noteKeywords: ["varietaetenvergleich", "vergleich", "varietaet"], children: [] }
] },
{ id: "deutsch/if1/muendlichkeit-schriftlichkeit", level: 2, code: "", titleDE: "Muendlichkeit vs Schriftlichkeit", titleZH: "口语与书面语", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if1/muendlichkeit-schriftlichkeit/merkmale-muendlichkeit", level: 3, code: "", titleDE: "Merkmale Muendlichkeit", titleZH: "口语特征", operatoren: ["darstellen", "analysieren"], klausurDE: "Aufgabenart I-II, AFB I-II, Drama-Dialog-Brücke", klausurZH: "任务类型 I-II,AFB I-II,戏剧对白衔接", leitfrageDE: "Was macht den Text muendlich?", leitfrageZH: "什么使文本具有口语性?", noteKeywords: ["muendlichkeit", "dialog", "alltagssprache"], children: [] },
{ id: "deutsch/if1/muendlichkeit-schriftlichkeit/merkmale-schriftlichkeit", level: 3, code: "", titleDE: "Merkmale Schriftlichkeit", titleZH: "书面语特征", operatoren: ["darstellen", "analysieren"], klausurDE: "Aufgabenart I-II, AFB I-II, Sachtext-Brücke", klausurZH: "任务类型 I-II,AFB I-II,实用文衔接", leitfrageDE: "Was macht den Text schriftlich?", leitfrageZH: "什么使文本具有书面语性?", noteKeywords: ["schriftlichkeit", "sachtext", "norm"], children: [] },
{ id: "deutsch/if1/muendlichkeit-schriftlichkeit/gegenwartssprache-transfer", level: 3, code: "", titleDE: "Gegenwartssprache-Transfer", titleZH: "当代语言迁移", operatoren: ["untersuchen", "Stellung nehmen"], klausurDE: "Aufgabenart IV, AFB III, Stellungnahme-Schluss", klausurZH: "任务类型 IV,AFB III,立场表态结尾", leitfrageDE: "Wie zeigt sich der Wandel heute?", leitfrageZH: "这种变化今天如何体现?", noteKeywords: ["gegenwartssprache", "transfer", "stellungnahme"], children: [] }
] }
] },
{ id: "deutsch/if2", level: 1, code: "IF 2", titleDE: "Texte", titleZH: "文本", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if2/drama-ganzschrift", level: 2, code: "", titleDE: "Drama-Ganzschrift", titleZH: "戏剧整本", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if2/drama-ganzschrift/figur", level: 3, code: "", titleDE: "Figur", titleZH: "人物", operatoren: ["analysieren", "interpretieren"], klausurDE: "Aufgabenart I, AFB II Schwerpunkt, Ganzschrift-Aufgabe", klausurZH: "任务类型 I,AFB II 重点,整本任务", leitfrageDE: "Was treibt die Figur an?", leitfrageZH: "什么驱动着这个人物?", noteKeywords: ["drama", "figurenkonstellation", "figur"], children: [] },
{ id: "deutsch/if2/drama-ganzschrift/handlung", level: 3, code: "", titleDE: "Handlung", titleZH: "情节", operatoren: ["untersuchen", "analysieren"], klausurDE: "Aufgabenart I, AFB I-II, Aufbau-Baustein", klausurZH: "任务类型 I,AFB I-II,结构模块", leitfrageDE: "Wo kippt der Konflikt?", leitfrageZH: "冲突在哪里反转?", noteKeywords: ["drama", "peripetie", "szenenanalyse"], children: [] },
{ id: "deutsch/if2/drama-ganzschrift/dialog", level: 3, code: "", titleDE: "Dialog", titleZH: "对白", operatoren: ["analysieren", "deuten"], klausurDE: "Aufgabenart I-II, AFB II, Dialog-Analyse mit Beleg und Zeile", klausurZH: "任务类型 I-II,AFB II,对白分析带引证与行号", leitfrageDE: "Wer steuert das Gespraech?", leitfrageZH: "谁主导了这场谈话?", noteKeywords: ["dialog", "szenenanalyse", "gespraechsstrategie"], children: [] },
{ id: "deutsch/if2/drama-ganzschrift/historischer-kontext", level: 3, code: "", titleDE: "Historischer Kontext", titleZH: "历史语境", operatoren: ["einordnen", "interpretieren"], klausurDE: "Aufgabenart I, AFB II-III, Kontext-Deutung", klausurZH: "任务类型 I,AFB II-III,语境阐释", leitfrageDE: "Was sagt das Stueck seiner Zeit?", leitfrageZH: "这部剧对它所处的时代说了什么?", noteKeywords: ["drama", "epochenreflexion", "kontext"], children: [] }
] },
{ id: "deutsch/if2/erzaehltexte", level: 2, code: "", titleDE: "Erzaehltexte", titleZH: "叙事文本", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if2/erzaehltexte/erzaehlperspektive", level: 3, code: "", titleDE: "Erzaehlperspektive", titleZH: "叙述视角", operatoren: ["untersuchen", "analysieren"], klausurDE: "Aufgabenart I-II, AFB II, Erzaehlanalyse-Baustein", klausurZH: "任务类型 I-II,AFB II,叙事分析模块", leitfrageDE: "Wer sieht und wer spricht?", leitfrageZH: "谁在看、谁在说?", noteKeywords: ["erzaehlperspektive", "erzaehler", "perspektive"], children: [] },
{ id: "deutsch/if2/erzaehltexte/zeitgestaltung", level: 3, code: "", titleDE: "Zeitgestaltung", titleZH: "时间结构", operatoren: ["untersuchen", "deuten"], klausurDE: "Aufgabenart I-II, AFB II, Aufbau-Baustein", klausurZH: "任务类型 I-II,AFB II,结构模块", leitfrageDE: "Warum wird hier gerafft oder gedehnt?", leitfrageZH: "这里为何加速或延宕?", noteKeywords: ["zeitgestaltung", "raffung", "dehnung"], children: [] },
{ id: "deutsch/if2/erzaehltexte/figuren-raum", level: 3, code: "", titleDE: "Figuren-Raum", titleZH: "人物与空间", operatoren: ["analysieren", "interpretieren"], klausurDE: "Aufgabenart I, AFB II-III, Deutungs-Baustein", klausurZH: "任务类型 I,AFB II-III,阐释模块", leitfrageDE: "Was spiegelt der Raum?", leitfrageZH: "空间映照了什么?", noteKeywords: ["figurenkonstellation", "raum", "deutungshypothese"], children: [] }
] },
{ id: "deutsch/if2/lyrik", level: 2, code: "", titleDE: "Lyrik", titleZH: "诗歌", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if2/lyrik/form-metrum", level: 3, code: "", titleDE: "Form-Metrum", titleZH: "形式格律", operatoren: ["untersuchen", "analysieren"], klausurDE: "Aufgabenart I, AFB I-II, Lyrik-Analyse Einstieg", klausurZH: "任务类型 I,AFB I-II,诗歌分析入门", leitfrageDE: "Was traegt die Form zum Gefuehl bei?", leitfrageZH: "形式为情感贡献了什么?", noteKeywords: ["lyrik", "metrum", "reim"], children: [] },
{ id: "deutsch/if2/lyrik/bildsprache", level: 3, code: "", titleDE: "Bildsprache", titleZH: "意象语言", operatoren: ["analysieren", "deuten"], klausurDE: "Aufgabenart I, AFB II Schwerpunkt, Bild-Deutung mit Beleg", klausurZH: "任务类型 I,AFB II 重点,意象阐释带引证", leitfrageDE: "Wofuer steht das Bild?", leitfrageZH: "这个意象代表什么?", noteKeywords: ["lyrik", "bildsprache", "deutungshypothese"], children: [] },
{ id: "deutsch/if2/lyrik/klang-strophe", level: 3, code: "", titleDE: "Klang-Strophe", titleZH: "音韵诗节", operatoren: ["untersuchen", "interpretieren"], klausurDE: "Aufgabenart I, AFB II, Klang- und Aufbau-Baustein", klausurZH: "任务类型 I,AFB II,音韵与结构模块", leitfrageDE: "Wie fuehrt der Klang durchs Gedicht?", leitfrageZH: "音韵如何引导全诗?", noteKeywords: ["lyrik", "klang", "strophe"], children: [] }
] },
{ id: "deutsch/if2/pragmatische-texte", level: 2, code: "", titleDE: "Pragmatische Texte", titleZH: "实用文", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if2/pragmatische-texte/textsorte", level: 3, code: "", titleDE: "Textsorte", titleZH: "文类", operatoren: ["untersuchen", "analysieren"], klausurDE: "Aufgabenart II-III, AFB I, Einleitungs-Baustein Textsorte", klausurZH: "任务类型 II-III,AFB I,文类导入模块", leitfrageDE: "Welche Textsorte liegt vor?", leitfrageZH: "这是什么文类?", noteKeywords: ["sachtext", "textsorte", "sachtextanalyse"], children: [] },
{ id: "deutsch/if2/pragmatische-texte/argumentationsgang", level: 3, code: "", titleDE: "Argumentationsgang", titleZH: "论证思路", operatoren: ["analysieren", "untersuchen"], klausurDE: "Aufgabenart II, AFB II Schwerpunkt, Analyse-Kern mit Beleg und Zeile", klausurZH: "任务类型 II,AFB II 重点,分析核心带引证与行号", leitfrageDE: "Wie wird die These gestuetzt?", leitfrageZH: "论点如何被支撑?", noteKeywords: ["sachtext", "argumentation", "dreischritt"], children: [] },
{ id: "deutsch/if2/pragmatische-texte/leserlenkung", level: 3, code: "", titleDE: "Leserlenkung", titleZH: "读者引导", operatoren: ["analysieren", "deuten"], klausurDE: "Aufgabenart II, AFB II, Sprache-Wirkung-Baustein", klausurZH: "任务类型 II,AFB II,语言效果模块", leitfrageDE: "Wie lenkt der Text die Lesenden?", leitfrageZH: "文本如何引导读者?", noteKeywords: ["sachtext", "leserlenkung", "rhetorik"], children: [] },
{ id: "deutsch/if2/pragmatische-texte/intention", level: 3, code: "", titleDE: "Intention", titleZH: "写作意图", operatoren: ["deuten", "erörtern"], klausurDE: "Aufgabenart II-III, AFB II-III, Uebergang zu Erörterung", klausurZH: "任务类型 II-III,AFB II-III,向议论过渡", leitfrageDE: "Was will der Text bewirken?", leitfrageZH: "文本想达到什么效果?", noteKeywords: ["sachtext", "intention", "eroerterung"], children: [] }
] },
{ id: "deutsch/if2/themenzusammenhang", level: 2, code: "", titleDE: "Themenzusammenhang", titleZH: "主题关联比较", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if2/themenzusammenhang/motivvergleich", level: 3, code: "", titleDE: "Motivvergleich", titleZH: "母题比较", operatoren: ["untersuchen", "interpretieren"], klausurDE: "Aufgabenart I-II, AFB II-III, Vergleichs-Baustein", klausurZH: "任务类型 I-II,AFB II-III,比较模块", leitfrageDE: "Was bleibt gleich, was wandelt sich?", leitfrageZH: "什么不变、什么变了?", noteKeywords: ["motivvergleich", "gedichtvergleich", "vergleich"], children: [] },
{ id: "deutsch/if2/themenzusammenhang/textvergleich", level: 3, code: "", titleDE: "Textvergleich", titleZH: "文本比较", operatoren: ["analysieren", "erörtern"], klausurDE: "Aufgabenart II-III, AFB III, Erörterungs-Baustein", klausurZH: "任务类型 II-III,AFB III,议论模块", leitfrageDE: "Welcher Text ueberzeugt und warum?", leitfrageZH: "哪篇文本更有说服力,为什么?", noteKeywords: ["textvergleich", "vergleich", "eroerterung"], children: [] }
] }
] },
{ id: "deutsch/if3", level: 1, code: "IF 3", titleDE: "Kommunikation", titleZH: "沟通", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if3/kommunikationsmodelle", level: 2, code: "", titleDE: "Kommunikationsmodelle", titleZH: "沟通模型", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if3/kommunikationsmodelle/sender-empfaenger", level: 3, code: "", titleDE: "Sender-Empfaenger", titleZH: "发送接受模型", operatoren: ["darstellen", "untersuchen"], klausurDE: "Aufgabenart III, AFB I-II, Modell-Baustein", klausurZH: "任务类型 III,AFB I-II,模型模块", leitfrageDE: "Wer kommuniziert was unter welchen Bedingungen?", leitfrageZH: "谁在什么条件下沟通了什么?", noteKeywords: ["sender-empfaenger", "modell", "kommunikation"], children: [] },
{ id: "deutsch/if3/kommunikationsmodelle/stoerung-missverstehen", level: 3, code: "", titleDE: "Stoerung-Missverstehen", titleZH: "干扰与误解", operatoren: ["untersuchen", "erörtern"], klausurDE: "Aufgabenart III, AFB II-III, Stoerungs-Analyse", klausurZH: "任务类型 III,AFB II-III,干扰分析", leitfrageDE: "Wo scheitert die Verstaendigung?", leitfrageZH: "理解在哪里失败?", noteKeywords: ["stoerung", "missverstehen", "eroerterung"], children: [] }
] },
{ id: "deutsch/if3/monologisch-dialogisch", level: 2, code: "", titleDE: "Monologisch vs dialogisch", titleZH: "独白与对话", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if3/monologisch-dialogisch/monolog-analyse", level: 3, code: "", titleDE: "Monolog-Analyse", titleZH: "独白分析", operatoren: ["analysieren", "deuten"], klausurDE: "Aufgabenart I, AFB II, Drama-Brücke Monolog", klausurZH: "任务类型 I,AFB II,戏剧独白衔接", leitfrageDE: "Was klaert der Monolog?", leitfrageZH: "独白澄清了什么?", noteKeywords: ["drama", "monolog", "dialog"], children: [] },
{ id: "deutsch/if3/monologisch-dialogisch/dialog-analyse", level: 3, code: "", titleDE: "Dialog-Analyse", titleZH: "对话分析", operatoren: ["analysieren", "untersuchen"], klausurDE: "Aufgabenart I-III, AFB II Schwerpunkt, Dialog-Kern mit Beleg", klausurZH: "任务类型 I-III,AFB II 重点,对话核心带引证", leitfrageDE: "Wie veraendert der Dialog die Lage?", leitfrageZH: "对话如何改变局势?", noteKeywords: ["dialog", "szenenanalyse", "beleg"], children: [] },
{ id: "deutsch/if3/monologisch-dialogisch/gespraechsstrategien", level: 3, code: "", titleDE: "Gespraechsstrategien", titleZH: "谈话策略", operatoren: ["untersuchen", "Stellung nehmen"], klausurDE: "Aufgabenart III-IV, AFB III, Bewertungs-Schluss", klausurZH: "任务类型 III-IV,AFB III,评价结尾", leitfrageDE: "Welche Strategie wirkt und warum?", leitfrageZH: "哪种策略有效,为什么?", noteKeywords: ["gespraechsstrategie", "dialog", "stellungnahme"], children: [] }
] },
{ id: "deutsch/if3/alltag-literarisch", level: 2, code: "", titleDE: "Alltag vs literarisch", titleZH: "日常与文学沟通", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if3/alltag-literarisch/alltagsgespraech", level: 3, code: "", titleDE: "Alltagsgespraech", titleZH: "日常谈话", operatoren: ["darstellen", "untersuchen"], klausurDE: "Aufgabenart III, AFB I-II, Alltags-Baustein", klausurZH: "任务类型 III,AFB I-II,日常谈话模块", leitfrageDE: "Was kennzeichnet das Alltagsgespraech?", leitfrageZH: "日常谈话的特征是什么?", noteKeywords: ["alltagsgespraech", "muendlichkeit", "dialog"], children: [] },
{ id: "deutsch/if3/alltag-literarisch/literarischer-dialog", level: 3, code: "", titleDE: "Literarischer Dialog", titleZH: "文学对话", operatoren: ["analysieren", "interpretieren"], klausurDE: "Aufgabenart I, AFB II-III, Literatur-Brücke", klausurZH: "任务类型 I,AFB II-III,文学衔接", leitfrageDE: "Was gestaltet der Dialog kuenstlerisch?", leitfrageZH: "对话在艺术上塑造了什么?", noteKeywords: ["drama", "dialog", "literarischer-dialog"], children: [] }
] }
] },
{ id: "deutsch/if4", level: 1, code: "IF 4", titleDE: "Medien", titleZH: "媒体", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if4/geltungsansprueche", level: 2, code: "", titleDE: "Geltungsansprueche", titleZH: "有效性要求", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if4/geltungsansprueche/fakt-meinung", level: 3, code: "", titleDE: "Fakt-Meinung", titleZH: "事实与观点", operatoren: ["untersuchen", "analysieren"], klausurDE: "Aufgabenart II, AFB I-II, Sachtext-Brücke", klausurZH: "任务类型 II,AFB I-II,实用文衔接", leitfrageDE: "Was ist belegbar, was ist Meinung?", leitfrageZH: "什么是可证实的,什么是观点?", noteKeywords: ["sachtext", "fakt", "meinung"], children: [] },
{ id: "deutsch/if4/geltungsansprueche/quellenpruefung", level: 3, code: "", titleDE: "Quellenpruefung", titleZH: "来源核查", operatoren: ["untersuchen", "Stellung nehmen"], klausurDE: "Aufgabenart II-IV, AFB III, Pruef- und Stellungnahme-Baustein", klausurZH: "任务类型 II-IV,AFB III,核查与表态模块", leitfrageDE: "Hält die Quelle der Pruefung stand?", leitfrageZH: "来源经得起核查吗?", noteKeywords: ["quellenpruefung", "stellungnahme", "wuerdigung"], children: [] }
] },
{ id: "deutsch/if4/partizipation", level: 2, code: "", titleDE: "Partizipation", titleZH: "参与", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if4/partizipation/generieren-teilen", level: 3, code: "", titleDE: "Generieren-Teilen", titleZH: "生产与分享", operatoren: ["darstellen", "untersuchen"], klausurDE: "Aufgabenart III-IV, AFB I-II, Mediennutzungs-Baustein", klausurZH: "任务类型 III-IV,AFB I-II,媒体使用模块", leitfrageDE: "Wie verbreitet sich der Inhalt?", leitfrageZH: "内容如何传播?", noteKeywords: ["partizipation", "teilen", "medien"], children: [] },
{ id: "deutsch/if4/partizipation/kommentieren-verantwortung", level: 3, code: "", titleDE: "Kommentieren-Verantwortung", titleZH: "评论与责任", operatoren: ["erörtern", "verfassen"], klausurDE: "Aufgabenart III-IV, AFB III, Erörterung oder Kommentar verfassen", klausurZH: "任务类型 III-IV,AFB III,议论或评论写作", leitfrageDE: "Wo endet freie Meinungsaeusserung?", leitfrageZH: "言论自由止于何处?", noteKeywords: ["kommentar", "verantwortung", "eroerterung"], children: [] }
] },
{ id: "deutsch/if4/multimodalitaet", level: 2, code: "", titleDE: "Multimodalitaet", titleZH: "多模态", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "deutsch/if4/multimodalitaet/bild-text", level: 3, code: "", titleDE: "Bild-Text", titleZH: "图与文", operatoren: ["analysieren", "deuten"], klausurDE: "Aufgabenart II, AFB II, Bild-Text-Analyse", klausurZH: "任务类型 II,AFB II,图文分析", leitfrageDE: "Was zeigt das Bild, was der Text verschweigt?", leitfrageZH: "图显示了什么文没有说?", noteKeywords: ["bild-text", "multimodal", "sachtext"], children: [] },
{ id: "deutsch/if4/multimodalitaet/ton-film", level: 3, code: "", titleDE: "Ton-Film", titleZH: "声音与影像", operatoren: ["untersuchen", "interpretieren"], klausurDE: "Aufgabenart II, AFB II-III, Film-Ton-Baustein", klausurZH: "任务类型 II,AFB II-III,影视声音模块", leitfrageDE: "Wie steuert der Ton den Blick?", leitfrageZH: "声音如何引导视线?", noteKeywords: ["ton-film", "multimodal", "film"], children: [] }
] }
] }
] } };
