import type { FachBaum } from "./types";
export const englischBaum: FachBaum = { fach: "Englisch", nameDE: "Englisch", nameZH: "英语", klpReferenz: "NRW KLP Englisch 2023, drei Themenfelder EF plus Zusatz-Ast Sprache-Klausur", klausurFokusDE: "Teil A plus Teil B mit AFB-II-Fokus, Zielniveau B1 mit B2-Anteilen", klausurFokusZH: "目标 B1 冲 B2,考试锚定 A 卷三段加 B 卷二选一,AFB II 为重点", root: { id: "englisch", level: 0, code: "", titleDE: "Englisch", titleZH: "英语", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf1", level: 1, code: "TF 1", titleDE: "Individuum-Gesellschaft", titleZH: "个人与社会", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf1/identitaet", level: 2, code: "", titleDE: "Identitaet", titleZH: "身份", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf1/identitaet/ambitionen-hindernisse", level: 3, code: "", titleDE: "Ambitionen-Hindernisse", titleZH: "抱负与障碍", operatoren: ["outline", "explain"], klausurDE: "Teil A Summary-Analysis, AFB I-II, B1 mit B2-Anteilen", klausurZH: "A 卷概要到分析,AFB I-II,B1 含 B2 成分", leitfrageDE: "What shapes identity under pressure?", leitfrageZH: "压力下什么塑造了身份?", noteKeywords: ["summary", "characterization", "ambition"], children: [] },
{ id: "englisch/tf1/identitaet/role-models", level: 3, code: "", titleDE: "Role Models", titleZH: "榜样", operatoren: ["analyse", "evaluate"], klausurDE: "Teil A Analysis-Evaluation, AFB II-III, Topic Role Models", klausurZH: "A 卷分析到评价,AFB II-III,榜样话题", leitfrageDE: "Are role models convincing?", leitfrageZH: "榜样有说服力吗?", noteKeywords: ["role-models-analysis", "comment", "characterization"], children: [] },
{ id: "englisch/tf1/identitaet/jugend-vielfalt", level: 3, code: "", titleDE: "Jugend-Vielfalt", titleZH: "青年多样性", operatoren: ["outline", "discuss"], klausurDE: "Teil A Summary-Comment, AFB II-III, Diversity-Baustein", klausurZH: "A 卷概要到评论,AFB II-III,多样性模块", leitfrageDE: "How diverse is youth identity?", leitfrageZH: "青年身份有多多样?", noteKeywords: ["diversity", "comment", "discussion"], children: [] }
] },
{ id: "englisch/tf1/konformitaet-individualismus", level: 2, code: "", titleDE: "Konformitaet-Individualismus", titleZH: "顺从与个性", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf1/konformitaet-individualismus/conformity-individualism", level: 3, code: "", titleDE: "Conformity vs Individualism", titleZH: "顺从与个性之争", operatoren: ["compare", "interpret"], klausurDE: "Teil A Analysis, AFB II Schwerpunkt, Vergleichs-Baustein", klausurZH: "A 卷分析,AFB II 重点,比较模块", leitfrageDE: "Conformity or individuality?", leitfrageZH: "顺从还是个性?", noteKeywords: ["characterization", "comparison", "conformity"], children: [] },
{ id: "englisch/tf1/konformitaet-individualismus/peer-pressure", level: 3, code: "", titleDE: "Peer Pressure", titleZH: "同伴压力", operatoren: ["examine", "discuss"], klausurDE: "Teil A Analysis-Evaluation, AFB II-III", klausurZH: "A 卷分析到评价,AFB II-III", leitfrageDE: "How does peer pressure work?", leitfrageZH: "同伴压力如何起作用?", noteKeywords: ["peer-pressure", "discussion", "comment"], children: [] }
] },
{ id: "englisch/tf1/werte-vielfalt", level: 2, code: "", titleDE: "Werte-Vielfalt", titleZH: "价值与多样性", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf1/werte-vielfalt/values-wertewandel", level: 3, code: "", titleDE: "Values-Wertewandel", titleZH: "价值与价值变迁", operatoren: ["outline", "assess"], klausurDE: "Teil A Summary-Evaluation, AFB I-III, Werte-Baustein", klausurZH: "A 卷概要到评价,AFB I-III,价值模块", leitfrageDE: "Which values change?", leitfrageZH: "哪些价值在变?", noteKeywords: ["values", "comment", "evaluation"], children: [] },
{ id: "englisch/tf1/werte-vielfalt/diversity", level: 3, code: "", titleDE: "Diversity", titleZH: "多样性维度", operatoren: ["explain", "comment"], klausurDE: "Teil A Analysis-Comment, AFB II-III", klausurZH: "A 卷分析到评论,AFB II-III", leitfrageDE: "What does diversity mean here?", leitfrageZH: "这里的多样性意味着什么?", noteKeywords: ["diversity", "discussion", "register"], children: [] }
] }
] },
{ id: "englisch/tf2", level: 1, code: "TF 2", titleDE: "Medien-Literatur", titleZH: "媒体与文学", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf2/formate", level: 2, code: "", titleDE: "Formate", titleZH: "媒介形式", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf2/formate/classic-formats", level: 3, code: "", titleDE: "Classic Formats", titleZH: "传统形式", operatoren: ["outline", "explain"], klausurDE: "Teil A Summary-Analysis, AFB I-II", klausurZH: "A 卷概要到分析,AFB I-II", leitfrageDE: "How does the classic format work?", leitfrageZH: "传统形式如何运作?", noteKeywords: ["format", "register", "summary"], children: [] },
{ id: "englisch/tf2/formate/multimodal-formats", level: 3, code: "", titleDE: "Multimodal Formats", titleZH: "多模态形式", operatoren: ["analyse", "examine"], klausurDE: "Teil A Analysis, AFB II Schwerpunkt", klausurZH: "A 卷分析,AFB II 重点", leitfrageDE: "How do image, sound and text interact?", leitfrageZH: "图声文如何互动?", noteKeywords: ["stylistic-devices", "multimodal", "register"], children: [] }
] },
{ id: "englisch/tf2/young-adult-fiction", level: 2, code: "", titleDE: "Young Adult Fiction", titleZH: "青少年小说", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf2/young-adult-fiction/characters", level: 3, code: "", titleDE: "Characters", titleZH: "人物", operatoren: ["analyse", "interpret"], klausurDE: "Teil A Summary-Analysis, AFB II Schwerpunkt, Lektuere-Kern", klausurZH: "A 卷概要到分析,AFB II 重点,长篇阅读核心", leitfrageDE: "What drives the character?", leitfrageZH: "什么驱动着人物?", noteKeywords: ["characterization", "pee", "summary"], children: [] },
{ id: "englisch/tf2/young-adult-fiction/narrative-perspective", level: 3, code: "", titleDE: "Narrative Perspective", titleZH: "叙述视角", operatoren: ["examine", "interpret"], klausurDE: "Teil A Analysis, AFB II, Erzaehl-Baustein", klausurZH: "A 卷分析,AFB II,叙事模块", leitfrageDE: "Who sees and who speaks?", leitfrageZH: "谁在看、谁在说?", noteKeywords: ["characterization", "pee", "perspective"], children: [] },
{ id: "englisch/tf2/young-adult-fiction/themes-message", level: 3, code: "", titleDE: "Themes-Message", titleZH: "主题与信息", operatoren: ["interpret", "evaluate"], klausurDE: "Teil A Analysis-Evaluation, AFB II-III", klausurZH: "A 卷分析到评价,AFB II-III", leitfrageDE: "What is the novel about at its core?", leitfrageZH: "这部小说核心讲什么?", noteKeywords: ["themes", "discussion", "comment"], children: [] }
] },
{ id: "englisch/tf2/identitaetsbildung-literatur", level: 2, code: "", titleDE: "Identitaetsbildung-Literatur", titleZH: "文学与身份塑造", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf2/identitaetsbildung-literatur/identification", level: 3, code: "", titleDE: "Identification", titleZH: "认同", operatoren: ["explain", "discuss"], klausurDE: "Teil A Evaluation-Comment, AFB III", klausurZH: "A 卷评价或评论,AFB III", leitfrageDE: "Why do readers identify?", leitfrageZH: "读者为何认同?", noteKeywords: ["identification", "discussion", "comment"], children: [] },
{ id: "englisch/tf2/identitaetsbildung-literatur/intention-reception", level: 3, code: "", titleDE: "Intention-Reception", titleZH: "意图与接受", operatoren: ["interpret", "assess"], klausurDE: "Teil A Evaluation, AFB II-III, Rezeptions-Baustein", klausurZH: "A 卷评价,AFB II-III,接受模块", leitfrageDE: "What is intended and what is received?", leitfrageZH: "意图是什么、接受到的是什么?", noteKeywords: ["reception", "contextualization", "comment"], children: [] }
] }
] },
{ id: "englisch/tf3", level: 1, code: "TF 3", titleDE: "Arbeit-Welt", titleZH: "工作与世界", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf3/auslandsjahr", level: 2, code: "", titleDE: "Auslandsjahr", titleZH: "海外交流年", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf3/auslandsjahr/motives", level: 3, code: "", titleDE: "Motives", titleZH: "动机", operatoren: ["outline", "explain"], klausurDE: "Teil A Summary, AFB I-II", klausurZH: "A 卷概要,AFB I-II", leitfrageDE: "Why go abroad?", leitfrageZH: "为何出国?", noteKeywords: ["summary", "motives", "abroad"], children: [] },
{ id: "englisch/tf3/auslandsjahr/challenges", level: 3, code: "", titleDE: "Challenges", titleZH: "挑战", operatoren: ["examine", "analyse"], klausurDE: "Teil A Analysis, AFB II Schwerpunkt", klausurZH: "A 卷分析,AFB II 重点", leitfrageDE: "What makes it difficult?", leitfrageZH: "难在哪里?", noteKeywords: ["challenges", "strategies", "characterization"], children: [] },
{ id: "englisch/tf3/auslandsjahr/evaluation", level: 3, code: "", titleDE: "Evaluation", titleZH: "评价", operatoren: ["evaluate", "discuss"], klausurDE: "Teil A Evaluation-Comment, AFB III", klausurZH: "A 卷评价或评论,AFB III", leitfrageDE: "Was it worth it?", leitfrageZH: "值得吗?", noteKeywords: ["comment", "discussion", "evaluation"], children: [] }
] },
{ id: "englisch/tf3/lernen-studium", level: 2, code: "", titleDE: "Lernen-Studium", titleZH: "学习与求学", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf3/lernen-studium/school-abroad", level: 3, code: "", titleDE: "School Abroad", titleZH: "海外学校", operatoren: ["outline", "compare"], klausurDE: "Teil A Summary-Analysis, AFB I-II", klausurZH: "A 卷概要到分析,AFB I-II", leitfrageDE: "How different is school abroad?", leitfrageZH: "海外学校有何不同?", noteKeywords: ["school-abroad", "summary", "comparison"], children: [] },
{ id: "englisch/tf3/lernen-studium/intercultural-learning", level: 3, code: "", titleDE: "Intercultural Learning", titleZH: "跨文化学习", operatoren: ["explain", "comment"], klausurDE: "Teil A Analysis-Comment, AFB II-III", klausurZH: "A 卷分析到评论,AFB II-III", leitfrageDE: "What is learned between cultures?", leitfrageZH: "文化之间学到了什么?", noteKeywords: ["contextualization", "strategies", "intercultural"], children: [] }
] },
{ id: "englisch/tf3/arbeiten-leben", level: 2, code: "", titleDE: "Arbeiten-Leben", titleZH: "工作与生活", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/tf3/arbeiten-leben/jobs-abroad", level: 3, code: "", titleDE: "Jobs Abroad", titleZH: "海外工作", operatoren: ["outline", "assess"], klausurDE: "Teil A Summary-Evaluation, AFB I-III", klausurZH: "A 卷概要到评价,AFB I-III", leitfrageDE: "What does working abroad offer?", leitfrageZH: "海外工作带来什么?", noteKeywords: ["jobs-abroad", "summary", "comment"], children: [] },
{ id: "englisch/tf3/arbeiten-leben/life-work-balance", level: 3, code: "", titleDE: "Life-Work Balance", titleZH: "生活与工作", operatoren: ["discuss", "evaluate"], klausurDE: "Teil A Comment, AFB III", klausurZH: "A 卷评论,AFB III", leitfrageDE: "How to balance life and work?", leitfrageZH: "如何平衡生活与工作?", noteKeywords: ["life-work-balance", "discussion", "comment"], children: [] }
] }
] },
{ id: "englisch/zusatz", level: 1, code: "Zusatz", titleDE: "Sprache-Klausur", titleZH: "语言与考试工具枝", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/zusatz/wortschatz", level: 2, code: "", titleDE: "Wortschatz", titleZH: "词汇", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/zusatz/wortschatz/topic-vocabulary", level: 3, code: "", titleDE: "Topic Vocabulary", titleZH: "话题词汇", operatoren: ["outline", "explain"], klausurDE: "Teil A Summary-Evaluation, AFB I-III, Sprach-Basis B1 mit B2-Anteilen", klausurZH: "A 卷概要或评价,AFB I-III,语言基础 B1 含 B2 成分", leitfrageDE: "Which words fit the topic?", leitfrageZH: "哪些词贴合话题?", noteKeywords: ["register", "topic-vocabulary", "summary"], children: [] },
{ id: "englisch/zusatz/wortschatz/linking-devices", level: 3, code: "", titleDE: "Linking Devices", titleZH: "衔接手段", operatoren: ["outline", "comment"], klausurDE: "Teil A alle drei Schritte, AFB I-III, Kohärenz-Baustein", klausurZH: "A 卷全部三段,AFB I-III,连贯模块", leitfrageDE: "How is the text linked?", leitfrageZH: "文本如何衔接?", noteKeywords: ["linking-devices", "coherence", "strategies"], children: [] }
] },
{ id: "englisch/zusatz/strukturen", level: 2, code: "", titleDE: "Strukturen", titleZH: "结构", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/zusatz/strukturen/tenses-present", level: 3, code: "", titleDE: "Tenses-Present", titleZH: "时态与现在时", operatoren: ["outline", "examine"], klausurDE: "Teil A Summary, AFB I, Regel own words plus present tense", klausurZH: "A 卷概要,AFB I,规则自己话加现在时", leitfrageDE: "Is it in your own present-tense words?", leitfrageZH: "是否用自己的话与现在时改写?", noteKeywords: ["summary", "present-tense", "own-words"], children: [] },
{ id: "englisch/zusatz/strukturen/analysis-vocabulary", level: 3, code: "", titleDE: "Analysis Vocabulary", titleZH: "分析用语", operatoren: ["analyse", "explain"], klausurDE: "Teil A Analysis, AFB II Schwerpunkt", klausurZH: "A 卷分析,AFB II 重点", leitfrageDE: "How to name devices precisely?", leitfrageZH: "如何精准命名手法?", noteKeywords: ["stylistic-devices", "register", "pee"], children: [] }
] },
{ id: "englisch/zusatz/teil-a-lesen-schreiben", level: 2, code: "", titleDE: "Teil A Lesen-Schreiben", titleZH: "A卷读写一体", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/zusatz/teil-a-lesen-schreiben/summary", level: 3, code: "", titleDE: "Summary", titleZH: "概要", operatoren: ["outline", "explain"], klausurDE: "Teil A Schritt 1, AFB I, no comment", klausurZH: "A 卷第一段,AFB I,不加评论", leitfrageDE: "What is the text about?", leitfrageZH: "文本讲了什么?", noteKeywords: ["summary", "own-words", "present-tense"], children: [] },
{ id: "englisch/zusatz/teil-a-lesen-schreiben/analysis", level: 3, code: "", titleDE: "Analysis", titleZH: "分析", operatoren: ["analyse", "examine"], klausurDE: "Teil A Schritt 2, AFB II Schwerpunkt", klausurZH: "A 卷第二段,AFB II 重点", leitfrageDE: "How does the text work?", leitfrageZH: "文本如何运作?", noteKeywords: ["pee", "stylistic-devices", "characterization"], children: [] },
{ id: "englisch/zusatz/teil-a-lesen-schreiben/evaluation-recreation", level: 3, code: "", titleDE: "Evaluation-Recreation", titleZH: "评价与改写", operatoren: ["evaluate", "assess"], klausurDE: "Teil A Schritt 3, AFB III, Evaluation oder re-creation of text", klausurZH: "A 卷第三段,AFB III,评价或文本改写", leitfrageDE: "What is your justified view or new text?", leitfrageZH: "你的有依据观点或新文本是什么?", noteKeywords: ["comment", "discussion", "re-creation"], children: [] }
] },
{ id: "englisch/zusatz/teil-b-wahlteil", level: 2, code: "", titleDE: "Teil B Wahlteil", titleZH: "B卷二选一", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "englisch/zusatz/teil-b-wahlteil/sprachmittlung", level: 3, code: "", titleDE: "Sprachmittlung", titleZH: "语言转述", operatoren: ["explain", "interpret"], klausurDE: "Teil B isoliert, AFB I-II, Mediation-Baustein", klausurZH: "B 卷独立,AFB I-II,转述模块", leitfrageDE: "What does the reader need to know?", leitfrageZH: "读者需要知道什么?", noteKeywords: ["mediation", "paraphrasing", "contextualization"], children: [] },
{ id: "englisch/zusatz/teil-b-wahlteil/hoerverstehen", level: 3, code: "", titleDE: "Hoerverstehen", titleZH: "听力理解", operatoren: ["outline", "examine"], klausurDE: "Teil B isoliert, AFB I-II, 2 Texte ca. 6 Min, 2 Durchgaenge", klausurZH: "B 卷独立,AFB I-II,两文本约 6 分钟,两遍", leitfrageDE: "What are the key points?", leitfrageZH: "要点是什么?", noteKeywords: ["listening", "summary", "strategies"], children: [] }
] }
] }
] } };
