import type { FachBaum } from "./types";
export const matheBaum: FachBaum = { fach: "Mathe", nameDE: "Mathematik", nameZH: "数学", klpReferenz: "NRW KLP Mathematik 2023", klausurFokusDE: "ZKE (Teil A ohne Hilfsmittel / Teil B mit Hilfsmitteln) + Darstellungsleistung", klausurFokusZH: "全州统考 ZKE（A 卷无工具 / B 卷可用官方公式表）+ 解题过程表达分", root: { id: "mathe", level: 0, code: "", titleDE: "Mathematik", titleZH: "数学", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if1", level: 1, code: "IF 1", titleDE: "Funktionen und Analysis", titleZH: "函数与分析", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if1/funktionstypen", level: 2, code: "", titleDE: "Funktionstypen und Graphen", titleZH: "函数类型与图像", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if1/funktionstypen/potenzfunktionen", level: 3, code: "", titleDE: "Potenzfunktionen", titleZH: "幂函数", operatoren: ["darstellen", "beschreiben", "bestimmen"], klausurDE: "Teil A Grundlagenaufgabe: aus Term Graphmerkmale bestimmen (AFB I-II). ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 基础题：由解析式判断图像特征（AFB I-II）；ZKE 的 A 卷部分无工具。", leitfrageDE: "Welche Form hat der Graph von f mit ganzzahligem Exponenten?", leitfrageZH: "整数指数的幂函数图像长什么样？", noteKeywords: ["potenzfunktion", "graph", "definitionsbereich", "monotonie"], children: [] },
{ id: "mathe/if1/funktionstypen/ganzrationale-funktionen", level: 3, code: "", titleDE: "Ganzrationale Funktionen", titleZH: "整式函数", operatoren: ["darstellen", "beschreiben", "begründen"], klausurDE: "Teil A/B: Globalverlauf aus Leitkoeffizient und Grad ablesen. ZKE Teil B mit Formelsammlung; Darstellungsleistung zählt.", klausurZH: "Teil A/B 标准对象：从首项系数和次数读出两端走势；ZKE 的 B 卷可用官方公式表，表达分计入成绩。", leitfrageDE: "Wie bestimmt der Grad den Globalverlauf?", leitfrageZH: "次数如何决定函数两端的走势？", noteKeywords: ["ganzrational", "globalverlauf", "leitkoeffizient", "kurvendiskussion"], children: [] },
{ id: "mathe/if1/funktionstypen/definitions-wertebereich-verlauf", level: 3, code: "", titleDE: "Definitions- und Wertebereich, Verlauf", titleZH: "定义域、值域与走势", operatoren: ["angeben", "beschreiben", "bestimmen"], klausurDE: "Teil A: Definitions-/Wertebereich angeben, Verlauf beschreiben. ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 必考小问：写出定义域值域并描述走势；ZKE 的 A 卷部分无工具。", leitfrageDE: "Wo ist die Funktion definiert und wohin läuft der Graph?", leitfrageZH: "函数在哪里有定义、图像往哪里走？", noteKeywords: ["definitionsbereich", "wertebereich", "globalverlauf", "graph"], children: [] },
{ id: "mathe/if1/funktionstypen/symmetrie-nullstellen", level: 3, code: "", titleDE: "Symmetrie und Nullstellen", titleZH: "对称性与零点", operatoren: ["bestimmen", "berechnen", "begründen"], klausurDE: "Teil A: Nullstellen berechnen, Symmetrie nachweisen. ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 常规计算：求零点并证明对称性；ZKE 的 A 卷部分无工具。", leitfrageDE: "Wie weist man Symmetrie und Nullstellen nach?", leitfrageZH: "如何证明对称性并求出零点？", noteKeywords: ["symmetrie", "nullstellen", "kurvendiskussion"], children: [] }
] },
{ id: "mathe/if1/transformationen", level: 2, code: "", titleDE: "Transformationen", titleZH: "图像变换", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if1/transformationen/verschiebung", level: 3, code: "", titleDE: "Verschiebung", titleZH: "平移", operatoren: ["darstellen", "beschreiben", "bestimmen"], klausurDE: "Teil A: Verschiebung am Term ablesen oder einzeichnen (Graph zu Term). ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 图与式互推：从解析式读出平移或画出图像；ZKE 的 A 卷部分无工具。", leitfrageDE: "Wie verschiebt ein Parameter den Graphen?", leitfrageZH: "参数如何让图像平移？", noteKeywords: ["verschiebung", "parameter", "graph", "term"], children: [] },
{ id: "mathe/if1/transformationen/spiegelung-streckung", level: 3, code: "", titleDE: "Spiegelung und Streckung", titleZH: "对称与伸缩", operatoren: ["darstellen", "beschreiben", "begründen"], klausurDE: "Teil A/B: Transformation beschreiben und skizzieren. ZKE Teil B mit Formelsammlung; Darstellungsleistung zählt.", klausurZH: "Teil A/B 作图题：描述变换并画出草图；ZKE 的 B 卷可用公式表，表达分计入成绩。", leitfrageDE: "Was bewirkt ein Faktor oder Minus vor Funktion oder Variable?", leitfrageZH: "函数前或变量前的系数与负号起什么作用？", noteKeywords: ["spiegelung", "streckung", "parameter", "skizze"], children: [] },
{ id: "mathe/if1/transformationen/graph-term", level: 3, code: "", titleDE: "Graph zu Term und zurück", titleZH: "图像与解析式互推", operatoren: ["darstellen", "bestimmen", "begründen"], klausurDE: "Teil B Modellierung: aus Skizze Term aufstellen und umgekehrt. Darstellungsleistung zählt.", klausurZH: "Teil B 建模：从草图写解析式及反向作图；解题过程表达分计入成绩。", leitfrageDE: "Wie kommt man vom Bild zum Term und zurück?", leitfrageZH: "如何在图像和解析式之间来回转换？", noteKeywords: ["graph", "term", "modellierung", "steckbrief"], children: [] }
] },
{ id: "mathe/if1/ableitung", level: 2, code: "", titleDE: "Ableitungsbegriff und Regeln", titleZH: "导数概念与法则", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if1/ableitung/mittlere-aenderungsrate", level: 3, code: "", titleDE: "Mittlere Änderungsrate", titleZH: "平均变化率", operatoren: ["berechnen", "beschreiben", "deuten"], klausurDE: "Teil A/B Anwendungseinstieg: Differenzenquotient berechnen und als Steigung deuten. ZKE Teil B mit Formelsammlung; Darstellungsleistung zählt.", klausurZH: "Teil A/B 应用题入口：计算差商并解释为斜率；ZKE 的 B 卷可用公式表，表达分计入成绩。", leitfrageDE: "Was misst der Differenzenquotient?", leitfrageZH: "差商度量的是什么？", noteKeywords: ["differenzenquotient", "sekante", "steigung", "aenderungsrate"], children: [] },
{ id: "mathe/if1/ableitung/lokale-aenderungsrate", level: 3, code: "", titleDE: "Lokale Änderungsrate und Ableitung", titleZH: "局部变化率与导数", operatoren: ["erklären", "beschreiben", "begründen"], klausurDE: "Teil A Verständnis: Übergang Sekante zu Tangente erklären (AFB II). ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 理解题：解释割线到切线的过渡（AFB II）；ZKE 的 A 卷部分无工具。", leitfrageDE: "Wie wird aus der Sekante eine Tangente?", leitfrageZH: "割线如何变成切线？", noteKeywords: ["ableitung", "limes", "tangente", "sekante"], children: [] },
{ id: "mathe/if1/ableitung/potenz-faktor-summenregel", level: 3, code: "", titleDE: "Potenz-, Faktor-, Summenregel", titleZH: "幂法则、系数法则、求和法则", operatoren: ["berechnen", "bestimmen", "angeben"], klausurDE: "Teil A Rechnung: Ableitung mit Potenz-, Faktor- und Summenregel bilden. ZKE Teil A ohne Hilfsmittel; Formelsammlung erst in Teil B.", klausurZH: "Teil A 纯计算：用三条法则求导；ZKE 的 A 卷无工具，公式表仅 B 卷可用。", leitfrageDE: "Wie leitet man Potenzen und Summen ab?", leitfrageZH: "幂和加和如何求导？", noteKeywords: ["potenzregel", "faktorregel", "summenregel", "ableitung"], children: [] },
{ id: "mathe/if1/ableitung/ableitungsfunktion-graph", level: 3, code: "", titleDE: "Ableitungsfunktion und Graph", titleZH: "导函数与图像", operatoren: ["darstellen", "beschreiben", "begründen"], klausurDE: "Teil A: Graph von f und f' einander zuordnen. ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 读图题：把原函数与导函数图像配对；ZKE 的 A 卷部分无工具。", leitfrageDE: "Was verrät der Graph von f' über f?", leitfrageZH: "导函数图像告诉我们原函数的什么信息？", noteKeywords: ["ableitung", "ableitungsfunktion", "graph", "monotonie"], children: [] }
] },
{ id: "mathe/if1/tangente-kurvenuntersuchung", level: 2, code: "", titleDE: "Tangente und Kurvenuntersuchung", titleZH: "切线与曲线考察", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if1/tangente-kurvenuntersuchung/tangente-normale", level: 3, code: "", titleDE: "Tangente und Normale", titleZH: "切线与法线", operatoren: ["bestimmen", "berechnen", "begründen"], klausurDE: "Teil A/B Schwerpunkt: Tangentengleichung aufstellen. ZKE Teil B mit Formelsammlung; Darstellungsleistung zählt.", klausurZH: "Teil A/B 高频大题：求切线方程；ZKE 的 B 卷可用公式表，表达分计入成绩。", leitfrageDE: "Wie stellt man Tangente und Normale auf?", leitfrageZH: "如何求切线和法线方程？", noteKeywords: ["tangente", "tangentenformel", "normale", "steigung"], children: [] },
{ id: "mathe/if1/tangente-kurvenuntersuchung/monotonie-extrema", level: 3, code: "", titleDE: "Monotonie und Extrema", titleZH: "单调性与极值", operatoren: ["bestimmen", "begründen", "berechnen"], klausurDE: "Teil B Kernschritt: Hoch-/Tiefpunkte mit Vorzeichenwechsel nachweisen. Darstellungsleistung zählt.", klausurZH: "Teil B 核心步骤：用变号证明极大极小值；表达分计入成绩。", leitfrageDE: "Wann liegt ein Hoch- oder Tiefpunkt vor?", leitfrageZH: "什么时候是极大值或极小值？", noteKeywords: ["monotonie", "extrema", "vorzeichenwechsel", "kurvendiskussion"], children: [] },
{ id: "mathe/if1/tangente-kurvenuntersuchung/kruemmung-wendepunkte", level: 3, code: "", titleDE: "Krümmung und Wendepunkte", titleZH: "凹凸性与拐点", operatoren: ["bestimmen", "begründen", "berechnen"], klausurDE: "Teil B: Wendepunkt mit f''-Vorzeichenwechsel nachweisen. Darstellungsleistung zählt.", klausurZH: "Teil B 压轴步骤：用二阶导变号证明拐点；表达分计入成绩。", leitfrageDE: "Was zeigt die zweite Ableitung?", leitfrageZH: "二阶导数说明什么？", noteKeywords: ["wendepunkt", "kruemmung", "ableitung", "kurvendiskussion"], children: [] },
{ id: "mathe/if1/tangente-kurvenuntersuchung/modellierung", level: 3, code: "", titleDE: "Modellierung", titleZH: "建模应用题", operatoren: ["modellieren", "bestimmen", "bewerten"], klausurDE: "Teil B Anwendung: Realsituation zu Funktion zu Extremwert zu Rückdeutung. Darstellungsleistung zählt.", klausurZH: "Teil B 应用题：现实问题转函数求极值再回扣现实；表达分计入成绩。", leitfrageDE: "Wie wird aus der Aufgabe eine Zielfunktion?", leitfrageZH: "应用题如何变成目标函数？", noteKeywords: ["modellierung", "steckbrief", "extremwert", "funktionsanpassung"], children: [] }
] }
] },
{ id: "mathe/if2", level: 1, code: "IF 2", titleDE: "Analytische Geometrie", titleZH: "解析几何", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if2/vektoren", level: 2, code: "", titleDE: "Vektoren und Rechnen", titleZH: "向量与运算", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if2/vektoren/punkte-ortsvektoren", level: 3, code: "", titleDE: "Punkte und Ortsvektoren", titleZH: "点与定位向量", operatoren: ["darstellen", "bestimmen", "beschreiben"], klausurDE: "Teil A Basis: Koordinaten ablesen, Ortsvektor angeben. ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 基础：读坐标并写出定位向量；ZKE 的 A 卷部分无工具。", leitfrageDE: "Was unterscheidet Punkt und Vektor?", leitfrageZH: "点和向量有什么区别？", noteKeywords: ["ortsvektor", "punkt", "koordinaten", "vektor"], children: [] },
{ id: "mathe/if2/vektoren/addition-skalarmultiplikation", level: 3, code: "", titleDE: "Addition und Skalarmultiplikation", titleZH: "加法与数乘", operatoren: ["berechnen", "darstellen", "bestimmen"], klausurDE: "Teil A Rechnung: Vektoren komponentenweise addieren und vervielfachen. ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 计算：向量按分量加法与数乘；ZKE 的 A 卷部分无工具。", leitfrageDE: "Wie rechnet man mit Vektoren in Koordinaten?", leitfrageZH: "坐标下如何做向量运算？", noteKeywords: ["vektoraddition", "skalarmultiplikation", "komponenten", "vektor"], children: [] },
{ id: "mathe/if2/vektoren/laenge-kollinearitaet", level: 3, code: "", titleDE: "Länge und Kollinearität", titleZH: "模长与共线", operatoren: ["berechnen", "begründen", "bestimmen"], klausurDE: "Teil A/B: Betrag berechnen, Kollinearität nachweisen. ZKE Teil B mit Formelsammlung; Darstellungsleistung zählt.", klausurZH: "Teil A/B 小问：求模长并证明共线；ZKE 的 B 卷可用公式表，表达分计入成绩。", leitfrageDE: "Wann sind zwei Vektoren kollinear?", leitfrageZH: "两个向量何时共线？", noteKeywords: ["betrag", "kollinearitaet", "laenge", "vektor"], children: [] }
] },
{ id: "mathe/if2/geraden", level: 2, code: "", titleDE: "Geraden in Parameterform", titleZH: "参数式直线", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if2/geraden/geradengleichung", level: 3, code: "", titleDE: "Geradengleichung aufstellen", titleZH: "写出直线方程", operatoren: ["bestimmen", "darstellen", "begründen"], klausurDE: "Teil A/B Pflicht: Gerade durch zwei Punkte in Parameterform angeben. ZKE Teil B mit Formelsammlung; Darstellungsleistung zählt.", klausurZH: "Teil A/B 必考：写出过两点的参数式直线；ZKE 的 B 卷可用公式表，表达分计入成绩。", leitfrageDE: "Was braucht man für eine Geradengleichung?", leitfrageZH: "写直线方程需要什么？", noteKeywords: ["geradengleichung", "parameterform", "richtungsvektor", "stuetzvektor"], children: [] },
{ id: "mathe/if2/geraden/punktprobe", level: 3, code: "", titleDE: "Punktprobe", titleZH: "点的检验", operatoren: ["untersuchen", "begründen", "berechnen"], klausurDE: "Teil A: prüfen, ob ein Punkt auf der Geraden liegt. ZKE Teil A ohne Hilfsmittel.", klausurZH: "Teil A 常规题：检验点是否在直线上；ZKE 的 A 卷部分无工具。", leitfrageDE: "Wie prüft man, ob ein Punkt auf der Geraden liegt?", leitfrageZH: "如何检验点是否在直线上？", noteKeywords: ["punktprobe", "parameterform", "gerade", "parameter"], children: [] },
{ id: "mathe/if2/geraden/zeichnen-deuten", level: 3, code: "", titleDE: "Zeichnen und Deuten", titleZH: "作图与解释", operatoren: ["darstellen", "beschreiben", "deuten"], klausurDE: "Teil A/B: Gerade skizzieren, Parameter deuten (AFB I-II). Darstellungsleistung zählt.", klausurZH: "Teil A/B 图示题：画直线并解释参数（AFB I-II）；表达分计入成绩。", leitfrageDE: "Was bedeutet der Parameter anschaulich?", leitfrageZH: "参数的直观意义是什么？", noteKeywords: ["skizze", "parameter", "parameterform", "deutung"], children: [] }
] },
{ id: "mathe/if2/lagebeziehungen", level: 2, code: "", titleDE: "Lagebeziehungen und Schnittpunkte", titleZH: "位置关系与交点", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "mathe/if2/lagebeziehungen/parallel-identisch", level: 3, code: "", titleDE: "Parallel und identisch", titleZH: "平行与重合", operatoren: ["untersuchen", "begründen", "bestimmen"], klausurDE: "Teil A/B: parallel vs. identisch unterscheiden. ZKE Teil B mit Formelsammlung; Darstellungsleistung zählt.", klausurZH: "Teil A/B 分类题：区分平行与重合；ZKE 的 B 卷可用公式表，表达分计入成绩。", leitfrageDE: "Wie unterscheidet man parallel und identisch?", leitfrageZH: "如何区分平行与重合？", noteKeywords: ["parallel", "identisch", "lagebeziehung", "kollinearitaet"], children: [] },
{ id: "mathe/if2/lagebeziehungen/schnittpunkt", level: 3, code: "", titleDE: "Schneidend und Schnittpunkt", titleZH: "相交与交点", operatoren: ["berechnen", "bestimmen", "begründen"], klausurDE: "Teil B Rechenkern: Schnittpunkt durch Gleichsetzen bestimmen. Darstellungsleistung zählt.", klausurZH: "Teil B 计算核心：联立求交点；表达分计入成绩。", leitfrageDE: "Wie berechnet man den Schnittpunkt?", leitfrageZH: "如何计算交点？", noteKeywords: ["schnittpunkt", "gleichsetzen", "parameterform", "lagebeziehung"], children: [] },
{ id: "mathe/if2/lagebeziehungen/windschief", level: 3, code: "", titleDE: "Windschief", titleZH: "异面", operatoren: ["untersuchen", "begründen", "beschreiben"], klausurDE: "Teil B Nachweis: windschief durch Ausschluss nachweisen. Darstellungsleistung zählt.", klausurZH: "Teil B 证明题：用排除法证明异面；表达分计入成绩。", leitfrageDE: "Wann heißen zwei Geraden windschief?", leitfrageZH: "两条直线何时叫异面？", noteKeywords: ["windschief", "lagebeziehung", "schnittpunkt", "parameterform"], children: [] }
] }
] }
] } };