import type { FachBaum } from "./types";

export const musikBaum: FachBaum = {
  fach: "Musik",
  nameDE: "Musik",
  nameZH: "音乐",
  klpReferenz: "NRW KLP GOSt Musik EF, mündliche Prüfung",
  klausurFokusDE: "Hörbeispiel beschreiben, mit Fachbegriffen analysieren, in Vortrag und Gespräch reflektiert urteilen; Ablauf Hören, Beschreiben, Analysefrage, Vortrag und Gespräch",
  klausurFokusZH: "口试看三件事：听得出参数、说得出分析、讲得出判断；术语要准，结构先行",
  root: {
    id: "musik",
    level: 0,
    code: "",
    titleDE: "Musik",
    titleZH: "音乐",
    operatoren: [],
    klausurDE: "",
    klausurZH: "",
    leitfrageDE: "",
    leitfrageZH: "",
    noteKeywords: [],
    children: [
      {
        id: "musik/if1",
        level: 1,
        code: "IF 1",
        titleDE: "Hören und Beschreiben",
        titleZH: "听与描述",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "musik/if1/parameter",
            level: 2,
            code: "",
            titleDE: "Parameter",
            titleZH: "音乐参数",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if1/parameter/rhythmus-tempo",
                level: 3,
                code: "",
                titleDE: "Rhythmus und Tempo",
                titleZH: "节奏与速度",
                operatoren: ["beschreiben", "benennen"],
                klausurDE: "Mündlicher Einstieg am Hörbeispiel: Takt, Rhythmusmuster und Tempowechsel mit dem Satzmuster Ich höre benennen.",
                klausurZH: "口试第1环节：听出拍号节奏型和速度，用德语说准",
                leitfrageDE: "Welchen Rhythmus und welches Tempo höre ich?",
                leitfrageZH: "我听到了什么样的节奏和速度？",
                noteKeywords: ["rhythmus", "tempo", "takt", "hoerbeispiel"],
                children: [],
              },
              {
                id: "musik/if1/parameter/melodiebildung",
                level: 3,
                code: "",
                titleDE: "Melodiebildung",
                titleZH: "旋律构成",
                operatoren: ["beschreiben", "darstellen"],
                klausurDE: "Mündliche Beschreibung: Melodieverlauf und Wiederkehr des Themas fassen, Grundlage für die spätere Analyse.",
                klausurZH: "口试描述环节：抓住走向和主题重复，能哼出轮廓",
                leitfrageDE: "Wie verläuft die Melodie und was kehrt wieder?",
                leitfrageZH: "旋律如何进行、什么在重复？",
                noteKeywords: ["melodie", "thema", "wiederkehr", "verlauf"],
                children: [],
              },
              {
                id: "musik/if1/parameter/harmonie-klangfarbe",
                level: 3,
                code: "",
                titleDE: "Harmonie und Klangfarbe",
                titleZH: "和声与音色",
                operatoren: ["beschreiben", "unterscheiden"],
                klausurDE: "Mündlicher Übergang von Beschreibung zur Analyse: Tongeschlecht, Satzdichte und Instrumentenklang unterscheiden.",
                klausurZH: "口试1到2环节过渡：分辨大小调色彩与乐器音色",
                leitfrageDE: "Welche Harmonik und welche Klangfarbe prägen das Beispiel?",
                leitfrageZH: "是什么样的和声与音色主导了这段音乐？",
                noteKeywords: ["harmonie", "klangfarbe", "dur-moll", "instrumente"],
                children: [],
              },
              {
                id: "musik/if1/parameter/dynamik-formverlauf",
                level: 3,
                code: "",
                titleDE: "Dynamik und Formverlauf",
                titleZH: "力度与曲式进行",
                operatoren: ["beschreiben", "gliedern"],
                klausurDE: "Mündlicher Abschluss der Beschreibung: Dynamikstufen und Abschnittsanlage gliedern, überleitet zur Formfrage.",
                klausurZH: "口试描述收尾：听出力度层次与段落布局，引出曲式",
                leitfrageDE: "Wie sind Dynamik und Ablauf gegliedert?",
                leitfrageZH: "力度与段落是如何布局的？",
                noteKeywords: ["dynamik", "formverlauf", "gliederung", "abschnitte"],
                children: [],
              },
            ],
          },
          {
            id: "musik/if1/epochenmerkmale",
            level: 2,
            code: "",
            titleDE: "Epochenmerkmale",
            titleZH: "时代特征",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if1/epochenmerkmale/barock",
                level: 3,
                code: "",
                titleDE: "Barockmerkmale",
                titleZH: "巴洛克特征",
                operatoren: ["beschreiben", "zuordnen"],
                klausurDE: "Mündliche Analysefrage: Epoche am Hörbeispiel verorten, eine der möglichen Zuordnungen.",
                klausurZH: "口试分析追问：时代定位备选项之一",
                leitfrageDE: "Woran erkenne ich Barock im Hörbeispiel?",
                leitfrageZH: "我从哪些特征听出巴洛克？",
                noteKeywords: ["barock", "generalbass", "polyphonie", "zuordnung"],
                children: [],
              },
              {
                id: "musik/if1/epochenmerkmale/klassik-beethoven",
                level: 3,
                code: "",
                titleDE: "Klassik mit Beethoven-Schwerpunkt",
                titleZH: "古典风格与贝多芬重点 ⏳",
                operatoren: ["beschreiben", "analysieren", "einordnen"],
                klausurDE: "Mündliche Analyse im Regelablauf Hörbeispiel, Epoche, Form; falls das Halbjahrthema bestätigt wird, als häufiger Analysegegenstand.",
                klausurZH: "口试常规流程：听例、断代、曲式；若学期主题确认则为高频对象",
                leitfrageDE: "Was klingt klassisch und was deutet auf Beethoven?",
                leitfrageZH: "哪里听出古典风格、哪里指向贝多芬？",
                noteKeywords: ["klassik", "beethoven", "motiv", "homophonie"],
                children: [],
              },
              {
                id: "musik/if1/epochenmerkmale/romantik",
                level: 3,
                code: "",
                titleDE: "Romantikmerkmale",
                titleZH: "浪漫派特征",
                operatoren: ["beschreiben", "vergleichen"],
                klausurDE: "Mündliche Analysefrage: Häufig im Kontrast zur Klassik befragt.",
                klausurZH: "口试常以与古典对比的方式出现",
                leitfrageDE: "Wodurch wirkt das Beispiel romantisch?",
                leitfrageZH: "这段音乐为什么听起来很浪漫派？",
                noteKeywords: ["romantik", "chromatik", "ausdruck", "vergleich"],
                children: [],
              },
              {
                id: "musik/if1/epochenmerkmale/pop",
                level: 3,
                code: "",
                titleDE: "Popmerkmale",
                titleZH: "流行音乐特征",
                operatoren: ["beschreiben", "vergleichen"],
                klausurDE: "Mündliches Gespräch: Als Gegenpol zu Klassik im Vergleich befragt.",
                klausurZH: "口试对话环节：作为古典的对比极进入",
                leitfrageDE: "Was unterscheidet Pop klanglich von Klassik?",
                leitfrageZH: "流行音乐在声音上与古典有何不同？",
                noteKeywords: ["pop", "songform", "groove", "klang"],
                children: [],
              },
            ],
          },
          {
            id: "musik/if1/hoerprotokoll-fachsprache",
            level: 2,
            code: "",
            titleDE: "Hörprotokoll und Fachsprache",
            titleZH: "听记与术语",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if1/hoerprotokoll-fachsprache/ersthoeren-ueberblick",
                level: 3,
                code: "",
                titleDE: "Ersthören und Überblick",
                titleZH: "初听与总览",
                operatoren: ["beschreiben", "zusammenfassen"],
                klausurDE: "Mündlicher Auftakt: In ein bis zwei Minuten Gesamteindruck und Abschnittszahl zusammenfassen, ohne Details.",
                klausurZH: "口试开场一两分钟：只抓整体印象与段落数",
                leitfrageDE: "Was ist mein erster Gesamteindruck?",
                leitfrageZH: "我的第一整体印象是什么？",
                noteKeywords: ["ersthoeren", "ueberblick", "eindruck", "struktur"],
                children: [],
              },
              {
                id: "musik/if1/hoerprotokoll-fachsprache/fachbegriffe",
                level: 3,
                code: "",
                titleDE: "Fachbegriffe treffsicher verwenden",
                titleZH: "准确使用术语",
                operatoren: ["benennen", "definieren"],
                klausurDE: "Mündlich durchgehend bewertet: Parameter korrekt benennen statt Alltagssprache, saubere Aussprache.",
                klausurZH: "口试贯穿全场：用术语不用日常词，发音准确",
                leitfrageDE: "Nutze ich den Fachbegriff statt der Alltagssprache?",
                leitfrageZH: "我用的是术语而不是日常词吗？",
                noteKeywords: ["fachbegriffe", "benennen", "aussprache", "praezision"],
                children: [],
              },
              {
                id: "musik/if1/hoerprotokoll-fachsprache/beschreibung-struktur",
                level: 3,
                code: "",
                titleDE: "Beschreibung strukturieren",
                titleZH: "结构化描述",
                operatoren: ["darstellen", "gliedern"],
                klausurDE: "Mündliche Beschreibung mit Strukturpunkten: Überblick, Parameter, Fazit nach fester Reihenfolge.",
                klausurZH: "口试描述结构分：总览、分参数、小结固定顺序",
                leitfrageDE: "Folgt meine Beschreibung einer klaren Reihenfolge?",
                leitfrageZH: "我的描述有清晰顺序吗？",
                noteKeywords: ["struktur", "reihenfolge", "darstellen", "fazit"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "musik/if2",
        level: 1,
        code: "IF 2",
        titleDE: "Analysieren",
        titleZH: "分析",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "musik/if2/formteile",
            level: 2,
            code: "",
            titleDE: "Formteile benennen",
            titleZH: "曲式部分命名",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if2/formteile/hoeren-abgrenzen",
                level: 3,
                code: "",
                titleDE: "Formteile hören und abgrenzen",
                titleZH: "听辨并划分段落",
                operatoren: ["analysieren", "gliedern"],
                klausurDE: "Typische Analysefrage im Gespräch: Das Beispiel gliedern und Grenzen benennen.",
                klausurZH: "典型分析题：划分段落并命名",
                leitfrageDE: "Wo beginnt ein neuer Formteil und woran höre ich das?",
                leitfrageZH: "新段落从哪里开始、我怎么听出来的？",
                noteKeywords: ["formteile", "gliederung", "hoeren", "grenze"],
                children: [],
              },
              {
                id: "musik/if2/formteile/wiederholung-kontrast",
                level: 3,
                code: "",
                titleDE: "Wiederholung und Kontrast",
                titleZH: "重复与对比",
                operatoren: ["analysieren", "vergleichen"],
                klausurDE: "Mündliche Vertiefung: Die Gliederung am Beispiel belegen, Wiederkehr gegen Kontrast stellen.",
                klausurZH: "口试追问层：指出哪里重复哪里对比，用实例论证",
                leitfrageDE: "Was kehrt wieder und was setzt Kontrast?",
                leitfrageZH: "什么在重复、什么形成对比？",
                noteKeywords: ["wiederholung", "kontrast", "beleg", "vergleich"],
                children: [],
              },
              {
                id: "musik/if2/formteile/formbegriff",
                level: 3,
                code: "",
                titleDE: "Formbegriff anwenden",
                titleZH: "运用曲式概念",
                operatoren: ["einordnen", "begründen"],
                klausurDE: "Mündlicher Schlusssatz der Analyse: Gehörtes in einen passenden Formbegriff einordnen und begründen.",
                klausurZH: "口试分析结论句：把段落装进合适的曲式概念",
                leitfrageDE: "Welcher Formbegriff passt und warum?",
                leitfrageZH: "哪个曲式概念合适、为什么？",
                noteKeywords: ["formbegriff", "einordnung", "begruendung", "schluss"],
                children: [],
              },
            ],
          },
          {
            id: "musik/if2/wirkung",
            level: 2,
            code: "",
            titleDE: "Wirkung erklären",
            titleZH: "效果解释",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if2/wirkung/parameter-wirkung",
                level: 3,
                code: "",
                titleDE: "Parameter zu Wirkung",
                titleZH: "从参数到效果",
                operatoren: ["erklären", "begründen"],
                klausurDE: "Kernsatz der Analysefrage: Jede Wirkungsaussage mit einem Parameter belegen, Satzmuster Das wirkt weil.",
                klausurZH: "口试分析核心句型：每个效果判断绑定参数证据",
                leitfrageDE: "Welche Wirkung hat der Parameter und warum?",
                leitfrageZH: "这个参数产生了什么效果、为什么？",
                noteKeywords: ["wirkung", "parameter", "beleg", "weil"],
                children: [],
              },
              {
                id: "musik/if2/wirkung/spannung-ausdruck",
                level: 3,
                code: "",
                titleDE: "Spannung und Ausdruck",
                titleZH: "张力与表现",
                operatoren: ["beschreiben", "deuten"],
                klausurDE: "Mündliche Vertiefung im Gespräch: Die Ausdruckskurve mit Auf- und Abbau der Spannung beschreiben.",
                klausurZH: "口试对话深化追问：描述张力起伏与表情变化",
                leitfrageDE: "Wie baut sich Spannung auf und ab?",
                leitfrageZH: "张力如何起伏？",
                noteKeywords: ["spannung", "ausdruck", "kurve", "deutung"],
                children: [],
              },
              {
                id: "musik/if2/wirkung/abschnitte-vergleichen",
                level: 3,
                code: "",
                titleDE: "Zwei Abschnitte vergleichen",
                titleZH: "比较两个段落",
                operatoren: ["vergleichen", "analysieren"],
                klausurDE: "Häufige Vergleichsfrage: Zwei Teile mit denselben Parametern gegenüberstellen, Unterschiede als These.",
                klausurZH: "常见对比型分析题：用同一组参数对比两段",
                leitfrageDE: "Worin unterscheiden sich die Abschnitte klanglich?",
                leitfrageZH: "两个段落在声音上有何不同？",
                noteKeywords: ["vergleich", "abschnitte", "parameter", "unterschied"],
                children: [],
              },
            ],
          },
          {
            id: "musik/if2/einordnung-deutung",
            level: 2,
            code: "",
            titleDE: "Einordnung und Deutung",
            titleZH: "定位与阐释",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if2/einordnung-deutung/epochenzuordnung",
                level: 3,
                code: "",
                titleDE: "Epochenzuordnung begründen",
                titleZH: "论证时代归属",
                operatoren: ["zuordnen", "begründen"],
                klausurDE: "Mündlicher Abschluss der Analyse: Stilistisch einordnen und mit mindestens zwei Klangbelegen stützen.",
                klausurZH: "口试分析收尾定位题：给出时代判断加至少两个证据",
                leitfrageDE: "Für welche Epoche sprechen die Merkmale?",
                leitfrageZH: "这些特征指向哪个时代？",
                noteKeywords: ["epoche", "zuordnung", "beleg", "stil"],
                children: [],
              },
              {
                id: "musik/if2/einordnung-deutung/funktion-kontext",
                level: 3,
                code: "",
                titleDE: "Funktion und Kontext",
                titleZH: "功能与语境",
                operatoren: ["einordnen", "erläutern"],
                klausurDE: "Mündliche Kontextfrage im Gespräch: Mögliche Funktion und Anlass nennen, ohne erfundene Details.",
                klausurZH: "口试语境追问：说出可能场合与功能，不编细节",
                leitfrageDE: "In welchem Kontext könnte diese Musik stehen?",
                leitfrageZH: "这段音乐可能处于什么语境？",
                noteKeywords: ["funktion", "kontext", "anlass", "einordnung"],
                children: [],
              },
              {
                id: "musik/if2/einordnung-deutung/deutungshypothese",
                level: 3,
                code: "",
                titleDE: "Deutungshypothese formulieren",
                titleZH: "提出阐释假设",
                operatoren: ["deuten", "beurteilen"],
                klausurDE: "Offener Abschluss von Vortrag und Gespräch: Eine prüfbare Deutung vorsichtig formulieren, zeigt Reflexion.",
                klausurZH: "口试开放收尾：用可能表达句式提假设，展示反思",
                leitfrageDE: "Welche Deutung lässt das Gehörte zu?",
                leitfrageZH: "听到的内容允许哪种理解？",
                noteKeywords: ["deutung", "hypothese", "reflexion", "vortrag"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "musik/if3",
        level: 1,
        code: "IF 3",
        titleDE: "Sprechen und Reflektieren",
        titleZH: "表达与反思",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "musik/if3/eigene-praxis",
            level: 2,
            code: "",
            titleDE: "Eigene Praxis vorstellen",
            titleZH: "介绍个人实践",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if3/eigene-praxis/stueck-praxis",
                level: 3,
                code: "",
                titleDE: "Stück und Praxis beschreiben",
                titleZH: "描述曲目与实践",
                operatoren: ["darstellen", "beschreiben"],
                klausurDE: "Auftakt des Vortrags zur eigenen Praxis: Stück und eigene Rolle darin vorstellen, schafft Glaubwürdigkeit.",
                klausurZH: "口试陈述开场：说清曲目要点与声部角色",
                leitfrageDE: "Was spiele/singe ich und was ist daran typisch?",
                leitfrageZH: "我演奏/演唱什么、其典型之处是什么？",
                noteKeywords: ["praxis", "stueck", "rolle", "vortrag"],
                children: [],
              },
              {
                id: "musik/if3/eigene-praxis/schwierigkeit-uebeweg",
                level: 3,
                code: "",
                titleDE: "Schwierigkeit und Übeweg benennen",
                titleZH: "说出难点与练习方法",
                operatoren: ["erläutern", "reflektieren"],
                klausurDE: "Mittelteil des Vortrags: Eine konkrete Schwierigkeit und die eigenen Übeschritte erläutern.",
                klausurZH: "口试陈述中段：点名一处难点与解决步骤",
                leitfrageDE: "Wo lag die Schwierigkeit und wie habe ich geübt?",
                leitfrageZH: "难点在哪里、我如何练习？",
                noteKeywords: ["schwierigkeit", "ueben", "methode", "reflexion"],
                children: [],
              },
              {
                id: "musik/if3/eigene-praxis/vortragssituation",
                level: 3,
                code: "",
                titleDE: "Vortragssituation bewältigen",
                titleZH: "应对演奏陈述场合",
                operatoren: ["präsentieren", "darstellen"],
                klausurDE: "Formnote des Vortrags: Zeit einhalten, klar sprechen, Raum für Rückfragen lassen.",
                klausurZH: "口试陈述形式分：守时清楚，留出问答时间",
                leitfrageDE: "Bleibe ich in der Zeit und bleibe ich verständlich?",
                leitfrageZH: "我守时且表达清楚吗？",
                noteKeywords: ["vortrag", "zeit", "sprache", "praesentation"],
                children: [],
              },
            ],
          },
          {
            id: "musik/if3/referat-gespraech",
            level: 2,
            code: "",
            titleDE: "Referat und Gespräch",
            titleZH: "陈述与对话",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if3/referat-gespraech/referat-struktur",
                level: 3,
                code: "",
                titleDE: "Referat strukturieren",
                titleZH: "组织小报告结构",
                operatoren: ["darstellen", "gliedern"],
                klausurDE: "Strukturnote für Vortrag und Referat: In These, Beleg und Fazit gliedern.",
                klausurZH: "口试报告结构分：论点论据结论三段",
                leitfrageDE: "Hat mein Referat These, Beleg und Fazit?",
                leitfrageZH: "我的报告有论点、论据和结论吗？",
                noteKeywords: ["referat", "these", "beleg", "fazit"],
                children: [],
              },
              {
                id: "musik/if3/referat-gespraech/nachfragen",
                level: 3,
                code: "",
                titleDE: "Auf Nachfragen antworten",
                titleZH: "回答追问",
                operatoren: ["erläutern", "begründen"],
                klausurDE: "Gesprächsphase: Frage kurz wiederholen, dann präzise antworten, Grenzen offen benennen.",
                klausurZH: "口试对话环节：先复述问题再答，不确定说清边界",
                leitfrageDE: "Beantworte ich die Nachfrage präzise?",
                leitfrageZH: "我精确回答了追问吗？",
                noteKeywords: ["nachfrage", "antwort", "gespraech", "praezision"],
                children: [],
              },
              {
                id: "musik/if3/referat-gespraech/fachgespraech",
                level: 3,
                code: "",
                titleDE: "Fachgespräch führen",
                titleZH: "进行专业对话",
                operatoren: ["erörtern", "begründen"],
                klausurDE: "Gesamteindruck im Gespräch: Fachlich bleiben, Begriffe ans Hörbeispiel rückbinden, beim Thema bleiben.",
                klausurZH: "口试对话印象分：术语回扣听例，不跑题",
                leitfrageDE: "Bleibe ich fachlich und beim Beispiel?",
                leitfrageZH: "我始终专业且紧扣例曲吗？",
                noteKeywords: ["fachgespraech", "kohaerenz", "fachlichkeit", "beispiel"],
                children: [],
              },
            ],
          },
          {
            id: "musik/if3/bewertung",
            level: 2,
            code: "",
            titleDE: "Bewertung begründen",
            titleZH: "评价论证",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "musik/if3/bewertung/kriterien",
                level: 3,
                code: "",
                titleDE: "Kriterien nennen",
                titleZH: "说出评价标准",
                operatoren: ["benennen", "definieren"],
                klausurDE: "Auftakt der Urteilsaufgabe Bewerten Sie: Erst Kriterien wie Intonation, Rhythmus und Ausdruck nennen.",
                klausurZH: "口试评价题开头：先亮标准再下判断",
                leitfrageDE: "Nach welchen Kriterien urteile ich?",
                leitfrageZH: "我按什么标准评价？",
                noteKeywords: ["kriterien", "massstab", "urteil", "benennen"],
                children: [],
              },
              {
                id: "musik/if3/bewertung/urteil-fachbegriff",
                level: 3,
                code: "",
                titleDE: "Urteil mit Fachbegriff stützen",
                titleZH: "用术语支撑判断",
                operatoren: ["beurteilen", "begründen"],
                klausurDE: "Kern der Urteilsaufgabe: Jedes gut oder schwach mit einem Fachbeleg stützen, Muster Das wirkt weil.",
                klausurZH: "口试评价论证核心：每个好坏后面跟术语证据",
                leitfrageDE: "Womit belege ich mein Urteil fachlich?",
                leitfrageZH: "我用什么专业证据支撑判断？",
                noteKeywords: ["urteil", "beleg", "fachbegriff", "begruendung"],
                children: [],
              },
              {
                id: "musik/if3/bewertung/selbstreflexion",
                level: 3,
                code: "",
                titleDE: "Selbstreflexion",
                titleZH: "自我反思",
                operatoren: ["reflektieren", "bewerten"],
                klausurDE: "Gesprächsabschluss: Die eigene Leistung einschätzen, Stärken und nächste Schritte nennen.",
                klausurZH: "口试对话收尾：说哪里强下次改哪里",
                leitfrageDE: "Was war stark und was verbessere ich?",
                leitfrageZH: "哪里强、下次改哪里？",
                noteKeywords: ["selbstreflexion", "staerken", "ziel", "einschaetzung"],
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
};
