import type { FachBaum } from "./types";

export const philosophieBaum: FachBaum = {
  fach: "Philosophie",
  nameDE: "Philosophie",
  nameZH: "哲学",
  klpReferenz: "NRW Kernlehrplan GeWi EF: IF 1 Anthropologie, IF 2 Ethik",
  klausurFokusDE: "Textanalyse mit Argumentrekonstruktion (Prämisse zu Konklusion) plus kriteriengeleitete Erörterung mit eigenem Urteil",
  klausurFokusZH: "文本细读、重构论证再评价：先说文本主张什么，再摆理由，最后给判断",
  root: {
    id: "philosophie",
    level: 0,
    code: "",
    titleDE: "Philosophie",
    titleZH: "哲学",
    operatoren: [],
    klausurDE: "",
    klausurZH: "",
    leitfrageDE: "",
    leitfrageZH: "",
    noteKeywords: [],
    children: [
      {
        id: "philosophie/if1",
        level: 1,
        code: "IF 1",
        titleDE: "Anthropologie und Menschenbilder",
        titleZH: "人类学与人像观",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "philosophie/if1/menschenbild-freiheit",
            level: 2,
            code: "",
            titleDE: "Menschenbild und Freiheit",
            titleZH: "人像观与自由",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "philosophie/if1/menschenbild-freiheit/freiheitsbegriff",
                level: 3,
                code: "",
                titleDE: "Freiheitsbegriff negativ und positiv",
                titleZH: "消极与积极自由之分",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Texteinstieg: Die These des Textes bestimmen und sein Freiheitsverständnis in eigenen Worten wiedergeben.",
                klausurZH: "文本分析开头：找出主张，说清文本用的是哪种自由",
                leitfrageDE: "Welcher Freiheitsbegriff liegt der Textthese zugrunde?",
                leitfrageZH: "文本主张背后是哪一种自由概念？",
                noteKeywords: ["freiheit", "negativ-positiv", "textthese"],
                children: [],
              },
              {
                id: "philosophie/if1/menschenbild-freiheit/determinismusfrage",
                level: 3,
                code: "",
                titleDE: "Determinismus-Frage",
                titleZH: "决定论之问",
                operatoren: ["darstellen", "erörtern"],
                klausurDE: "Erörterung mit Pro und Kontra: Beide Seiten am Kriterium Freiheit abwägen und ein eigenes Urteil formulieren.",
                klausurZH: "正反论述：两边各写成前提，用自由标准权衡后下判断",
                leitfrageDE: "Ist der Mensch frei oder determiniert?",
                leitfrageZH: "人是自由的还是被决定的？",
                noteKeywords: ["determinismus", "freiheit", "pro-contra"],
                children: [],
              },
              {
                id: "philosophie/if1/menschenbild-freiheit/sartre-entwurf",
                level: 3,
                code: "",
                titleDE: "Sartre Entwurf: Existenz geht der Essenz voraus",
                titleZH: "萨特：存在先于本质",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Argumentrekonstruktion von Prämisse zur Konklusion: Sartres These herausarbeiten und mit einem Alltagsbeispiel belegen.",
                klausurZH: "论证重构：摆出萨特前提和结论，再配一个生活例子",
                leitfrageDE: "Was folgt daraus, dass Existenz der Essenz vorausgeht?",
                leitfrageZH: "“存在先于本质”会推出什么结论？",
                noteKeywords: ["sartre", "existenz-essenz", "entwurf", "wahl"],
                children: [],
              },
            ],
          },
          {
            id: "philosophie/if1/vernunft-natur-kultur",
            level: 2,
            code: "",
            titleDE: "Vernunft, Natur und Kultur",
            titleZH: "理性、自然与文化",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "philosophie/if1/vernunft-natur-kultur/vernunftbegriff",
                level: 3,
                code: "",
                titleDE: "Vernunftbegriff",
                titleZH: "理性概念",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Textanalyse: Den Vernunftbegriff des Textes herausarbeiten und mit einem Beispiel belegen.",
                klausurZH: "文本分析：找出文本的理性概念并举例说明",
                leitfrageDE: "Was macht Vernunft zum Merkmal des Menschen?",
                leitfrageZH: "理性凭什么成为人的标志？",
                noteKeywords: ["vernunft", "selbstgesetzgebung", "merkmal"],
                children: [],
              },
              {
                id: "philosophie/if1/vernunft-natur-kultur/natur-kultur-spannung",
                level: 3,
                code: "",
                titleDE: "Natur-Kultur-Spannung",
                titleZH: "自然与文化的张力",
                operatoren: ["darstellen", "erörtern"],
                klausurDE: "Erörterung mit Kriterium: Natur-Argument und Kultur-Argument gegeneinander abwägen und begründet urteilen.",
                klausurZH: "论述：自然论据和文化论据对照权衡，给出有理由的判断",
                leitfrageDE: "Bestimmt Natur oder Kultur den Menschen stärker?",
                leitfrageZH: "决定人的更多是自然还是文化？",
                noteKeywords: ["natur", "kultur", "anlage-umwelt", "kriterium"],
                children: [],
              },
              {
                id: "philosophie/if1/vernunft-natur-kultur/sprache-gemeinschaft",
                level: 3,
                code: "",
                titleDE: "Sprache und Gemeinschaft",
                titleZH: "语言与共同体",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Textanalyse am Schluss: Ein Textbeispiel auf Sprache und Gemeinschaft beziehen und kurz am Kriterium Menschenwürde bewerten.",
                klausurZH: "文本分析收尾：把例子挂到语言和共同体上，用尊严标准简评",
                leitfrageDE: "Wird der Mensch erst in Gemeinschaft zum Menschen?",
                leitfrageZH: "人是否只有在共同体中才成其为人？",
                noteKeywords: ["sprache", "gemeinschaft", "menschenwuerde"],
                children: [],
              },
            ],
          },
          {
            id: "philosophie/if1/positionen-vergleich",
            level: 2,
            code: "",
            titleDE: "Positionen im Vergleich",
            titleZH: "经典立场与比较",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "philosophie/if1/positionen-vergleich/kant-vernunftwesen",
                level: 3,
                code: "",
                titleDE: "Kant-Ansatz: Vernunftwesen",
                titleZH: "康德进路：人是理性存在者",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Argumentrekonstruktion: Aus der Prämisse Vernunft die Konklusion Würde und Selbstgesetzgebung ableiten, plus Beispiel.",
                klausurZH: "论证重构：从理性前提推出尊严和自我立法结论，配例子",
                leitfrageDE: "Warum begründet Vernunft Würde?",
                leitfrageZH: "理性为什么能推出尊严？",
                noteKeywords: ["kant", "vernunftwesen", "wuerde", "selbstgesetzgebung"],
                children: [],
              },
              {
                id: "philosophie/if1/positionen-vergleich/sartre-existenzialismus",
                level: 3,
                code: "",
                titleDE: "Sartre Existenzialismus",
                titleZH: "萨特存在主义",
                operatoren: ["darstellen", "erörtern"],
                klausurDE: "Erörterung: Sartres Position mit Pro und Kontra prüfen und am Kriterium Freiheit beurteilen.",
                klausurZH: "论述：正反两面检验萨特立场，用自由标准评价",
                leitfrageDE: "Macht radikale Freiheit den Menschen überfordert?",
                leitfrageZH: "彻底的自由会不会压垮人？",
                noteKeywords: ["sartre", "freiheit", "verantwortung", "pro-contra"],
                children: [],
              },
              {
                id: "philosophie/if1/positionen-vergleich/vergleich-menschenbilder",
                level: 3,
                code: "",
                titleDE: "Vergleich der Menschenbilder",
                titleZH: "人像观比较",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Erörterung und Urteil: Positionen mit gemeinsamem Kriterium vergleichen und eine eigene Stellung formulieren.",
                klausurZH: "论述收束：用同一标准比较立场，写出自己的站位",
                leitfrageDE: "Welches Menschenbild überzeugt unter dem Kriterium Menschenwürde?",
                leitfrageZH: "以人的尊严为标准，哪种人像观更有说服力？",
                noteKeywords: ["vergleich", "menschenbild", "menschenwuerde", "tabelle"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "philosophie/if2",
        level: 1,
        code: "IF 2",
        titleDE: "Ethik",
        titleZH: "伦理学",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "philosophie/if2/gewissen-verantwortung-normen",
            level: 2,
            code: "",
            titleDE: "Gewissen, Verantwortung und Normen",
            titleZH: "良知、责任与规范",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "philosophie/if2/gewissen-verantwortung-normen/gewissen-begriff",
                level: 3,
                code: "",
                titleDE: "Gewissen-Begriff",
                titleZH: "良知概念",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Textanalyse: Das Gewissensverständnis des Textes rekonstruieren und mit einem Beispiel veranschaulichen.",
                klausurZH: "文本分析：重构文本的良知理解，举例说明",
                leitfrageDE: "Ist das Gewissen angeboren oder gelernt?",
                leitfrageZH: "良知是天生的还是学来的？",
                noteKeywords: ["gewissen", "moral", "beispiel"],
                children: [],
              },
              {
                id: "philosophie/if2/gewissen-verantwortung-normen/verantwortung-dimensionen",
                level: 3,
                code: "",
                titleDE: "Verantwortung-Dimensionen",
                titleZH: "责任维度",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Erörterung und Urteil: Verantwortung als Kriterium nennen und das eigene Urteil daran prüfen.",
                klausurZH: "论述评价：把责任当标准，用它检验自己的判断",
                leitfrageDE: "Wofür und vor wem sind wir verantwortlich?",
                leitfrageZH: "我们对什么、向谁负责？",
                noteKeywords: ["verantwortung", "kriterium", "urteil"],
                children: [],
              },
              {
                id: "philosophie/if2/gewissen-verantwortung-normen/normen-werte-regeln",
                level: 3,
                code: "",
                titleDE: "Normen, Werte und Regeln",
                titleZH: "规范、价值与规则之分",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Texteinstieg: Norm, Wert und Regel im Text sauber unterscheiden und zuordnen.",
                klausurZH: "文本分析开头：把规范、价值、规则分清并归位",
                leitfrageDE: "Wann wird ein Wert zur verbindlichen Norm?",
                leitfrageZH: "价值何时变成有约束力的规范？",
                noteKeywords: ["normen", "werte", "regeln", "zuordnung"],
                children: [],
              },
            ],
          },
          {
            id: "philosophie/if2/utilitarismus",
            level: 2,
            code: "",
            titleDE: "Utilitarismus",
            titleZH: "功利主义",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "philosophie/if2/utilitarismus/nutzen-folgenprinzip",
                level: 3,
                code: "",
                titleDE: "Nutzen- und Folgenprinzip",
                titleZH: "效用与后果原则",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Argumentrekonstruktion: Aus dem Folgenkalkül als Prämisse die gebotene oder verbotene Handlung ableiten, plus Beispiel.",
                klausurZH: "论证重构：从后果计算推出该做或不该做，配例子",
                leitfrageDE: "Darf eine gute Folge ein problematisches Mittel rechtfertigen?",
                leitfrageZH: "好的后果能让有问题的手段正当吗？",
                noteKeywords: ["utilitarismus", "folgen", "nutzen", "konklusion"],
                children: [],
              },
              {
                id: "philosophie/if2/utilitarismus/handlungs-regelutilitarismus",
                level: 3,
                code: "",
                titleDE: "Handlungs- versus Regelutilitarismus",
                titleZH: "行为与规则功利之分",
                operatoren: ["darstellen", "erörtern"],
                klausurDE: "Erörterung mit Pro und Kontra: Beide Varianten gegeneinander abwägen und das Kriterium Gerechtigkeit nennen.",
                klausurZH: "正反论述：比较两个版本，用公正标准权衡",
                leitfrageDE: "Reicht der Einzelfall oder braucht es eine allgemeine Regel?",
                leitfrageZH: "只看个案够吗，还是需要一般规则？",
                noteKeywords: ["handlung", "regel", "gerechtigkeit", "pro-contra"],
                children: [],
              },
              {
                id: "philosophie/if2/utilitarismus/kritik-einwaende",
                level: 3,
                code: "",
                titleDE: "Kritik und Einwände",
                titleZH: "对功利主义的批评",
                operatoren: ["erörtern", "beurteilen"],
                klausurDE: "Urteilsteil: Die Einwände an den Kriterien Menschenwürde und Gerechtigkeit prüfen und Stellung nehmen.",
                klausurZH: "评价段：用尊严和公正标准检验反驳，给出站位",
                leitfrageDE: "Schützt der Utilitarismus Minderheiten ausreichend?",
                leitfrageZH: "功利主义能保护少数人吗？",
                noteKeywords: ["kritik", "minderheit", "menschenwuerde", "gerechtigkeit"],
                children: [],
              },
            ],
          },
          {
            id: "philosophie/if2/pflichtethik-kant",
            level: 2,
            code: "",
            titleDE: "Pflichtethik nach Kant",
            titleZH: "义务论与康德",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "philosophie/if2/pflichtethik-kant/maxime-pflicht",
                level: 3,
                code: "",
                titleDE: "Maxime und Pflicht",
                titleZH: "准则与义务",
                operatoren: ["darstellen", "rekonstruieren"],
                klausurDE: "Textanalyse: Die Maxime der Textfigur ausformulieren und den Pflichtanspruch rekonstruieren.",
                klausurZH: "文本分析：写出人物准则，重构其义务要求",
                leitfrageDE: "Was unterscheidet eine Maxime von einer Gewohnheit?",
                leitfrageZH: "准则和习惯有什么区别？",
                noteKeywords: ["maxime", "pflicht", "kant", "beispiel"],
                children: [],
              },
              {
                id: "philosophie/if2/pflichtethik-kant/universalisierung",
                level: 3,
                code: "",
                titleDE: "Universalisierungsformel",
                titleZH: "普遍化公式",
                operatoren: ["rekonstruieren", "beurteilen"],
                klausurDE: "Argumentrekonstruktion mit Prüfung: Maxime aufstellen, den Universalisierungstest durchführen und das Ergebnis beurteilen.",
                klausurZH: "重构加检验：列出准则，做普遍化测试并评价结果",
                leitfrageDE: "Besteht meine Maxime den Universalisierungstest?",
                leitfrageZH: "我的准则能通过普遍化检验吗？",
                noteKeywords: ["universalisierung", "test", "maxime", "kant"],
                children: [],
              },
              {
                id: "philosophie/if2/pflichtethik-kant/menschheitszweck",
                level: 3,
                code: "",
                titleDE: "Menschheitszweckformel",
                titleZH: "目的公式",
                operatoren: ["darstellen", "Stellung nehmen"],
                klausurDE: "Erörterung und Urteil: Einen Fall mit der Menschheitszweckformel prüfen und die eigene Stellung am Kriterium Menschenwürde festmachen.",
                klausurZH: "论述评价：用目的公式检验案例，以尊严为标准表态",
                leitfrageDE: "Wo wird ein Mensch bloß als Mittel benutzt?",
                leitfrageZH: "哪里有人只被当成了手段？",
                noteKeywords: ["zweckformel", "mittel", "menschenwuerde", "kant"],
                children: [],
              },
            ],
          },
          {
            id: "philosophie/if2/tugend-vergleich",
            level: 2,
            code: "",
            titleDE: "Tugend-Ansätze und Modellvergleich",
            titleZH: "德性进路与模型比较",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "philosophie/if2/tugend-vergleich/tugend-charakter",
                level: 3,
                code: "",
                titleDE: "Tugend und Charakter",
                titleZH: "德性与品格",
                operatoren: ["darstellen", "erörtern"],
                klausurDE: "Erörterung: Die Tugendperspektive als drittes Argument in die Pro- und Kontra-Abwägung einführen.",
                klausurZH: "论述：把德性视角作为第三条论据引入正反权衡",
                leitfrageDE: "Zählt die Tat oder der Charakter?",
                leitfrageZH: "算数的是行为还是品格？",
                noteKeywords: ["tugend", "charakter", "pro-contra"],
                children: [],
              },
              {
                id: "philosophie/if2/tugend-vergleich/glueck-gelingen",
                level: 3,
                code: "",
                titleDE: "Glück und Gelingen",
                titleZH: "幸福与圆满",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Urteilsteil: Gelingen als zusätzliches Kriterium nennen und kurz abwägen.",
                klausurZH: "评价段：把圆满生活作为补充标准简要权衡",
                leitfrageDE: "Gehört Glück zur Moral dazu?",
                leitfrageZH: "幸福属于道德的一部分吗？",
                noteKeywords: ["glueck", "gelingen", "kriterium", "urteil"],
                children: [],
              },
              {
                id: "philosophie/if2/tugend-vergleich/vergleich-modelle",
                level: 3,
                code: "",
                titleDE: "Vergleich Utilitarismus versus Kant",
                titleZH: "两大模型比较与选用",
                operatoren: ["erörtern", "beurteilen"],
                klausurDE: "Erörterung am Schluss: Beide Modelle mit gleichem Kriterium wie Freiheit, Gerechtigkeit oder Menschenwürde vergleichen und begründet urteilen.",
                klausurZH: "收束论述：用同一标准比较两大模型，给出有理由的判断",
                leitfrageDE: "Folgen oder Pflicht — was überzeugt im Fall?",
                leitfrageZH: "后果还是义务——在这个案例中谁更有说服力？",
                noteKeywords: ["vergleich", "folgen", "pflicht", "kriterium"],
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
};
