import type { FachBaum } from "./types";
export const physikBaum: FachBaum = { fach: "Physik", nameDE: "Physik", nameZH: "物理", klpReferenz: "NRW KLP Physik 2022", klausurFokusDE: "Experiment-Auswertung + Diagramm-Deutung Pflicht; Lösungsweg gegeben/gesucht zu Ansatz zu Rechnung zu Bewertung", klausurFokusZH: "实验分析与图像解读必考；按已知/求解→思路→计算→评价四步作答", root: { id: "physik", level: 0, code: "", titleDE: "Physik", titleZH: "物理", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if1", level: 1, code: "IF 1", titleDE: "Grundlagen der Mechanik", titleZH: "力学基础", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if1/kinematik", level: 2, code: "", titleDE: "Kinematik", titleZH: "运动学", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if1/kinematik/gleichfoermige-bewegung", level: 3, code: "", titleDE: "Gleichförmige Bewegung", titleZH: "匀速运动", operatoren: ["beschreiben", "berechnen", "darstellen"], klausurDE: "s-t-/v-t-Diagramm lesen und Weg berechnen (AFB I). Diagramm-Deutung Pflicht.", klausurZH: "基础计算加图像题：读 s-t/v-t 图像并求位移（AFB I）；图像解读必考。", leitfrageDE: "Woran erkennt man eine gleichförmige Bewegung im Diagramm?", leitfrageZH: "如何从图像认出匀速运动？", noteKeywords: ["gleichfoermige", "diagramm", "kinematik", "geschwindigkeit"], children: [] },
{ id: "physik/if1/kinematik/gleichmaessig-beschleunigte-bewegung", level: 3, code: "", titleDE: "Gleichmäßig beschleunigte Bewegung", titleZH: "匀加速运动", operatoren: ["beschreiben", "berechnen", "begründen"], klausurDE: "Standardrechnung: gegeben/gesucht zu Formelwahl zu Rechnung mit Einheiten.", klausurZH: "标准计算题：已知/求解→选公式→带单位计算。", leitfrageDE: "Wie hängen Weg, Zeit und Beschleunigung zusammen?", leitfrageZH: "位移、时间和加速度有什么关系？", noteKeywords: ["beschleunigt", "kinematik", "formel", "einheiten"], children: [] },
{ id: "physik/if1/kinematik/freier-fall", level: 3, code: "", titleDE: "Freier Fall", titleZH: "自由落体", operatoren: ["beschreiben", "berechnen", "auswerten"], klausurDE: "Fallzeit messen, g bestimmen, Abweichung bewerten. Experiment-Auswertung Pflicht.", klausurZH: "实验加计算综合：测下落时间、定 g、评价偏差；实验分析必考。", leitfrageDE: "Warum fällt alles im Vakuum gleich schnell?", leitfrageZH: "为什么真空中所有东西下落一样快？", noteKeywords: ["freier fall", "erdbeschleunigung", "experiment", "auswertung"], children: [] },
{ id: "physik/if1/kinematik/diagramme-weg-zeit-geschwindigkeit", level: 3, code: "", titleDE: "Diagramme: Weg, Zeit, Geschwindigkeit", titleZH: "位移—时间—速度图像", operatoren: ["auswerten", "deuten", "darstellen"], klausurDE: "Steigung/Flaeche deuten, Graphen umzeichnen. Diagramm-Deutung Pflicht.", klausurZH: "图像解读必考：解释斜率与面积并重画图像。", leitfrageDE: "Was bedeuten Steigung und Fläche im Diagramm?", leitfrageZH: "图像中的斜率和面积代表什么？", noteKeywords: ["diagramm", "steigung", "flaeche", "deutung"], children: [] }
] },
{ id: "physik/if1/dynamik", level: 2, code: "", titleDE: "Dynamik", titleZH: "牛顿动力学", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if1/dynamik/newton-gesetze", level: 3, code: "", titleDE: "Newton'sche Gesetze", titleZH: "牛顿三定律", operatoren: ["nennen", "beschreiben", "erklären"], klausurDE: "Alltagsphänomen einem Newton-Gesetz zuordnen (AFB I-II).", klausurZH: "概念解释题：把生活现象归入牛顿定律（AFB I-II）。", leitfrageDE: "Welches Newton-Gesetz erklärt das Phänomen?", leitfrageZH: "这个现象用牛顿哪条定律解释？", noteKeywords: ["newton", "traegheit", "kraft", "dynamik"], children: [] },
{ id: "physik/if1/dynamik/kraeftegleichgewicht", level: 3, code: "", titleDE: "Kräftegleichgewicht", titleZH: "受力平衡", operatoren: ["darstellen", "begründen", "berechnen"], klausurDE: "Kräfteplan zeichnen, Gleichgewicht begründen. Lösungsweg: gegeben/gesucht zu Ansatz zu Rechnung zu Bewertung.", klausurZH: "受力分析题：画受力图并证明平衡；按已知/求解→思路→计算→评价作答。", leitfrageDE: "Wie zeigt man Kräftegleichgewicht?", leitfrageZH: "如何证明受力平衡？", noteKeywords: ["kraefteplan", "gleichgewicht", "kraft", "zeichnung"], children: [] },
{ id: "physik/if1/dynamik/reibung", level: 3, code: "", titleDE: "Reibung", titleZH: "摩擦力", operatoren: ["beschreiben", "erklären", "bewerten"], klausurDE: "Reibung als Fehlerquelle benennen und bewerten. Experiment-Auswertung Pflicht.", klausurZH: "实验评价题：指出摩擦为误差来源并评价；实验分析必考。", leitfrageDE: "Wie beeinflusst Reibung Messung und Bewegung?", leitfrageZH: "摩擦如何影响测量和运动？", noteKeywords: ["reibung", "fehlerquelle", "messung", "bewertung"], children: [] }
] },
{ id: "physik/if1/erhaltungssaetze", level: 2, code: "", titleDE: "Erhaltungssätze", titleZH: "守恒定律与碰撞", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if1/erhaltungssaetze/energieformen", level: 3, code: "", titleDE: "Energieformen: Lage, Bewegung, Spannung", titleZH: "能量形式：势能、动能、弹性势能", operatoren: ["nennen", "beschreiben", "berechnen"], klausurDE: "Energieumwandlung beschreiben, Größen berechnen.", klausurZH: "能量计算题：描述能量转化并计算各量。", leitfrageDE: "Welche Energieformen wandeln sich um?", leitfrageZH: "哪些能量形式在互相转化？", noteKeywords: ["energie", "lageenergie", "bewegungsenergie", "umwandlung"], children: [] },
{ id: "physik/if1/erhaltungssaetze/impuls", level: 3, code: "", titleDE: "Impuls", titleZH: "动量", operatoren: ["beschreiben", "erklären", "berechnen"], klausurDE: "Impulserhaltung als Ansatz wählen und begründen.", klausurZH: "守恒应用题：选用动量守恒作思路并说明理由。", leitfrageDE: "Wann bleibt der Impuls erhalten?", leitfrageZH: "动量何时守恒？", noteKeywords: ["impuls", "impulserhaltung", "stoss", "ansatz"], children: [] },
{ id: "physik/if1/erhaltungssaetze/stoss-eindimensional", level: 3, code: "", titleDE: "Stoßvorgänge eindimensional", titleZH: "一维碰撞", operatoren: ["auswerten", "berechnen", "bewerten"], klausurDE: "Stoß auswerten, elastisch vs. unelastisch unterscheiden. Experiment-Auswertung und Bewertung.", klausurZH: "综合大题：分析碰撞并区分弹性与非弹性；实验分析与评价。", leitfrageDE: "Elastisch oder unelastisch - woran erkennt man es?", leitfrageZH: "如何区分弹性与非弹性碰撞？", noteKeywords: ["stoss", "elastisch", "unelastisch", "auswertung"], children: [] }
] },
{ id: "physik/if1/experiment-auswertung", level: 2, code: "", titleDE: "Experiment und Auswertung", titleZH: "实验与数据处理", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if1/experiment-auswertung/messen-unsicherheit", level: 3, code: "", titleDE: "Messen und Unsicherheit", titleZH: "测量与误差", operatoren: ["beschreiben", "auswerten", "bewerten"], klausurDE: "Messunsicherheit angeben, Fehlerquellen nennen. Experiment-Auswertung Pflicht.", klausurZH: "实验题开头：写出不确定度并列出误差来源；实验分析必考。", leitfrageDE: "Woher kommt die Messunsicherheit?", leitfrageZH: "测量不确定度从哪里来？", noteKeywords: ["messung", "messunsicherheit", "fehlerquelle", "experiment"], children: [] },
{ id: "physik/if1/experiment-auswertung/digitale-auswertung", level: 3, code: "", titleDE: "Digitale Messdatenauswertung", titleZH: "数字化数据处理", operatoren: ["auswerten", "darstellen", "beschreiben"], klausurDE: "Messdaten fitten, Parameter bestimmen. Experiment-Auswertung Pflicht.", klausurZH: "数字化处理必考：拟合测量数据并确定参数；实验分析必考。", leitfrageDE: "Wie gewinnt man aus Messdaten eine physikalische Größe?", leitfrageZH: "如何从测量数据得到物理量？", noteKeywords: ["messdaten", "auswertung", "fit", "experiment"], children: [] },
{ id: "physik/if1/experiment-auswertung/diagramm-deutung", level: 3, code: "", titleDE: "Diagramm-Deutung", titleZH: "图像解读", operatoren: ["auswerten", "deuten", "bewerten"], klausurDE: "Diagramm beschreiben zu deuten zu Hypothese bewerten. Diagramm-Deutung Pflicht.", klausurZH: "必考环节：描述图像→解读→评价假设；图像解读必考。", leitfrageDE: "Was sagt das Diagramm über die Hypothese?", leitfrageZH: "图像对假设说了什么？", noteKeywords: ["diagramm", "deutung", "hypothese", "auswertung"], children: [] }
] }
] },
{ id: "physik/if2", level: 1, code: "IF 2", titleDE: "Kreisbewegung, Gravitation, Weltbilder", titleZH: "圆周运动、引力、世界观", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if2/kreisbewegung", level: 2, code: "", titleDE: "Kreisbewegung und Zentripetalkraft", titleZH: "圆周运动与向心力", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if2/kreisbewegung/gleichfoermige-kreisbewegung", level: 3, code: "", titleDE: "Gleichförmige Kreisbewegung", titleZH: "匀速圆周运动", operatoren: ["beschreiben", "berechnen", "darstellen"], klausurDE: "Umlaufdauer, Frequenz, Bahngeschwindigkeit berechnen.", klausurZH: "基础计算：求周期、频率和轨道速度。", leitfrageDE: "Was bleibt bei der Kreisbewegung konstant und was nicht?", leitfrageZH: "圆周运动中什么不变、什么在变？", noteKeywords: ["kreisbewegung", "umlaufdauer", "frequenz", "bahngeschwindigkeit"], children: [] },
{ id: "physik/if2/kreisbewegung/zentripetalkraft", level: 3, code: "", titleDE: "Zentripetalkraft", titleZH: "向心力", operatoren: ["erklären", "begründen", "berechnen"], klausurDE: "Zentripetalkraft herleiten und anwenden (AFB II).", klausurZH: "高频解释加计算：推导并应用向心力（AFB II）。", leitfrageDE: "Woher kommt die Zentripetalkraft?", leitfrageZH: "向心力从哪里来？", noteKeywords: ["zentripetalkraft", "kreisbewegung", "herleitung", "kraft"], children: [] },
{ id: "physik/if2/kreisbewegung/alltagsbeispiele", level: 3, code: "", titleDE: "Alltagsbeispiele", titleZH: "生活实例", operatoren: ["erklären", "bewerten", "beschreiben"], klausurDE: "Alltagsbeispiel mit Zentripetalkraft erklären, Sicherheit bewerten.", klausurZH: "情境评价题：用向心力解释生活实例并评价安全。", leitfrageDE: "Wer liefert hier die Zentripetalkraft?", leitfrageZH: "这个情景里谁提供向心力？", noteKeywords: ["alltag", "zentripetalkraft", "bewertung", "sicherheit"], children: [] }
] },
{ id: "physik/if2/gravitation-kepler", level: 2, code: "", titleDE: "Gravitation und Kepler", titleZH: "引力与开普勒", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if2/gravitation-kepler/gravitationsgesetz", level: 3, code: "", titleDE: "Newton'sches Gravitationsgesetz", titleZH: "万有引力定律", operatoren: ["beschreiben", "berechnen", "begründen"], klausurDE: "Gravitationskraft berechnen, Bezug zu g herstellen.", klausurZH: "计算题：求万有引力并联系重力加速度 g。", leitfrageDE: "Wie hängt die Schwerkraft vom Abstand ab?", leitfrageZH: "重力如何随距离变化？", noteKeywords: ["gravitation", "schwerkraft", "abstand", "berechnung"], children: [] },
{ id: "physik/if2/gravitation-kepler/kepler-gesetze", level: 3, code: "", titleDE: "Kepler'sche Gesetze", titleZH: "开普勒定律", operatoren: ["nennen", "beschreiben", "auswerten"], klausurDE: "Kepler-Gesetze an Planetendaten prüfen. Diagramm- und Datenauswertung.", klausurZH: "数据分析题：用行星数据检验开普勒定律；图表与数据分析。", leitfrageDE: "Was sagen die Kepler-Gesetze über Planetenbahnen?", leitfrageZH: "开普勒定律说了行星轨道的什么？", noteKeywords: ["kepler", "planetenbahn", "datenauswertung", "ellipse"], children: [] },
{ id: "physik/if2/gravitation-kepler/satelliten", level: 3, code: "", titleDE: "Satelliten", titleZH: "卫星运动", operatoren: ["erklären", "berechnen", "bewerten"], klausurDE: "Geostationär vs. niedrig: Bahnhöhe berechnen und bewerten.", klausurZH: "综合应用题：同步与低轨对比，计算轨道高度并评价。", leitfrageDE: "Warum fällt ein Satellit nicht herunter?", leitfrageZH: "卫星为什么不掉下来？", noteKeywords: ["satellit", "geostationaer", "bahnhoehe", "kreisbewegung"], children: [] }
] },
{ id: "physik/if2/weltbilder-bezugssysteme", level: 2, code: "", titleDE: "Weltbilder und Bezugssysteme", titleZH: "世界观与参考系", operatoren: [], klausurDE: "", klausurZH: "", leitfrageDE: "", leitfrageZH: "", noteKeywords: [], children: [
{ id: "physik/if2/weltbilder-bezugssysteme/geo-heliozentrisch", level: 3, code: "", titleDE: "Wandel geo- zu heliozentrisch", titleZH: "地心说到日心说的转变", operatoren: ["beschreiben", "erklären", "bewerten"], klausurDE: "Modellwechsel begründen, Evidenz bewerten (AFB II-III).", klausurZH: "评价题：论证模型更替并评价证据（AFB II-III）。", leitfrageDE: "Warum setzte sich das heliozentrische Modell durch?", leitfrageZH: "日心说为什么胜出？", noteKeywords: ["weltbild", "heliozentrisch", "geozentrisch", "modellwechsel"], children: [] },
{ id: "physik/if2/weltbilder-bezugssysteme/bezugssysteme", level: 3, code: "", titleDE: "Bezugssysteme", titleZH: "参考系", operatoren: ["beschreiben", "erklären", "begründen"], klausurDE: "Bewegung aus zwei Bezugssystemen beschreiben.", klausurZH: "理解题：从两种参考系描述同一运动。", leitfrageDE: "Wie ändert das Bezugssystem die Beschreibung?", leitfrageZH: "参考系如何改变运动描述？", noteKeywords: ["bezugssystem", "beobachter", "bewegung", "beschreibung"], children: [] },
{ id: "physik/if2/weltbilder-bezugssysteme/lichtuhr", level: 3, code: "", titleDE: "Lichtuhr-Gedankenexperiment", titleZH: "光钟思想实验", operatoren: ["beschreiben", "erklären", "deuten"], klausurDE: "Lichtuhr beschreiben, Invarianz von c deuten.", klausurZH: "思想实验解读：描述光钟并解释光速不变。", leitfrageDE: "Was zeigt die Lichtuhr über Lichtgeschwindigkeit?", leitfrageZH: "光钟说明了光速的什么？", noteKeywords: ["lichtuhr", "gedankenexperiment", "lichtgeschwindigkeit", "invarianz"], children: [] }
] }
] }
] } };