import type { FachBaum } from "./types";

export const sowiBaum: FachBaum = {
  fach: "SoWi",
  nameDE: "Sozialwissenschaften",
  nameZH: "社会科学",
  klpReferenz: "NRW Kernlehrplan GeWi EF: IF 1 Soziale Ungleichheit, IF 2 Politik und Partizipation, IF 3 Wirtschaft und Markt",
  klausurFokusDE: "Sachtext plus Karikatur, Tabelle oder Statistik im Dreischritt darstellen, analysieren, beurteilen; Einleitung in drei Sätzen",
  klausurFokusZH: "材料题三步走：描述、分析、评价，开头三句交代清楚",
  root: {
    id: "sowi",
    level: 0,
    code: "",
    titleDE: "Sozialwissenschaften",
    titleZH: "社会科学",
    operatoren: [],
    klausurDE: "",
    klausurZH: "",
    leitfrageDE: "",
    leitfrageZH: "",
    noteKeywords: [],
    children: [
      {
        id: "sowi/if1",
        level: 1,
        code: "IF 1",
        titleDE: "Soziale Ungleichheit",
        titleZH: "社会不平等",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "sowi/if1/dimensionen",
            level: 2,
            code: "",
            titleDE: "Dimensionen",
            titleZH: "维度",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if1/dimensionen/einkommen-bildung",
                level: 3,
                code: "",
                titleDE: "Einkommen und Bildung",
                titleZH: "收入与教育",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Darstellen-Teil: Sachtext oder Tabelle in knapper Einleitung und Kernbefunden wiedergeben, Einheiten und Zeitraum nennen.",
                klausurZH: "描述段：三句开头加核心发现，认准单位和年份",
                leitfrageDE: "Wie hängen Einkommen und Bildung zusammen?",
                leitfrageZH: "收入和教育之间有什么关系？",
                noteKeywords: ["einkommen", "bildung", "tabelle", "schichtung"],
                children: [],
              },
              {
                id: "sowi/if1/dimensionen/geschlecht-herkunft",
                level: 3,
                code: "",
                titleDE: "Geschlecht und Herkunft",
                titleZH: "性别与出身",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Analysieren-Teil: Ursachen und Folgen mit Fachbegriffen wie strukturelle Benachteiligung erklären.",
                klausurZH: "分析段：落到结构原因，用结构性不利等术语解释",
                leitfrageDE: "Wo wirkt Herkunft stärker als Leistung?",
                leitfrageZH: "出身在哪里比成绩更有影响？",
                noteKeywords: ["geschlecht", "herkunft", "strukturell", "benachteiligung"],
                children: [],
              },
              {
                id: "sowi/if1/dimensionen/lebenslagen",
                level: 3,
                code: "",
                titleDE: "Lebenslagen-Überlagerung",
                titleZH: "生活境况叠加",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Urteilsteil: Kriterien wie Gerechtigkeit und Chancengleichheit nennen und das eigene Urteil daran begründen.",
                klausurZH: "评价段：亮出公正和平等标准，给出有理由的判断",
                leitfrageDE: "Wer ist mehrfach benachteiligt und warum?",
                leitfrageZH: "谁面临多重不利，为什么？",
                noteKeywords: ["lebenslagen", "mehrfach", "gerechtigkeit", "chancengleichheit"],
                children: [],
              },
            ],
          },
          {
            id: "sowi/if1/ursachen-messung",
            level: 2,
            code: "",
            titleDE: "Ursachen und Messung",
            titleZH: "原因与测量",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if1/ursachen-messung/ursachen-faktoren",
                level: 3,
                code: "",
                titleDE: "Ursachen und Faktoren",
                titleZH: "成因要素",
                operatoren: ["analysieren", "darstellen"],
                klausurDE: "Analysieren-Teil: Ursachen mit Fachbegriffen den Materialbefunden zuordnen, etwa Familie, Bildungsweg und Arbeitsmarkt.",
                klausurZH: "分析段：三筐原因对应材料发现，每筐写一句",
                leitfrageDE: "Welche Ursachen erklärt das Material, welche nicht?",
                leitfrageZH: "材料解释了哪些成因，还有哪些没解释？",
                noteKeywords: ["ursachen", "familie", "arbeitsmarkt", "faktoren"],
                children: [],
              },
              {
                id: "sowi/if1/ursachen-messung/messung-indikatoren",
                level: 3,
                code: "",
                titleDE: "Messung und Indikatoren",
                titleZH: "测量与指标",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Materialarbeit mit Statistik und Tabelle: Achsen, Einheiten und Zeitraum benennen und eine Trendaussage formulieren.",
                klausurZH: "图表题：说清坐标单位时间，再写趋势判断的两面",
                leitfrageDE: "Was misst der Indikator — und was verschweigt er?",
                leitfrageZH: "这个指标测了什么，又掩盖了什么？",
                noteKeywords: ["indikator", "messung", "statistik", "grenze"],
                children: [],
              },
              {
                id: "sowi/if1/ursachen-messung/statistik-lesen",
                level: 3,
                code: "",
                titleDE: "Statistik lesen",
                titleZH: "读表读数",
                operatoren: ["darstellen"],
                klausurDE: "Darstellen-Teil: Tabelle oder Statistik sachlich beschreiben, Höchst-, Tiefst- und Veränderungswerte nennen, ohne zu werten.",
                klausurZH: "描述段：只写看到什么，最高最低和变化，不提前评价",
                leitfrageDE: "Was zeigt die Statistik genau?",
                leitfrageZH: "统计图到底显示了什么？",
                noteKeywords: ["statistik", "beschreiben", "tabelle", "trend"],
                children: [],
              },
            ],
          },
          {
            id: "sowi/if1/mobilitaet-sozialstaat",
            level: 2,
            code: "",
            titleDE: "Mobilität und Sozialstaat",
            titleZH: "流动与社会国家",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if1/mobilitaet-sozialstaat/soziale-mobilitaet",
                level: 3,
                code: "",
                titleDE: "Soziale Mobilität und Aufstieg",
                titleZH: "社会流动与上升",
                operatoren: ["analysieren", "beurteilen"],
                klausurDE: "Von analysieren zu beurteilen: Mobilitätschancen aus dem Material deuten, dann am Kriterium Chancengleichheit bewerten.",
                klausurZH: "先分析再评价：从材料读流动机会，用机会平等标准评价",
                leitfrageDE: "Wie offen ist der Aufstieg wirklich?",
                leitfrageZH: "上升通道到底有多开放？",
                noteKeywords: ["mobilitaet", "aufstieg", "chancengleichheit", "deutung"],
                children: [],
              },
              {
                id: "sowi/if1/mobilitaet-sozialstaat/chancen-barrieren",
                level: 3,
                code: "",
                titleDE: "Chancen und Barrieren",
                titleZH: "机会与壁垒",
                operatoren: ["analysieren", "erörtern"],
                klausurDE: "Analysieren-Teil: Fördernde und hemmende Faktoren gegenüberstellen.",
                klausurZH: "分析段：机会和壁垒成对写，分析立刻立体",
                leitfrageDE: "Welche Barrieren bremsen gleiche Chancen?",
                leitfrageZH: "哪些壁垒拖住了平等机会？",
                noteKeywords: ["chancen", "barrieren", "gegenueberstellung", "faktoren"],
                children: [],
              },
              {
                id: "sowi/if1/mobilitaet-sozialstaat/sozialstaat-ausgleich",
                level: 3,
                code: "",
                titleDE: "Sozialstaat und Ausgleich",
                titleZH: "社会国家与调节",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Beurteilen-Teil: Sozialstaatliche Maßnahmen am Kriterium Gerechtigkeit prüfen und ein eigenes Urteil formulieren.",
                klausurZH: "评价段：写国家做了什么、够不够、代价是什么",
                leitfrageDE: "Gleicht der Sozialstaat fair aus?",
                leitfrageZH: "社会国家的调节算公平吗？",
                noteKeywords: ["sozialstaat", "ausgleich", "gerechtigkeit", "massnahmen"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "sowi/if2",
        level: 1,
        code: "IF 2",
        titleDE: "Politische Strukturen und Partizipation",
        titleZH: "政治结构与参与",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "sowi/if2/demokratieprinzipien",
            level: 2,
            code: "",
            titleDE: "Demokratieprinzipien",
            titleZH: "民主原则",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if2/demokratieprinzipien/grundprinzipien",
                level: 3,
                code: "",
                titleDE: "Grundprinzipien",
                titleZH: "基本原则",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Darstellen-Teil: Demokratische Prinzipien wie Mehrheit, Minderheitenschutz und Befristung im Sachtext identifizieren.",
                klausurZH: "描述段：先套民主三件套，判断材料哪里符合",
                leitfrageDE: "Wo zeigt das Material Demokratie, wo nicht?",
                leitfrageZH: "材料哪里体现民主，哪里没有？",
                noteKeywords: ["demokratie", "mehrheit", "minderheitenschutz", "prinzipien"],
                children: [],
              },
              {
                id: "sowi/if2/demokratieprinzipien/rechtsstaat-gewaltenteilung",
                level: 3,
                code: "",
                titleDE: "Rechtsstaat und Gewaltenteilung",
                titleZH: "法治与分权",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Analysieren-Teil: Akteure und Zuständigkeiten zuordnen und die gegenseitige Kontrolle erklären.",
                klausurZH: "分析段：点名机构和职能，说清谁监督谁",
                leitfrageDE: "Wer kontrolliert wen mit welchen Mitteln?",
                leitfrageZH: "谁用什么手段监督谁？",
                noteKeywords: ["rechtsstaat", "gewaltenteilung", "kontrolle", "akteure"],
                children: [],
              },
              {
                id: "sowi/if2/demokratieprinzipien/grundrechte",
                level: 3,
                code: "",
                titleDE: "Grundrechte",
                titleZH: "基本权利",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Beurteilen-Teil: Grundrechte als Kriterium nennen und Eingriff gegen Schutz abwägen.",
                klausurZH: "评价段：以基本权利为底线，权衡限制与保护",
                leitfrageDE: "Wo endet mein Recht, wo beginnt das der anderen?",
                leitfrageZH: "我的权利在哪里结束，他人的从哪里开始？",
                noteKeywords: ["grundrechte", "kriterium", "abwaegung", "schutz"],
                children: [],
              },
            ],
          },
          {
            id: "sowi/if2/parteien-wahlen",
            level: 2,
            code: "",
            titleDE: "Parteien und Wahlen",
            titleZH: "政党与选举",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if2/parteien-wahlen/parteien-funktionen",
                level: 3,
                code: "",
                titleDE: "Parteien und Funktionen",
                titleZH: "政党与功能",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Darstellen und analysieren: Parteifunktionen am Sachtext belegen und einordnen.",
                klausurZH: "描述加分析：在材料中找到对应句，归入政党功能",
                leitfrageDE: "Welche Parteifunktion zeigt das Material?",
                leitfrageZH: "材料体现了政党的哪项功能？",
                noteKeywords: ["parteien", "funktionen", "einordnung", "sachtext"],
                children: [],
              },
              {
                id: "sowi/if2/parteien-wahlen/wahlen-wahlsysteme",
                level: 3,
                code: "",
                titleDE: "Wahlen und Wahlsysteme",
                titleZH: "选举与选举制度",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Analysieren-Teil mit Statistik: Wahl- oder Umfragewerte beschreiben und Folgen für Mehrheiten deuten.",
                klausurZH: "图表分析：描述选举数据，推断对组阁执政的影响",
                leitfrageDE: "Was folgt aus dem Wahlergebnis für Regieren?",
                leitfrageZH: "选举结果对组阁执政意味着什么？",
                noteKeywords: ["wahlen", "wahlsystem", "mehrheit", "umfrage"],
                children: [],
              },
              {
                id: "sowi/if2/parteien-wahlen/karikatur-analyse",
                level: 3,
                code: "",
                titleDE: "Karikatur-Analyse",
                titleZH: "漫画分析",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Materialarbeit Karikatur: Bildelemente sachlich beschreiben, dann mit Fachbegriff deuten.",
                klausurZH: "漫画三步：先写看见什么，再写讽刺指向，最后挂概念",
                leitfrageDE: "Was kritisiert die Karikatur mit welchen Mitteln?",
                leitfrageZH: "漫画用什么手法批评了什么？",
                noteKeywords: ["karikatur", "beschreiben", "deutung", "fachbegriff"],
                children: [],
              },
            ],
          },
          {
            id: "sowi/if2/beteiligung-protest-digital",
            level: 2,
            code: "",
            titleDE: "Beteiligung, Protest und digital",
            titleZH: "参与、抗议与数字公共领域",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if2/beteiligung-protest-digital/partizipationsformen",
                level: 3,
                code: "",
                titleDE: "Partizipationsformen",
                titleZH: "参与形式",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Analysieren-Teil: Beteiligungsformen aus dem Material sortieren und Akteure benennen.",
                klausurZH: "分析段：按体制内外和个人集体分类，点名参与者",
                leitfrageDE: "Wer beteiligt sich wie — und wer nicht?",
                leitfrageZH: "谁以什么方式参与，谁没有？",
                noteKeywords: ["partizipation", "formen", "akteure", "sortierung"],
                children: [],
              },
              {
                id: "sowi/if2/beteiligung-protest-digital/protest-bewegungen",
                level: 3,
                code: "",
                titleDE: "Protest und Bewegungen",
                titleZH: "抗议与运动",
                operatoren: ["analysieren", "beurteilen"],
                klausurDE: "Von analysieren zu beurteilen: Anliegen und Mittel deuten, dann Legitimität mit Kriterien prüfen.",
                klausurZH: "先分析后评价：答清诉求手段合法边界三问",
                leitfrageDE: "Wann ist Protest legitim?",
                leitfrageZH: "抗议何时是正当的？",
                noteKeywords: ["protest", "bewegung", "legitimitaet", "mittel"],
                children: [],
              },
              {
                id: "sowi/if2/beteiligung-protest-digital/digital-oeffentlichkeit",
                level: 3,
                code: "",
                titleDE: "Digital und Öffentlichkeit",
                titleZH: "数字参与与公共领域",
                operatoren: ["analysieren", "beurteilen"],
                klausurDE: "Beurteilen-Teil: Digitale Beteiligung an Kriterien wie Teilhabe und Deliberation messen und ein eigenes Urteil formulieren.",
                klausurZH: "评价段：用降低门槛和碎片情绪化这对矛盾下判断",
                leitfrageDE: "Stärkt das Netz die Demokratie oder spaltet es sie?",
                leitfrageZH: "网络是增强民主还是分裂民主？",
                noteKeywords: ["digital", "oeffentlichkeit", "teilhabe", "deliberation"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "sowi/if3",
        level: 1,
        code: "IF 3",
        titleDE: "Wirtschaft und Markt",
        titleZH: "经济与市场",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "sowi/if3/wirtschaftskreislauf",
            level: 2,
            code: "",
            titleDE: "Wirtschaftskreislauf",
            titleZH: "经济循环",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if3/wirtschaftskreislauf/akteure-stroeme",
                level: 3,
                code: "",
                titleDE: "Akteure und Ströme",
                titleZH: "行为者与流",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Darstellen-Teil: Akteure und Ströme des Schaubilds sachlich wiedergeben, Pfeilrichtungen beachten.",
                klausurZH: "描述段：标出谁和谁换了什么，箭头方向写对",
                leitfrageDE: "Wer tauscht was mit wem?",
                leitfrageZH: "谁和谁交换了什么？",
                noteKeywords: ["akteure", "stroeme", "schaubild", "kreislauf"],
                children: [],
              },
              {
                id: "sowi/if3/wirtschaftskreislauf/haushalte-unternehmen",
                level: 3,
                code: "",
                titleDE: "Haushalte und Unternehmen",
                titleZH: "家户与企业",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Analysieren-Teil: Rollen im Kreislauf zuordnen und eine einfache Störung wie einen Konsumrückgang fortdenken.",
                klausurZH: "分析段：回到两类角色，推演一环出问题的影响",
                leitfrageDE: "Was passiert bei einer Störung im Kreislauf?",
                leitfrageZH: "循环中一环出问题会发生什么？",
                noteKeywords: ["haushalte", "unternehmen", "stoerung", "rollen"],
                children: [],
              },
              {
                id: "sowi/if3/wirtschaftskreislauf/kreislauf-lesen",
                level: 3,
                code: "",
                titleDE: "Kreislauf lesen",
                titleZH: "循环图阅读",
                operatoren: ["darstellen"],
                klausurDE: "Darstellen-Teil: Das Schaubild mit knapper Einleitung einbetten und die Kernströme nennen, ohne zu werten.",
                klausurZH: "描述段：只复述流向和关系，评价留到后面",
                leitfrageDE: "Welche Ströme trägt das Modell?",
                leitfrageZH: "这个模型呈现了哪些流？",
                noteKeywords: ["kreislauf", "schaubild", "beschreiben", "stroeme"],
                children: [],
              },
            ],
          },
          {
            id: "sowi/if3/markt-preisbildung",
            level: 2,
            code: "",
            titleDE: "Markt und Preisbildung",
            titleZH: "市场与价格形成",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if3/markt-preisbildung/angebot-nachfrage",
                level: 3,
                code: "",
                titleDE: "Angebot und Nachfrage",
                titleZH: "供给与需求",
                operatoren: ["darstellen", "analysieren"],
                klausurDE: "Materialarbeit mit Grafik: Kurven beschreiben und Mengen- oder Preisänderungen ablesen.",
                klausurZH: "读图题：背熟两条线方向，读出量价变化",
                leitfrageDE: "Wie reagieren Menge und Preis aufeinander?",
                leitfrageZH: "量和价格如何相互反应？",
                noteKeywords: ["angebot", "nachfrage", "kurve", "preis"],
                children: [],
              },
              {
                id: "sowi/if3/markt-preisbildung/preisbildung",
                level: 3,
                code: "",
                titleDE: "Preisbildung",
                titleZH: "价格形成",
                operatoren: ["analysieren", "darstellen"],
                klausurDE: "Analysieren-Teil: Eine Preisänderung auf die Verschiebung von Angebot oder Nachfrage zurückführen.",
                klausurZH: "分析段：只讲哪条线动了、为什么动",
                leitfrageDE: "Warum steigt oder fällt der Preis hier?",
                leitfrageZH: "这里的价格为什么涨或跌？",
                noteKeywords: ["preisbildung", "gleichgewicht", "verschiebung", "analyse"],
                children: [],
              },
              {
                id: "sowi/if3/markt-preisbildung/marktversagen",
                level: 3,
                code: "",
                titleDE: "Marktversagen",
                titleZH: "市场失灵",
                operatoren: ["analysieren", "beurteilen"],
                klausurDE: "Von analysieren zu beurteilen: Den Versagensfall wie Externalität oder öffentliches Gut benennen, dann Staatseingriff an Effizienz und Fairness prüfen.",
                klausurZH: "先找失灵再评价：污染不管或公共品缺供，引出国家角色",
                leitfrageDE: "Wo versagt der Markt im Material?",
                leitfrageZH: "材料中的市场在哪里失灵？",
                noteKeywords: ["marktversagen", "externalitaet", "effizienz", "fairness"],
                children: [],
              },
            ],
          },
          {
            id: "sowi/if3/staat-globalisierung",
            level: 2,
            code: "",
            titleDE: "Staat und Globalisierung",
            titleZH: "国家角色与全球化",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sowi/if3/staat-globalisierung/rolle-staat",
                level: 3,
                code: "",
                titleDE: "Rolle des Staates",
                titleZH: "国家角色",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Beurteilen-Teil: Den Staatseingriff mit Kriterien prüfen und ein eigenes Urteil mit Abwägung formulieren.",
                klausurZH: "评价段：国家定规则当裁判兜底线，建议配依据",
                leitfrageDE: "Soll der Staat hier eingreifen?",
                leitfrageZH: "国家在这里该不该出手？",
                noteKeywords: ["staat", "eingriff", "regeln", "urteil"],
                children: [],
              },
              {
                id: "sowi/if3/staat-globalisierung/sozial-markt-ausgleich",
                level: 3,
                code: "",
                titleDE: "Sozial und Markt im Ausgleich",
                titleZH: "社会与市场的平衡",
                operatoren: ["analysieren", "beurteilen"],
                klausurDE: "Beurteilen-Teil: Effizienz gegen Gerechtigkeit abwägen und ein begründetes Urteil formulieren.",
                klausurZH: "评价段：写清得到什么付出什么，效率公平都要",
                leitfrageDE: "Wie viel Markt verträgt die Fairness?",
                leitfrageZH: "公平能承受多少市场？",
                noteKeywords: ["sozial", "markt", "effizienz", "gerechtigkeit"],
                children: [],
              },
              {
                id: "sowi/if3/staat-globalisierung/globalisierung-ansaetze",
                level: 3,
                code: "",
                titleDE: "Globalisierung-Ansätze",
                titleZH: "全球化进路",
                operatoren: ["darstellen", "beurteilen"],
                klausurDE: "Von darstellen zu beurteilen: Den Globalisierungsbezug des Materials wiedergeben, dann Chancen und Risiken mit Kriterien bewerten.",
                klausurZH: "先描述再评价：材料给哪面先写哪面，再评机会风险",
                leitfrageDE: "Wer gewinnt, wer verliert durch Verflechtung?",
                leitfrageZH: "相互依存让谁受益、让谁受损？",
                noteKeywords: ["globalisierung", "chancen", "risiken", "verflechtung"],
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
};
