import type { FachBaum } from "./types";

export const sportBaum: FachBaum = {
  fach: "Sport",
  nameDE: "Sport",
  nameZH: "体育",
  klpReferenz: "NRW KLP GOSt Sport EF, mündliche Prüfung",
  klausurFokusDE: "Bewegung in Phasen erklären, Fehler und Korrektur nennen, Trainingsprinzipien und eigene Leistung reflektieren",
  klausurFokusZH: "口试要能做更要能讲：按阶段说清动作，说准错误纠正，说明训练原理",
  root: {
    id: "sport",
    level: 0,
    code: "",
    titleDE: "Sport",
    titleZH: "体育",
    operatoren: [],
    klausurDE: "",
    klausurZH: "",
    leitfrageDE: "",
    leitfrageZH: "",
    noteKeywords: [],
    children: [
      {
        id: "sport/if1",
        level: 1,
        code: "IF 1",
        titleDE: "Praxis",
        titleZH: "实践",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "sport/if1/leichtathletik",
            level: 2,
            code: "",
            titleDE: "Leichtathletik",
            titleZH: "田径",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if1/leichtathletik/lauftechnik",
                level: 3,
                code: "",
                titleDE: "Lauftechnik",
                titleZH: "跑步技术",
                operatoren: ["beschreiben", "demonstrieren"],
                klausurDE: "Praxisnachweis mit Erklärung: Frequenz, Schrittlänge, Armarbeit und Atmung beschreiben und Schwerpunkte zeigen.",
                klausurZH: "口试实践加解说：说清步频步幅摆臂呼吸并示范要点",
                leitfrageDE: "Was macht eine ökonomische Lauftechnik aus?",
                leitfrageZH: "经济的跑步技术要点是什么？",
                noteKeywords: ["lauf", "frequenz", "atmung", "technik"],
                children: [],
              },
              {
                id: "sport/if1/leichtathletik/sprungtechnik",
                level: 3,
                code: "",
                titleDE: "Sprungtechnik",
                titleZH: "跳跃技术",
                operatoren: ["beschreiben", "gliedern"],
                klausurDE: "Phasenbild mit Praxis: Vorbereitung, Absprung, Flug und Landung erklären und zeigen, typische Fehler mit Korrektur.",
                klausurZH: "口试阶段分析加展示：四步说清跳跃，必问典型错误纠正",
                leitfrageDE: "Wie gliedert sich der Sprung in Phasen?",
                leitfrageZH: "跳跃动作分哪几个阶段？",
                noteKeywords: ["sprung", "phasen", "absprung", "landung"],
                children: [],
              },
              {
                id: "sport/if1/leichtathletik/wurftechnik-leistung",
                level: 3,
                code: "",
                titleDE: "Wurftechnik und Leistung",
                titleZH: "投掷技术与成绩",
                operatoren: ["beschreiben", "auswerten"],
                klausurDE: "Leistungsnachweis mit Deutung: Haltung, Ausholbewegung, Abflugwinkel und Ausschwingen erklären, Weite auf Technik zurückführen.",
                klausurZH: "口试成绩加归因：讲清持球引体出手随挥，成绩挂钩技术",
                leitfrageDE: "Entscheidend ist beim Wurf …, weil …?",
                leitfrageZH: "投掷的关键是什么、为什么？",
                noteKeywords: ["wurf", "technik", "weite", "leistung"],
                children: [],
              },
            ],
          },
          {
            id: "sport/if1/spiele",
            level: 2,
            code: "",
            titleDE: "Spiele",
            titleZH: "球类游戏",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if1/spiele/technik-im-spiel",
                level: 3,
                code: "",
                titleDE: "Technik im Spiel",
                titleZH: "比赛中的技术 ⏳",
                operatoren: ["beschreiben", "demonstrieren"],
                klausurDE: "Praxisdemo mit Kurzerklärung: Zwei bis drei Kerntechniken der Kurssportart zeigen und Schwerpunkte nennen.",
                klausurZH: "口试实践演示加讲解：说出课程球项核心技术要点",
                leitfrageDE: "Was sind die technischen Schlüsselpunkte?",
                leitfrageZH: "技术关键点是什么？",
                noteKeywords: ["spiel", "technik", "demo", "schluesselpunkte"],
                children: [],
              },
              {
                id: "sport/if1/spiele/taktik-zusammenspiel",
                level: 3,
                code: "",
                titleDE: "Taktik und Zusammenspiel",
                titleZH: "战术与配合",
                operatoren: ["erläutern", "darstellen"],
                klausurDE: "Gespräch mit Spielszene: Laufwege, Passen und Raumnutzung erklären, nicht nur Einzeltechnik.",
                klausurZH: "口试场景追问：讲清跑位传接与空间利用",
                leitfrageDE: "Wie schafft Zusammenspiel Raumvorteil?",
                leitfrageZH: "配合如何创造空间优势？",
                noteKeywords: ["taktik", "zusammenspiel", "raum", "szene"],
                children: [],
              },
              {
                id: "sport/if1/spiele/regeln-anwenden",
                level: 3,
                code: "",
                titleDE: "Regeln im Spiel anwenden",
                titleZH: "运用比赛规则",
                operatoren: ["erklären", "anwenden"],
                klausurDE: "Mündliche Regelfrage: Regel nennen, auf die Szene anwenden und Entscheidung begründen.",
                klausurZH: "口试规则题：规则到场景再到判罚",
                leitfrageDE: "Welche Regel gilt in dieser Szene und warum?",
                leitfrageZH: "这个场景适用哪条规则、为什么？",
                noteKeywords: ["regeln", "szene", "entscheidung", "anwenden"],
                children: [],
              },
            ],
          },
          {
            id: "sport/if1/gymnastik-schwimmen",
            level: 2,
            code: "",
            titleDE: "Gymnastik-Tanz und Schwimmen",
            titleZH: "体操舞蹈与游泳",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if1/gymnastik-schwimmen/rhythmus-koordination",
                level: 3,
                code: "",
                titleDE: "Rhythmus und Koordination",
                titleZH: "节奏与协调",
                operatoren: ["beschreiben", "demonstrieren"],
                klausurDE: "Praxispräsentation mit Erklärung: Bewegung im Rhythmus halten, Koordination von Armen und Beinen zeigen.",
                klausurZH: "口试组合展示加解说：动作卡上节奏，讲上下肢协调",
                leitfrageDE: "Wie bleibt die Bewegung im Rhythmus?",
                leitfrageZH: "动作如何合上节奏？",
                noteKeywords: ["rhythmus", "koordination", "praesentation", "bewegung"],
                children: [],
              },
              {
                id: "sport/if1/gymnastik-schwimmen/bewegungsfolge",
                level: 3,
                code: "",
                titleDE: "Bewegungsfolge gestalten",
                titleZH: "编排动作组合",
                operatoren: ["gestalten", "begründen"],
                klausurDE: "Gestaltungsaufgabe mit Begründung: Kleine Folge in Beginn, Steigerung und Schluss aufbauen und Aufbau begründen.",
                klausurZH: "口试编排题：开头发展结尾编小组合并说明理由",
                leitfrageDE: "Warum habe ich die Folge so aufgebaut?",
                leitfrageZH: "我为什么这样编排组合？",
                noteKeywords: ["gestaltung", "folge", "aufbau", "begruendung"],
                children: [],
              },
              {
                id: "sport/if1/gymnastik-schwimmen/schwimmtechnik-ausdauer",
                level: 3,
                code: "",
                titleDE: "Schwimmtechnik und Ausdauer",
                titleZH: "泳姿技术与耐力 ⏳",
                operatoren: ["beschreiben", "erläutern"],
                klausurDE: "Praxisnachweis mit Erklärung: Armzug, Beinschlag und Atmungsrhythmus einer Lage erläutern, Krafteinteilung nennen.",
                klausurZH: "口试实践加讲解：说清泳姿划水打腿呼吸与耐力分配",
                leitfrageDE: "Worauf achte ich bei Technik und Einteilung?",
                leitfrageZH: "技术与体力分配注意什么？",
                noteKeywords: ["schwimmen", "lage", "atmung", "ausdauer"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "sport/if2",
        level: 1,
        code: "IF 2",
        titleDE: "Theorie mündlich",
        titleZH: "理论口试",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "sport/if2/trainingslehre",
            level: 2,
            code: "",
            titleDE: "Trainingslehre",
            titleZH: "训练学",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if2/trainingslehre/aufwaermen",
                level: 3,
                code: "",
                titleDE: "Aufwärmen",
                titleZH: "热身",
                operatoren: ["erklären", "begründen"],
                klausurDE: "Klassische Einstiegsfrage: Zweck, Reihenfolge und Intensität des Aufwärmens erklären und begründen.",
                klausurZH: "口试标准开口题：说清目的内容顺序强度，不只跑两圈",
                leitfrageDE: "Warum und wie wärme ich mich auf?",
                leitfrageZH: "为什么热身、怎样热身？",
                noteKeywords: ["aufwaermen", "zweck", "intensitaet", "reihenfolge"],
                children: [],
              },
              {
                id: "sport/if2/trainingslehre/belastung-erholung",
                level: 3,
                code: "",
                titleDE: "Belastung und Erholung",
                titleZH: "负荷与恢复",
                operatoren: ["erklären", "darstellen"],
                klausurDE: "Vertiefung im Gespräch: Stellgrößen der Belastung und Mittel der Erholung darstellen, an Beispiel binden.",
                klausurZH: "口试对话深化题：负荷三要素与恢复手段要匹配",
                leitfrageDE: "Wie hängen Belastung und Erholung zusammen?",
                leitfrageZH: "负荷与恢复是什么关系？",
                noteKeywords: ["belastung", "erholung", "intensitaet", "beispiel"],
                children: [],
              },
              {
                id: "sport/if2/trainingslehre/superkompensation",
                level: 3,
                code: "",
                titleDE: "Superkompensation",
                titleZH: "超量恢复",
                operatoren: ["erklären", "darstellen"],
                klausurDE: "Theorieaufgabe für hohe Punktzahl: Das Modell mit Kurve erklären und mit Beispiel zeigen, wann der nächste Reiz passt.",
                klausurZH: "口试理论高分题：用曲线解释练休提高的时机",
                leitfrageDE: "Wann setzt der nächste Reiz optimal ein?",
                leitfrageZH: "下一次刺激何时加最合适？",
                noteKeywords: ["superkompensation", "reiz", "kurve", "modell"],
                children: [],
              },
            ],
          },
          {
            id: "sport/if2/bewegungsanalyse",
            level: 2,
            code: "",
            titleDE: "Bewegungsanalyse Phasenbild",
            titleZH: "动作阶段分析",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if2/bewegungsanalyse/vorbereitungsphase",
                level: 3,
                code: "",
                titleDE: "Vorbereitungsphase",
                titleZH: "准备阶段",
                operatoren: ["beschreiben", "erklären"],
                klausurDE: "Erste Frage zum Phasenbild: Ausgangsstellung und Ausholbewegung beschreiben, Satzmuster Die Bewegung gliedert sich in.",
                klausurZH: "口试阶段三问之首：说清准备姿势与预拉长",
                leitfrageDE: "Was bereitet die Hauptphase optimal vor?",
                leitfrageZH: "什么为主要阶段做好了准备？",
                noteKeywords: ["vorbereitung", "stellung", "phasenbild", "ausholen"],
                children: [],
              },
              {
                id: "sport/if2/bewegungsanalyse/hauptphase",
                level: 3,
                code: "",
                titleDE: "Hauptphase",
                titleZH: "主要阶段",
                operatoren: ["analysieren", "erklären"],
                klausurDE: "Kern der Analyse: Kraftfolge und Schlüsselmoment nennen, biomechanisch begründen mit Entscheidend ist weil.",
                klausurZH: "口试分析核心：点名发力顺序与关键瞬间，讲生物力学",
                leitfrageDE: "Was ist biomechanisch entscheidend?",
                leitfrageZH: "从生物力学看决定性的是什么？",
                noteKeywords: ["hauptphase", "biomechanik", "kraft", "schluessel"],
                children: [],
              },
              {
                id: "sport/if2/bewegungsanalyse/endphase",
                level: 3,
                code: "",
                titleDE: "Endphase",
                titleZH: "结束阶段",
                operatoren: ["beschreiben", "begründen"],
                klausurDE: "Abschluss des Phasenbilds: Abfangen, Gleichgewicht und Ausschwingen beschreiben, Sicherheit begründen.",
                klausurZH: "口试阶段收尾加安全追问：讲缓冲平衡随挥",
                leitfrageDE: "Wie sichere ich die Bewegung am Ende?",
                leitfrageZH: "结尾如何保证安全稳定？",
                noteKeywords: ["endphase", "gleichgewicht", "sicherheit", "abfangen"],
                children: [],
              },
            ],
          },
          {
            id: "sport/if2/fairness-regeln",
            level: 2,
            code: "",
            titleDE: "Fairness und Regeln",
            titleZH: "公平与规则",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if2/fairness-regeln/regeln-erklaeren",
                level: 3,
                code: "",
                titleDE: "Regeln erklären",
                titleZH: "解释规则",
                operatoren: ["erklären", "darstellen"],
                klausurDE: "Regelfrage: Kern der Regel in eigenen Worten erklären, Sinn und Beispiel nennen.",
                klausurZH: "口试规则解释题：用自己的话说核心，不背条文",
                leitfrageDE: "Was regelt die Regel und wozu?",
                leitfrageZH: "这条规则管什么、为了什么？",
                noteKeywords: ["regeln", "sinn", "beispiel", "erklaeren"],
                children: [],
              },
              {
                id: "sport/if2/fairness-regeln/fairness-verhalten",
                level: 3,
                code: "",
                titleDE: "Fairness und Verhalten",
                titleZH: "公平与行为",
                operatoren: ["beurteilen", "reflektieren"],
                klausurDE: "Wertungsfrage: Faires und unfaires Verhalten an Beispielen zeigen und mit Respekt und Verantwortung beurteilen.",
                klausurZH: "口试价值判断题：举公平不公平行为并评价",
                leitfrageDE: "Was ist fair und woran mache ich das fest?",
                leitfrageZH: "什么是公平、依据是什么？",
                noteKeywords: ["fairness", "verhalten", "respekt", "beurteilung"],
                children: [],
              },
              {
                id: "sport/if2/fairness-regeln/sicherheit",
                level: 3,
                code: "",
                titleDE: "Sicherheit",
                titleZH: "安全",
                operatoren: ["benennen", "begründen"],
                klausurDE: "Sicherheitsfrage oft an Praxis gekoppelt: Anlage, Gerät und Hilfestellung nennen und begründen.",
                klausurZH: "口试安全追问：说清场地器材帮助保护要点",
                leitfrageDE: "Wie minimiere ich das Verletzungsrisiko?",
                leitfrageZH: "如何把受伤风险降到最低？",
                noteKeywords: ["sicherheit", "anlage", "geraet", "hilfe"],
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "sport/if3",
        level: 1,
        code: "IF 3",
        titleDE: "Reflexion",
        titleZH: "反思",
        operatoren: [],
        klausurDE: "",
        klausurZH: "",
        leitfrageDE: "",
        leitfrageZH: "",
        noteKeywords: [],
        children: [
          {
            id: "sport/if3/eigene-leistung",
            level: 2,
            code: "",
            titleDE: "Eigene Leistung auswerten",
            titleZH: "评估个人表现",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if3/eigene-leistung/leistung-beschreiben",
                level: 3,
                code: "",
                titleDE: "Leistung beschreiben",
                titleZH: "描述表现",
                operatoren: ["beschreiben", "darstellen"],
                klausurDE: "Auftakt der Reflexion: Die eigene Leistung mit Daten und Technikpunkten sachlich beschreiben.",
                klausurZH: "口试反思开场：用数据和技术要点客观描述",
                leitfrageDE: "Was habe ich konkret geleistet?",
                leitfrageZH: "我具体做出了什么表现？",
                noteKeywords: ["leistung", "beschreiben", "daten", "technik"],
                children: [],
              },
              {
                id: "sport/if3/eigene-leistung/fehler-erkennen",
                level: 3,
                code: "",
                titleDE: "Fehler erkennen",
                titleZH: "发现错误",
                operatoren: ["analysieren", "benennen"],
                klausurDE: "Fehleranalyse: Einen Hauptfehler benennen und Phase plus Ursache zuordnen.",
                klausurZH: "口试错误分析：定位主要错误及所在阶段",
                leitfrageDE: "Wo liegt der Hauptfehler und in welcher Phase?",
                leitfrageZH: "主要错误在哪里、在哪个阶段？",
                noteKeywords: ["fehler", "phase", "ursache", "analyse"],
                children: [],
              },
              {
                id: "sport/if3/eigene-leistung/korrektur",
                level: 3,
                code: "",
                titleDE: "Korrektur vorschlagen",
                titleZH: "提出纠正",
                operatoren: ["erläutern", "begründen"],
                klausurDE: "Korrekturfrage: Eine übbare Korrekturübung nennen und biomechanisch oder physiologisch begründen.",
                klausurZH: "口试纠正题：给可练的纠正练习并说明有效原因",
                leitfrageDE: "Mit welcher Übung korrigiere ich und warum?",
                leitfrageZH: "用什么练习纠正、为什么有效？",
                noteKeywords: ["korrektur", "uebung", "begruendung", "fehler"],
                children: [],
              },
            ],
          },
          {
            id: "sport/if3/trainingskriterien",
            level: 2,
            code: "",
            titleDE: "Trainingskriterien nennen",
            titleZH: "说出训练指标",
            operatoren: [],
            klausurDE: "",
            klausurZH: "",
            leitfrageDE: "",
            leitfrageZH: "",
            noteKeywords: [],
            children: [
              {
                id: "sport/if3/trainingskriterien/herzfrequenz",
                level: 3,
                code: "",
                titleDE: "Herzfrequenz",
                titleZH: "心率",
                operatoren: ["erklären", "anwenden"],
                klausurDE: "Steuerungsfrage zur Intensität: Herzfrequenz als Kennwert der Belastung erklären und anwenden.",
                klausurZH: "口试强度追问：说清心率作为强度指标的用法",
                leitfrageDE: "Was sagt die Herzfrequenz über die Belastung?",
                leitfrageZH: "心率说明了什么负荷情况？",
                noteKeywords: ["herzfrequenz", "belastung", "intensitaet", "kennwert"],
                children: [],
              },
              {
                id: "sport/if3/trainingskriterien/dehnung-beweglichkeit",
                level: 3,
                code: "",
                titleDE: "Dehnung und Beweglichkeit",
                titleZH: "拉伸与柔韧",
                operatoren: ["erklären", "begründen"],
                klausurDE: "Kleine Planungsfrage: Zeitpunkt und Methode des Dehnens nennen und Wirkung auf die Technik begründen.",
                klausurZH: "口试训练计划小题：何时怎样拉伸及其对技术的影响",
                leitfrageDE: "Wann dehne ich wie und wozu?",
                leitfrageZH: "何时怎样拉伸、为了什么？",
                noteKeywords: ["dehnung", "beweglichkeit", "methode", "technik"],
                children: [],
              },
              {
                id: "sport/if3/trainingskriterien/koordination",
                level: 3,
                code: "",
                titleDE: "Koordination",
                titleZH: "协调性",
                operatoren: ["erklären", "veranschaulichen"],
                klausurDE: "Verbundfrage: Koordination als Zusammenspiel mehrerer Körperteile erklären und an der eigenen Sportart veranschaulichen.",
                klausurZH: "口试综合题：说清多部位合拍，举本项目例子",
                leitfrageDE: "Wo zeigt sich Koordination in meiner Sportart?",
                leitfrageZH: "在我的项目中协调体现在哪里？",
                noteKeywords: ["koordination", "zusammenspiel", "beispiel", "technik"],
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
};
